Repository microsoft/LightGBM, pull requests merged in 2019-12, with the labels that each got.

#2601 [docs] fixed broken link in docs
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: blocking

#2447 [python] Allow python sklearn interface's fit() to pass init_model to train()
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: awaiting-response

#2623 [docs] fixed broken link in docs
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: blocking

#2530 [R-package][ci] added CI stage for R package (fixes #2335, fixes #2569)
  .ci/test.sh
  .ci/test_r_package.sh
  .travis.yml
  .vsts-ci.yml
  R-package/.Rbuildignore
  R-package/DESCRIPTION
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.prepare_rules2.Rd
  R-package/src/install.libs.R
  R-package/tests/testthat.R
  build_r.R
Labels: in-process

#2637 [python] specify the last supported version of scikit-learn
  .appveyor.yml
  .ci/test.sh
  .vsts-ci.yml
  docker/dockerfile-python
  docker/gpu/dockerfile.gpu
  docs/GPU-Tutorial.rst
  docs/Python-API.rst
  docs/Python-Intro.rst
  examples/python-guide/README.md
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  python-package/setup.py
Labels: blocking
