Repository microsoft/LightGBM, pull requests merged in 2019-11, with the labels that each got.

#2543 [R-package] removed unnecessary Suggests dependencies
  R-package/DESCRIPTION
Labels: awaiting-review

#2565 Fix detecting alias of objective in loading model from strings
  include/LightGBM/config.h
  src/boosting/gbdt_model_text.cpp
  src/io/config.cpp
Labels: blocking

#2540 Fix build error when HDFS is enabled.
  src/io/file_io.cpp
Labels: awaiting-review, blocking

#2548 Update LambdaRank example documentation
  examples/lambdarank/README.md
Labels: in-process

#2581 [R-package] fixed minor issues with tests and documentation
  R-package/R/lgb.cv.R
  R-package/R/lgb.prepare_rules2.R
  R-package/R/lightgbm.R
  R-package/tests/testthat/test_parameters.R
Labels: awaiting-review
