Repository microsoft/LightGBM, pull requests merged in 2020-10, with the labels that each got.

#3429 [ci] rename R-package GitHub Actions workflow
  .github/workflows/r_package.yml
Labels: maintenance

#3430 Update callback.R with keyword arguments
  R-package/R/callback.R
Labels: maintenance

#3434 [R-package] add 'cleanup' script to handle left-behind Makevars
  .ci/test_r_package.sh
  R-package/cleanup
Labels: maintenance

#3435 [R-package] [ci] Make Windows CI fail if R CMD check fails
  .ci/test_r_package_windows.ps1
Labels: fix

#3437 fix type casting warning
  swig/StringArray.hpp
Labels: fix

#3417 Move Tree destructor to header file
  include/LightGBM/tree.h
  src/io/tree.cpp
Labels: fix

#3446 [docs] update GitHub Actions badge
  README.md
Labels: doc

#3408 added new GPU docker files
  docker/gpu/README.md
  docker/gpu/dockerfile-cli-only-distroless.gpu
  docker/gpu/dockerfile-cli-only.gpu
Labels: feature

#3439 [R-package] [ci] Add test on R package with sanitizers
  .github/workflows/r_package.yml
Labels: awaiting review, maintenance

#3360 [R-package] Remove ability to install precompiled lib_lightgbm (fixes #3320)
  R-package/README.md
  R-package/src/install.libs.R
Labels: breaking

#3449 pin Ubuntu version in distroless docker file
  docker/gpu/README.md
  docker/gpu/dockerfile-cli-only-distroless.gpu
Labels: fix

#3452 [R-package] Updated lgb.train.R with keyword arguments
  R-package/R/lgb.train.R
Labels: maintenance

#3460 [R-package] Suppresses unknown pragma warnings during CRAN build
  .ci/test_r_package.sh
  build-cran-package.sh
Labels: fix

#3306 Updated network retry delay strategy to scale
  include/LightGBM/c_api.h
  src/network/linkers_socket.cpp
Labels: feature

#3444 [R-package] remove deprecation warnings on lgb.prepare() functions
  R-package/NAMESPACE
  R-package/R/removed.R
  R-package/man/lgb.prepare.Rd
  R-package/man/lgb.prepare2.Rd
  R-package/man/lgb.prepare_rules.Rd
  R-package/man/lgb.prepare_rules2.Rd
Labels: awaiting review, maintenance

#3468 [ci] ignore R CMD CHECK warnings on new R version
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
Labels: maintenance

#3443 [ci] [R-package] Fix memory leaks found by valgrind
  .ci/test_r_package_valgrind.sh
  .github/workflows/r_valgrind.yml
  R-package/R/lgb.Predictor.R
  R-package/README.md
  R-package/src/R_object_helper.h
  R-package/src/lightgbm_R.cpp
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_utils.R
  include/LightGBM/utils/log.h
  src/boosting/gbdt_model_text.cpp
  src/treelearner/monotone_constraints.hpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: fix

#3464 [R-package] Updated lgb.Predictor.R with keyword arguments
  R-package/R/lgb.Predictor.R
Labels: maintenance

#3472 [R-package] Improves logging in lint_r_code.R (fixes #3471)
  .ci/lint_r_code.R
Labels: maintenance

#3477 [ci] update SWIG installation on macOS
  .ci/setup.sh
  .vsts-ci.yml
Labels: maintenance

#3424 setup CUDA CI job
  .ci/setup.sh
  .github/workflows/cuda.yml
Labels: maintenance

#3431 Add support for cuda version less then 10.0
  include/LightGBM/cuda/vector_cudahost.h
Labels: feature

#2754 Fix add features
  include/LightGBM/feature_group.h
  python-package/lightgbm/basic.py
  src/io/dataset.cpp
  tests/python_package_test/test_basic.py
Labels: fix

#3425 Add support to optimize for NDCG at a given truncation level
  R-package/tests/testthat/test_learning_to_rank.R
  docs/Parameters.rst
  include/LightGBM/config.h
  src/objective/rank_objective.hpp
  tests/python_package_test/test_sklearn.py
Labels: feature

#3485 speed up multi-threading sum
  include/LightGBM/utils/threading.h
  src/treelearner/leaf_splits.hpp
Labels: efficiency

#3492 avoid min_data and min_hessian are zeros at the same time
  src/io/config.cpp
Labels: fix

#3495 [docs] fix param docs
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#3486 [ci] [python] reduce unnecessary data loading in tests
  .gitignore
  tests/python_package_test/__init__.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_plotting.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/utils.py
Labels: maintenance

#3505 [ci] Update MacOS version at Travis
  .travis.yml
Labels: maintenance

#3504 [tests][python] remove excess iterations
  tests/python_package_test/test_basic.py
Labels: maintenance

#3501 bump minimal CMake version
  CMakeLists.txt
Labels: breaking

#3503 [docs] added Data Science Bowl Comp Solution 2019
  examples/README.md
Labels: doc

#3496 [R-package] Updated lgb.Booster.R with keyword arguments
  R-package/R/lgb.Booster.R
Labels: maintenance

#3509 [R-package] remove unused variables in configure.ac
  R-package/configure
  R-package/configure.ac
Labels: maintenance
