Repository microsoft/LightGBM, pull requests merged in 2020-06, with the labels that each got.

#3119 [ci] use GitHub Actions for R CI jobs (fixes #2353)
  .ci/setup.sh
  .ci/test_r_package.sh
  .github/workflows/main.yml
  .travis.yml
  .vsts-ci.yml
Labels: maintenance

#3124 [ci] make MiKTeX downloads more reliable
  .ci/test_r_package_windows.ps1
Labels: maintenance

#3129 [python][scikit-learn] add new attribute for used number of features
  python-package/lightgbm/sklearn.py
Labels: feature

#3140 [R-package] Turn matrix to storage mode "double"
  R-package/R/lgb.Predictor.R
  R-package/tests/testthat/test_Predictor.R
Labels: fix

#3117 [R-package] fix best_score using custom evaluation (fixes #3112)
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_custom_objective.R
Labels: awaiting review, fix

#3141 fix error C3861: '_BitScanReverse': identifier not found
  include/LightGBM/utils/common.h
Labels: fix

#3148 fix str2double for `leaf_weights`
  src/io/tree.cpp
Labels: fix

#3157 [ci][docs] temporarily pin Sphinx version
  docs/requirements_base.txt
  docs/requirements_rtd.txt
Labels: blocking, maintenance

#3022 refactor LGBM_DatasetGetFeatureNames
  R-package/src/lightgbm_R.cpp
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  tests/python_package_test/test_basic.py
Labels: breaking

#3162 [ci] avoid VS warning for R builds
  .ci/test_r_package_windows.ps1
Labels: maintenance

#3065 [R-package] Add support for R 4.0 (fixes #3064, fixes #3024)
  .appveyor.yml
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/main.yml
  .gitignore
  .vsts-ci.yml
  R-package/README.md
  R-package/inst/make-r-def.R
  R-package/src/cmake/modules/FindLibR.cmake
  R-package/src/install.libs.R
  build_r.R
  docs/GPU-Windows.rst
Labels: awaiting review, feature

#3168 [ci] Move R Windows CI to GitHub Actions
  .appveyor.yml
  .ci/test_r_package_windows.ps1
  .github/workflows/main.yml
  .vsts-ci.yml
Labels: maintenance

#3176 [ci][docs] fix broken links
  docs/.linkcheckerrc
  docs/GPU-Windows.rst
  docs/README.rst
  docs/make.bat
Labels: blocking, doc

#3175 [ci] update Boost version
  .ci/setup.sh
Labels: maintenance

#3164 [docs][scikit-learn] removed duplicated docstrings
  docs/requirements_base.txt
  docs/requirements_rtd.txt
  python-package/lightgbm/sklearn.py
Labels: doc

#3169 [R-package] [ci] cut nrounds in unit tests
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.importance.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
  R-package/tests/testthat/test_parameters.R
Labels: maintenance

#3179 [ci][docs] added GitHub Actions badge and simplified condition in config
  .github/workflows/main.yml
  README.md
Labels: maintenance

#3126 Interaction constraints
  R-package/R/lgb.train.R
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/tree.h
  include/LightGBM/utils/common.h
  python-package/lightgbm/basic.py
  src/boosting/gbdt.cpp
  src/boosting/rf.hpp
  src/io/config.cpp
  src/io/config_auto.cpp
  src/io/tree.cpp
  src/treelearner/col_sampler.hpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/feature_parallel_tree_learner.cpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/gpu_tree_learner.h
  src/treelearner/parallel_tree_learner.h
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  src/treelearner/voting_parallel_tree_learner.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#3181 [R-package] fix R CMD check NOTE about leftover files
  .ci/test_r_package_windows.ps1
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.Dataset.save.Rd
  R-package/man/lgb.Dataset.set.categorical.Rd
  R-package/man/lgb.load.Rd
  R-package/man/lgb.save.Rd
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_parameters.R
Labels: maintenance

#3171 Adding static library option
  CMakeLists.txt
Labels: feature

#3193 [R-package] [ci] update to R 4.0.2 for Windows CI jobs (fixes #3191)
  .ci/test_r_package_windows.ps1
Labels: fix

#3190 [docs] document option to build a static library
  CMakeLists.txt
  docs/Installation-Guide.rst
Labels: doc

#3173 [python][scikit-learn] new stacking tests and make number of features a property
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#3189 Fix bug with interaction constraints
  src/treelearner/col_sampler.hpp
  tests/python_package_test/test_engine.py
Labels: fix

#3000 adding sparse support to TreeSHAP in lightgbm
  include/LightGBM/boosting.h
  include/LightGBM/c_api.h
  include/LightGBM/meta.h
  include/LightGBM/tree.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  src/application/predictor.hpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/c_api.cpp
  src/io/tree.cpp
  tests/python_package_test/test_engine.py
Labels: feature
