Repository microsoft/LightGBM, pull requests merged in 2020-11, with the labels that each got.

#3510 [R-package] fix MM_PREFETCH and MM_MALLOC checks in configure.ac
  .gitignore
  R-package/configure
  R-package/configure.ac
Labels: fix

#3494 Support deterministic
  docs/Parameters.rst
  include/LightGBM/config.h
  src/io/config.cpp
  src/io/config_auto.cpp
  src/treelearner/leaf_splits.hpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: feature

#3508 [R-package] [docs] fix broken plots in pkgdown site (fixes #3276)
  docs/conf.py
Labels: doc

#3530 [ci] fix check-docs error with AMD support website (fixes #3529)
  docs/.linkcheckerrc
Labels: blocking, maintenance

#3523 [R-package] [ci] add correct path for mingw32-make in CI
  .ci/test_r_package_windows.ps1
Labels: maintenance

#3528 [R-package] remove Makefile hack in install.libs.R
  R-package/src/install.libs.R
Labels: maintenance

#3524 [ci] upgrade GitHub Actions third-party actions to newest versions
  .github/workflows/cuda.yml
  .github/workflows/r_artifacts.yml
  .github/workflows/r_package.yml
  .github/workflows/r_valgrind.yml
Labels: maintenance

#3527 ignore files from local Dask work
  .gitignore
Labels: maintenance

#3521 better document for bin_construct_sample_cnt
  docs/Parameters.rst
  include/LightGBM/config.h
  src/io/dataset_loader.cpp
Labels: doc

#3526 fix invalid read detected by valgrind
  src/treelearner/leaf_splits.hpp
Labels: maintenance

#3536 [ci] Make valgrind check stricter
  .ci/test_r_package_valgrind.sh
Labels: maintenance

#3534 [R-package] fix learning-to-rank tests on Solaris
  R-package/tests/testthat/test_learning_to_rank.R
Labels: fix

#3537 Fix #2898: Clearer warning message for user (2^max_depth > num_leaves).
  src/io/config.cpp
Labels: doc

#3535 [ci] simplify R CI scripts
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
Labels: maintenance

#3541 [R-package] [ci] Fix failures with R 3.6 and CMake (fixes #3469)
  CMakeLists.txt
Labels: fix

#3547 move APPLE_OUTPUT_DYLIB option closer to the rest options
  CMakeLists.txt
Labels: maintenance

#3533 TST make sklearn integration test compatible with 0.24
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#3545 fix constant hessian for huber objective
  src/objective/regression_objective.hpp
Labels: fix

#3549 [ci] fix CUDA CI builds
  .github/workflows/cuda.yml
Labels: fix

#3553 Add note on LightGBM/OpenMP hanging on AWS Batch
  docs/FAQ.rst
Labels: doc

#3554 [docs] simplify RTD config and use latest Sphinx
  docs/requirements_base.txt
  docs/requirements_rtd.txt
Labels: doc

#3522 Optimization of row-wise histogram construction
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  include/LightGBM/bin.h
  include/LightGBM/dataset.h
  include/LightGBM/feature_group.h
  include/LightGBM/train_share_states.h
  include/LightGBM/utils/threading.h
  src/io/bin.cpp
  src/io/dataset.cpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/io/train_share_states.cpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  src/treelearner/voting_parallel_tree_learner.cpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: efficiency

#3558 [ci] Use different PATH based on Rtools version
  .ci/test_r_package_windows.ps1
Labels: fix

#3563 fix warning
  include/LightGBM/feature_group.h
Labels: maintenance

#3564 fix compilation warning
  include/LightGBM/train_share_states.h
Labels: maintenance

#3565 [python] mark 3.1 version is the last one with Python 2 support
  python-package/lightgbm/__init__.py
Labels: breaking

#3573 [ci] remove conda from R CI jobs
  .ci/setup.sh
  .ci/test.sh
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
Labels: maintenance

#3568 bump version for development
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#3579 [python] remove unnecessary files to reduce sdist size
  python-package/MANIFEST.in
Labels: maintenance

#3582 small R Docker cleanup
  docker/dockerfile-r
Labels: maintenance

#3566 [R-package] Remove CLI-only objects
  CMakeLists.txt
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  build-cran-package.sh
  src/application/application.cpp
  src/boosting/gbdt.cpp
Labels: maintenance

#3587 [ci] Fix missing git install in R artifact job (fixes #3567)
  .github/workflows/r_artifacts.yml
Labels: maintenance

#3575 remove max_block_size_ in train states (fix #3570)
  include/LightGBM/train_share_states.h
  include/LightGBM/utils/threading.h
  src/io/train_share_states.cpp
Labels: fix

#3578 fix deterministic, part2
  src/objective/binary_objective.hpp
  src/objective/regression_objective.hpp
  src/objective/xentropy_objective.hpp
Labels: fix

#3588 [ci] test 32-bit R in CI
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  R-package/tests/testthat/test_learning_to_rank.R
Labels: maintenance

#3590 Fix #3557 and potential issue with dense multi-val feature groups.
  include/LightGBM/feature_group.h
  src/io/dataset.cpp
  src/io/dataset_loader.cpp
Labels: fix

#3538 [refactor] SWIG - Split pointer manipulation to individual .i file
  swig/lightgbmlib.i
  swig/pointer_manipulation.i
Labels: maintenance

#3539 [refactor] Reduce code duplication in c_api.cpp
  src/c_api.cpp
Labels: maintenance

#3593 [python] fix regex in MANIFEST file
  python-package/MANIFEST.in
Labels: fix

#3594 [python] Allow to build Python wheel package
  .ci/test.sh
  .travis.yml
  python-package/README.rst
  python-package/setup.py
Labels: feature

#3600 [R-package][tests] update values in valgrind test
  .ci/test_r_package_valgrind.sh
Labels: maintenance

#3602 [ci] remove unnecessary environment variables in R-package CI
  .github/workflows/r_package.yml
Labels: maintenance

#3604 [R-package] use keyword arguments for internal functions in utils.R
  R-package/R/utils.R
Labels: maintenance

#3605 [R-package] Update lgb.model.dt.tree.R to use keyword arguments
  R-package/R/lgb.model.dt.tree.R
Labels: maintenance

#3560 [R-package] use as.factor() instead of factor() in lgb.cv()
  R-package/R/lgb.cv.R
Labels: efficiency

#3574 [R-package] Use command-line args to customize CMake builds (fixes #2441)
  .ci/test_r_package_windows.ps1
  R-package/README.md
  build_r.R
Labels: feature

#3609 [docs][R-package] fix typo
  R-package/README.md
Labels: doc

#3610 [docs] Add new badges
  R-package/README.md
  README.md
  python-package/README.rst
Labels: doc

#3612 [R-package] {lightgbm} is now available on CRAN (fixes #629)
  R-package/README.md
Labels: feature
