Repository microsoft/LightGBM, pull requests merged in 2020-12, with the labels that each got.

#3598 [R-package] construct dataset earlier in lgb.train and lgb.cv (fixes #3583)
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_dataset.R
Labels: fix

#3620 [ci] add credentials to gitignore
  .gitignore
Labels: maintenance

#3627 [docs] update documentation with AUC-mu, average precision
  docs/Features.rst
Labels: doc

#3592 Check max_bin, etc. match config when using binary
  include/LightGBM/dataset_loader.h
  src/io/dataset_loader.cpp
Labels: fix

#3631 fix typo in dataset checks
  src/io/dataset_loader.cpp
Labels: fix

#3630 [R-package] fix partial matching of keyword arguments in lgb.cv() (fixes #3629)
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  R-package/R/lgb.cv.R
Labels: blocking, fix

#3618 [python] more detailed docs for trees_to_dataframe(), create_tree_digraph(), plot_tree()
  python-package/lightgbm/basic.py
  python-package/lightgbm/plotting.py
Labels: doc

#3611 release 3.1.1
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#3632 [docs] add Kubeflow operator repo and link to example
  README.md
  docs/Parallel-Learning-Guide.rst
Labels: doc

#3633 [ci] Bump version for development
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#3581 [python] Drop Python 2 support
  .appveyor.yml
  .ci/test.sh
  .ci/test_windows.ps1
  .travis.yml
  .vsts-ci.yml
  docker/gpu/README.md
  docker/gpu/dockerfile.gpu
  docs/conf.py
  docs/requirements_base.txt
  examples/python-guide/advanced_example.py
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
  python-package/setup.py
  tests/python_package_test/test_consistency.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/utils.py
Labels: breaking

#3638 [docs] added daal4py to related projects
  README.md
Labels: doc

#3615 clarify warning about small target values with MAPE (fixes #3608)
  src/objective/regression_objective.hpp
Labels: maintenance

#3639 [python-package] remove unnecessary files to reduce sdist size
  python-package/MANIFEST.in
Labels: maintenance

#3644 [docs] fix RTD builds
  docs/conf.py
Labels: blocking, maintenance

#3628 [docs] Add details on improving training speed
  docs/Parameters-Tuning.rst
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#3649 [python] add average precision into higher_better eval
  python-package/lightgbm/basic.py
Labels: fix

#3403 [python] Windows wheels that support GPUs via OpenCL
  .ci/install_opencl.ps1
  .ci/test_windows.ps1
  .vsts-ci.yml
  python-package/setup.py
  tests/python_package_test/test_dual.py
Labels: feature

#3663 [docs] add link to ML Flow and treesnip in LightGBM docs
  README.md
Labels: doc

#3660 [docs][ci] added docs about GPU support out of the box for Windows wheels and small refactoring for dual test
  .appveyor.yml
  .ci/install_opencl.ps1
  .ci/test_windows.ps1
  .vsts-ci.yml
  docs/GPU-Targets.rst
  docs/GPU-Windows.rst
  python-package/README.rst
  tests/python_package_test/test_dual.py
Labels: maintenance

#3668 [docs] fix MLflow spelling
  README.md
Labels: doc

#3515 [python] [dask] add initial dask integration
  .ci/test.sh
  .github/CODEOWNERS
  python-package/lightgbm/dask.py
  python-package/setup.py
  tests/python_package_test/test_dask.py
Labels: feature

#3680 [docs] add link to optuna examples
  README.md
Labels: doc

#3682 [ci] speed up files downloading for Windows CI
  .ci/install_opencl.ps1
  .ci/test_r_package_windows.ps1
  .ci/test_windows.ps1
  .vsts-ci.yml
Labels: maintenance

#3688 [ci] remove unused CI checks, other small simplifications
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
Labels: maintenance

#3681 small code and docs refactoring
  CMakeLists.txt
  docs/Parameters.rst
  include/LightGBM/c_api.h
  include/LightGBM/config.h
  src/c_api.cpp
  src/io/config.cpp
  src/io/dataset_loader.cpp
  src/io/tree.cpp
  src/treelearner/linear_tree_learner.cpp
  src/treelearner/linear_tree_learner.h
  src/treelearner/tree_learner.cpp
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#3690 [docs] add doc on min_data_in_leaf approximation (fixes #3634)
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#3685 [python-package] remove unused Eigen files, compile with EIGEN_MPL2_ONLY (fixes #3684)
  CMakeLists.txt
  python-package/MANIFEST.in
  src/treelearner/linear_tree_learner.cpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: efficiency

#3692 [ci] fix deprecated 'brew cask install' call
  .ci/test_r_package.sh
Labels: maintenance
