Repository microsoft/LightGBM, pull requests merged in 2020-05, with the labels that each got.

#2963 [R-package] CMake fixes to support MSVC
  CMakeLists.txt
  R-package/src/cmake/modules/FindLibR.cmake
Labels: fix

#3032 [docs] updated bug report template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: doc

#2950 Path smoothing
  .ci/test_r_package.sh
  docs/Parameters-Tuning.rst
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/tree.h
  src/io/config.cpp
  src/io/config_auto.cpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/leaf_splits.hpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/voting_parallel_tree_learner.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#3046 [R-package] add conda dir for LIBR_CORE_LIBRARY (fixes #3045)
  R-package/src/cmake/modules/FindLibR.cmake
Labels: fix

#3037 [docs] updated docs about output values
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: doc

#3050 [docs] update ROCm link in docs
  docs/GPU-Targets.rst
Labels: maintenance

#3056 [ci] fix flaky test
  .vsts-ci.yml
Labels: blocking, maintenance

#3055 typo fix
  src/io/dataset.cpp
Labels: maintenance

#3059 [python-package] Use set for OS check
  python-package/setup.py
Labels: maintenance

#3063 fix goss bug
  src/boosting/goss.hpp
Labels: fix

#3020 [R-package] added tests on LGBM_BoosterResetTrainingData_R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#3073 removed deprecated code
  python-package/lightgbm/plotting.py
  src/objective/binary_objective.hpp
Labels: maintenance

#3078 Document cmake+MinGW (fixes #3060)
  docs/FAQ.rst
Labels: doc

#3081 [docs] document one more workaround for CMake and MinGW build and fix typos
  R-package/tests/testthat/test_lgb.Booster.R
  docs/FAQ.rst
Labels: doc

#3079 Update CODEOWNERS rule about CMakeLists.txt
  .github/CODEOWNERS
Labels: maintenance

#3085 [docs] update link to GitHub anchor conventions
  docs/FAQ.rst
Labels: blocking, fix

#2965 [R-package] speed up installation with Visual Studio
  .appveyor.yml
  .ci/test_r_package_windows.ps1
  .vsts-ci.yml
  R-package/DESCRIPTION
  R-package/src/install.libs.R
  build_r.R
Labels: maintenance

#3072 [R-package] [docs] remove devtools dependency for docs builds (fixes #3036)
  R-package/pkgdown/_pkgdown.yml
  R-package/pkgdown/extra.js
  build_r.R
  build_r_site.R
  docs/conf.py
Labels: maintenance

#3077 fix goss with constant hessian
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/boosting/goss.hpp
Labels: fix

#3070 [R-package] [docs] Removed outdated language about the R package
  docs/GPU-Windows.rst
Labels: awaiting review, doc

#3069 [R-package] fix warnings in tests
  R-package/tests/testthat/test_basic.R
Labels: awaiting review, maintenance

#3092 [R-package] [ci] Fix CI timeouts for Mac builds on Travis (fixes #3091)
  .ci/test_r_package.sh
Labels: blocking, fix

#3086 [R-package] [docs] fix warnings in pkgdown site building
  .gitignore
  R-package/R/lightgbm.R
  R-package/man/lgb_shared_params.Rd
  R-package/pkgdown/_pkgdown.yml
Labels: doc

#3096 [ci] avoid duplicate AppVeyor builds
  .appveyor.yml
Labels: maintenance

#3089 fix refactoring bug in voting parallel
  src/treelearner/feature_histogram.hpp
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: fix

#3098 [R-package] [docs] replace build_r_site.R with pkgdown::build_site()
  build_r_site.R
  docs/conf.py
Labels: maintenance

#3105 [R-package] characterize all cmake messages
  R-package/src/cmake/modules/FindLibR.cmake
Labels: maintenance

#3104 [ci] fix add-apt-repository warning
  .ci/test_r_package.sh
Labels: maintenance

#3090 redirect log to python console
  include/LightGBM/c_api.h
  include/LightGBM/utils/log.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
Labels: feature

#3080 Optimize the computation of the cross-entropy ranking loss
  src/objective/rank_objective.hpp
Labels: awaiting review, efficiency

#3108 Fixed machine list parsing: s/find_first_of/find
  src/network/linkers_socket.cpp
Labels: fix

#3068 fix MSVC warning about control paths (fixes #3067)
  src/boosting/prediction_early_stop.cpp
Labels: fix

#3114 fix a bug when we set the default score
  src/boosting/score_updater.hpp
Labels: fix

#3087 [R-package] move R source files into R-package, reduce duplication in build_r.R
  .ci/test.sh
  .github/CODEOWNERS
  R-package/.Rbuildignore
  R-package/src/R_object_helper.h
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  build_r.R
Labels: awaiting review, maintenance

#3101 [R-package] fix issue where early stopping thinks higher MAPE is desirable (fixes #3099)
  R-package/R/callback.R
  R-package/R/lgb.Booster.R
  R-package/R/metrics.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_metrics.R
Labels: awaiting review, fix

#3110 memory corruption fix for distributed data parallel version before SyncUpGlobalBestSplit
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/feature_parallel_tree_learner.cpp
  src/treelearner/split_info.hpp
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: fix

#3125 [ci] remove unused environment variable in CI setups
  .travis.yml
  .vsts-ci.yml
Labels: maintenance
