Repository microsoft/LightGBM, pull requests merged in 2020-04, with the labels that each got.

#2958 [SWIG][mmlspark] fix seg fault in LGBM_BoosterGetEvalNamesSWIG
  swig/StringArray_API_extensions.i
Labels: fix

#2911 [R-package] adding routine registration in R package (fixes #1910)
  .ci/test_r_package.sh
  CMakeLists.txt
  R-package/.Rbuildignore
  R-package/src/install.libs.R
  src/lightgbm_R.cpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: feature

#2962 [ci] reduce duplication in Python Windows CI
  .appveyor.yml
  .ci/test_windows.ps1
  .vsts-ci.yml
Labels: maintenance

#2931 Cleanup MissingType enum constants
  include/LightGBM/tree.h
  src/io/tree.cpp
Labels: maintenance

#2938 replace built-in assert with own CHECK macro
  src/io/json11.cpp
Labels: maintenance

#2969 [ci] upgrade to R 3.6.3 in CI
  .travis.yml
  .vsts-ci.yml
Labels: maintenance

#2971 fixed cpplint errors
  include/LightGBM/utils/openmp_wrapper.h
  src/io/tree.cpp
  src/lightgbm_R.cpp
Labels: maintenance

#2929 fixed cpplint errors about string& members
  src/io/json11.cpp
Labels: maintenance

#2977 [ci][docs] downdrage sphinx and fix LaTeX error in R-package tests
  .ci/test_r_package.sh
  docs/requirements_base.txt
Labels: blocking, maintenance

#2978 [docs] update URL in docs
  docs/GPU-Targets.rst
Labels: maintenance

#2982 [ci][docs] downgrade breathe
  docs/requirements.txt
Labels: blocking, maintenance

#2975 fix cpp lint in json11
  include/LightGBM/utils/json11.h
  src/boosting/gbdt.cpp
  src/io/dataset_loader.cpp
  src/io/json11.cpp
Labels: maintenance

#2945 [R-package] Added unit tests on creating Booster from file or string
  R-package/R/lgb.Booster.R
  R-package/README.md
  R-package/tests/testthat/test_lgb.Booster.R
Labels: awaiting review, maintenance

#2939 Pr3 monotone constraints splits penalization
  docs/Parameters.rst
  include/LightGBM/config.h
  src/io/config.cpp
  src/io/config_auto.cpp
  src/treelearner/monotone_constraints.hpp
  src/treelearner/serial_tree_learner.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#2949 [python] Re-enable scikit-learn 0.22+ support
  .ci/test.sh
  .ci/test_windows.ps1
  docker/dockerfile-python
  docker/gpu/dockerfile.gpu
  docs/GPU-Tutorial.rst
  docs/Python-API.rst
  docs/Python-Intro.rst
  examples/python-guide/README.md
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  python-package/setup.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#2980 Revert "Fix Booster read/write locale dependency (#2891)"
  include/LightGBM/utils/locale_context.h
  src/c_api.cpp
Labels: fix

#2990 [ci] fixed r-lintr version constraint
  .ci/test.sh
  .ci/test_r_package.sh
Labels: blocking, maintenance

#2713 [python][ci] start to support Python 3.8
  .travis.yml
  .vsts-ci.yml
  python-package/setup.py
Labels: maintenance

#2985 more cpp lints
  include/LightGBM/utils/common.h
  src/io/dataset.cpp
  src/io/tree.cpp
  src/network/socket_wrapper.hpp
Labels: maintenance

#2996 Update CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#2989 [R-package] [docs] Simplified examples to cut example run time (fixes #2988)
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.importance.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.plot.importance.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.prepare.R
  R-package/R/lgb.prepare2.R
  R-package/R/lgb.prepare_rules.R
  R-package/R/lgb.prepare_rules2.R
  R-package/R/lgb.train.R
  R-package/R/lgb.unloader.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/dim.Rd
  R-package/man/dimnames.lgb.Dataset.Rd
  R-package/man/getinfo.Rd
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.Dataset.construct.Rd
  R-package/man/lgb.Dataset.create.valid.Rd
  R-package/man/lgb.Dataset.save.Rd
  R-package/man/lgb.Dataset.set.categorical.Rd
  R-package/man/lgb.Dataset.set.reference.Rd
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.dump.Rd
  R-package/man/lgb.get.eval.result.Rd
  R-package/man/lgb.importance.Rd
  R-package/man/lgb.interprete.Rd
  R-package/man/lgb.load.Rd
  R-package/man/lgb.plot.importance.Rd
  R-package/man/lgb.plot.interpretation.Rd
  R-package/man/lgb.prepare.Rd
  R-package/man/lgb.prepare2.Rd
  R-package/man/lgb.prepare_rules.Rd
  R-package/man/lgb.prepare_rules2.Rd
  R-package/man/lgb.save.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lgb.unloader.Rd
  R-package/man/lgb_shared_params.Rd
  R-package/man/lightgbm.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  R-package/man/setinfo.Rd
  R-package/man/slice.Rd
Labels: maintenance

#2994 [R-package] Removed unused constant in R_object_helper.h
  include/LightGBM/R_object_helper.h
Labels: maintenance

#2993 [R-package] Updated package metadata in DESCRIPTION
  R-package/DESCRIPTION
Labels: maintenance

#2973 [ci] Changed use of strcpy to snprintf (fixes #1990)
  .ci/test.sh
  include/LightGBM/c_api.h
Labels: awaiting review, maintenance

#3001 [docs] updated core team list
  docs/FAQ.rst
Labels: doc

#2859 [mmlspark] allow allocating more than int max array
  swig/lightgbmlib.i
Labels: feature

#3002 [R-package] fix R examples and lgb.plot.interpretation()
  .gitignore
  R-package/DESCRIPTION
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.prepare_rules.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/agaricus.test.Rd
  R-package/man/agaricus.train.Rd
  R-package/man/bank.Rd
  R-package/man/lgb.Dataset.set.categorical.Rd
  R-package/man/lgb.plot.interpretation.Rd
  R-package/man/lgb.prepare_rules.Rd
  R-package/man/lgb.save.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  docs/FAQ.rst
  docs/conf.py
Labels: fix

#3013 [ci][docs] be compatible with Sphinx 3
  docs/conf.py
  docs/requirements.txt
  docs/requirements_base.txt
Labels: maintenance

#3015 [ci][docs] Fix RTD builds
  .readthedocs.yml
  docs/requirements_rtd.txt
Labels: maintenance

#3009 [R-package] [ci] added echoing of R CMD check logs to CI
  .ci/test_r_package.sh
Labels: maintenance

#3019 [ci] minor CI scripts update
  .ci/setup.sh
  .ci/test_r_package.sh
  .travis.yml
  docker/dockerfile-python
  docker/gpu/dockerfile.gpu
Labels: maintenance

#3021 [docs] update link to Julia wrapper
  README.md
Labels: doc

#3007 [R-package] Added tests on creating a Booster from a Dataset
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#3005 [R-package] Added tests on LGBM_GetLastError_R
  R-package/R/utils.R
  R-package/tests/testthat/test_utils.R
Labels: awaiting review, maintenance

#3004 [R-package] [docs] remove unnecessary build in test coverage
  R-package/README.md
Labels: awaiting review, doc

#3006 [R-package] added tests on LGBM_BoosterRollbackOneIter_R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#2961 [R-package] fixed best_iter and best_score when training data is passed (fixes #2295, #2525)
  R-package/R/callback.R
  R-package/R/lgb.Booster.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#3023 [python][tests] unused and missing imports
  tests/c_api_test/test_.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#2936 [R-package] [ci] Add Windows CI for R package (fixes #2335)
  .appveyor.yml
  .ci/test_r_package_windows.ps1
  .ci/test_windows.ps1
  .vsts-ci.yml
  R-package/NAMESPACE
  R-package/R/lightgbm.R
  R-package/src/cmake/modules/FindLibR.cmake
  R-package/src/install.libs.R
Labels: awaiting review, maintenance

#3035 [R-package] Remove lgbdl from docs until fix
  R-package/README.md
Labels: doc

#3031 Fix loss computation in rank cross-entropy objective
  src/objective/rank_objective.hpp
  tests/python_package_test/test_sklearn.py
Labels: fix
