Repository microsoft/LightGBM, pull requests merged in 2020-07, with the labels that each got.

#3199 [R-package] [ci] Fix MiKTeX downloads (fixes #3198)
  .ci/test_r_package_windows.ps1
  .gitignore
Labels: maintenance

#3197 Allow the minimal feature to 1 in column sampling
  src/treelearner/col_sampler.hpp
Labels: maintenance

#3136 [R-package] Interface for interaction constraints
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
  R-package/tests/testthat/test_basic.R
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: feature, in progress

#3208 [ci] bump gcc version for macOS
  .ci/setup.sh
  .ci/test.sh
Labels: blocking, maintenance

#3205 [ci] [R-package] catch builds that have not updated docs
  .ci/test.sh
  .ci/test_r_package.sh
  .github/workflows/main.yml
Labels: maintenance

#3211 [python] fix early_stopping_round = 0
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: fix

#3215 Remove extra semicolons
  include/LightGBM/utils/common.h
Labels: maintenance

#3214 [docs] Improve some phrasing in the installation guide
  docs/Installation-Guide.rst
Labels: doc

#3174 typo fix
  src/boosting/rf.hpp
Labels: doc

#3217 [R-package] remove unused Suggests dependencies
  R-package/DESCRIPTION
Labels: maintenance

#3216 [R-package] Add version floor of R 3.5 (fixes #3212)
  CMakeLists.txt
  R-package/DESCRIPTION
  R-package/README.md
  R-package/src/R_object_helper.h
  R-package/src/install.libs.R
Labels: breaking

#3223 [R-package] remove xlen_t in custom R-to-C++ interface
  R-package/src/R_object_helper.h
Labels: maintenance

#3225 [ci] bump R 4 version
  .ci/test_r_package.sh
Labels: blocking, maintenance

#3226 add rules for tests/ in CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#3222 [python][scikit-learn] Fixes a bug that prevented using multiple eval_metrics in LGBMClassifier
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: fix

#3220 feature importance type in saved model file
  R-package/R/lgb.Booster.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  docs/Parameters.rst
  include/LightGBM/boosting.h
  include/LightGBM/c_api.h
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  src/application/application.cpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/boosting/gbdt_model_text.cpp
  src/c_api.cpp
  src/io/config_auto.cpp
  swig/lightgbmlib.i
  tests/c_api_test/test_.py
Labels: feature

#2992 Feat/optimize single prediction
  include/LightGBM/c_api.h
  src/c_api.cpp
  swig/lightgbmlib.i
Labels: feature, in progress

#3228 Upcast index to size_t in Refit
  src/c_api.cpp
Labels: fix

#2760 feat: Change locking strategy of Booster, allow for share and unique locks
  include/LightGBM/utils/yamc/alternate_shared_mutex.hpp
  include/LightGBM/utils/yamc/yamc_rwlock_sched.hpp
  include/LightGBM/utils/yamc/yamc_shared_lock.hpp
  src/c_api.cpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: feature

#3224 [R-package] factor out {ggplot2}
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  R-package/DESCRIPTION
  R-package/demo/leaf_stability.R
Labels: awaiting review, maintenance

#3231 [R-package] add test on importance types
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#3233 [SWIG] removed commented code
  swig/lightgbmlib.i
Labels: maintenance

#3239 typo fix
  src/treelearner/serial_tree_learner.cpp
Labels: maintenance

#3240 [ci] remove unnecessary R_CHECK_FORCE_SUGGESTS in CI scripts
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#3235 [R-package] Add tests on lgb.check.eval, lgb.unloader, and lgb.encode.char
  R-package/DESCRIPTION
  R-package/R/lgb.unloader.R
  R-package/R/utils.R
  R-package/man/lgb.unloader.Rd
  R-package/tests/testthat/test_lgb.unloader.R
  R-package/tests/testthat/test_utils.R
Labels: maintenance

#3250 [R-package] remove duplicated test
  R-package/R/utils.R
  R-package/tests/testthat/test_utils.R
Labels: maintenance

#3251 [ci] partly remove macOS temp CI fix
  .ci/setup.sh
Labels: maintenance

#3242 fix possible problem in getting number of columns from libsvm file.
  src/io/parser.cpp
Labels: fix

#3246 fix bug in CEGB when reset training data or config
  src/treelearner/cost_effective_gradient_boosting.hpp
  src/treelearner/serial_tree_learner.cpp
Labels: fix

#3252 [docs] improve params docs
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#3188 [R-package] make package installable with CRAN toolchain (fixes #2960)
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/main.yml
  .gitignore
  R-package/.Rbuildignore
  R-package/AUTOCONF_UBUNTU_VERSION
  R-package/README.md
  R-package/configure
  R-package/configure.ac
  R-package/configure.win
  R-package/inst/Makevars
  R-package/inst/Makevars.win
  R-package/recreate-configure.sh
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  build-cran-package.sh
  build_r.R
  include/LightGBM/utils/common.h
Labels: blocking, feature

#3260 remove unnecessary semicolon
  include/LightGBM/utils/openmp_wrapper.h
Labels: maintenance

#3258 [TYPO] DatasetLoader::ConstructFromSampleData
  include/LightGBM/dataset_loader.h
  src/c_api.cpp
  src/io/dataset_loader.cpp
Labels: maintenance

#3261 [R-package] allow R to pick between -fPIC and -fpic for CRAN package
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
Labels: maintenance

#3265 [ci] run Travis and Azure Pipelines only for master branch
  .travis.yml
  .vsts-ci.yml
Labels: maintenance

#3253 [tests][python][scikit-learn] New unit tests and maintenance
  tests/python_package_test/test_sklearn.py
Labels: maintenance
