Repository microsoft/LightGBM, pull requests merged in 2020-03, with the labels that each got.

#2849 introduced specific CHECKs
  include/LightGBM/tree.h
  include/LightGBM/utils/log.h
  src/application/predictor.hpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt_model_text.cpp
  src/c_api.cpp
  src/io/bin.cpp
  src/io/dataset.cpp
  src/io/dataset_loader.cpp
  src/metric/dcg_calculator.cpp
  src/metric/regression_metric.hpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/serial_tree_learner.cpp
Labels: maintenance

#2839 don't save num_thread as possible
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/dataset.h
  include/LightGBM/utils/array_args.h
  include/LightGBM/utils/common.h
  include/LightGBM/utils/openmp_wrapper.h
  include/LightGBM/utils/threading.h
  src/application/predictor.hpp
  src/c_api.cpp
  src/io/dataset.cpp
  src/io/multi_val_sparse_bin.hpp
  src/io/sparse_bin.hpp
  src/metric/map_metric.hpp
  src/metric/rank_metric.hpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: fix

#2827 speed up multi-val bin subset for bagging
  include/LightGBM/bin.h
  include/LightGBM/dataset.h
  include/LightGBM/feature_group.h
  include/LightGBM/tree_learner.h
  src/boosting/gbdt.cpp
  src/boosting/rf.hpp
  src/c_api.cpp
  src/io/dataset.cpp
  src/io/dense_bin.hpp
  src/io/dense_nbits_bin.hpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/io/sparse_bin.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/gpu_tree_learner.h
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
Labels: efficiency

#2852 reduce the overhead of OMP_NUM_THREADS in training
  include/LightGBM/dataset.h
  src/io/dataset.cpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: efficiency

#2851 fix bug in parallel learning
  include/LightGBM/config.h
  src/application/application.cpp
  src/io/config.cpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: fix

#2847 [R-package] added test on training with sparse features
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#2857 speed up for const hessian
  include/LightGBM/bin.h
  include/LightGBM/dataset.h
  src/io/dataset.cpp
  src/io/dense_bin.hpp
  src/io/dense_nbits_bin.hpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/io/sparse_bin.hpp
Labels: efficiency

#2856 [ci] fix R tests for macOS on Azure Pipelines
  .ci/test_r_package.sh
Labels: blocking, maintenance

#2865 [docs] Fix description according to markdownlint
  README.md
Labels: maintenance

#2845 [R-package] removed unused imports from R-specific lib_lightgbm components
  include/LightGBM/R_object_helper.h
  include/LightGBM/lightgbm_R.h
  src/lightgbm_R.cpp
Labels: maintenance

#2861 [docs] update link to MS MPI
  docs/Installation-Guide.rst
Labels: maintenance

#2848 [R-package] [ci] added tests on early_stopping
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#2863 fixed cpplint issues
  R-package/tests/testthat/test_basic.R
  include/LightGBM/feature_group.h
  include/LightGBM/utils/common.h
  src/boosting/gbdt.cpp
  src/boosting/goss.hpp
  src/boosting/rf.hpp
  src/c_api.cpp
  src/io/bin.cpp
  src/io/dataset.cpp
  src/io/dataset_loader.cpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/lightgbm_R.cpp
  src/objective/regression_objective.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
Labels: maintenance

#2866 fix warnings in debug mode about that not all control paths return a value
  src/c_api.cpp
Labels: maintenance

#2864 use specific checks in auto config
  helpers/parameter_generator.py
  src/io/config_auto.cpp
Labels: maintenance

#2853 shrinkage to internal values
  include/LightGBM/tree.h
Labels: fix

#2846 [R-package] [docs] Added documentation on lgb.dl() and data.table version (fixes #2715)
  R-package/README.md
  docs/FAQ.rst
Labels: doc

#2589 [python] save all param values into model file
  helpers/parameter_generator.py
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  src/io/config_auto.cpp
  tests/python_package_test/test_engine.py
Labels: fix

#2843 add more bots
  .github/no-response.yml
  .github/release-drafter.yml
  .vsts-ci.yml
Labels: maintenance

#2882 fix ResetConfig in FeatureHistogram
  src/treelearner/feature_histogram.hpp
Labels: fix

#2887 [docs] update latest benchmark results
  docs/Experiments.rst
Labels: doc

#2837 [R-package] Introduce R-specific control of lib_lightgbm
  CMakeLists.txt
  R-package/src/install.libs.R
  src/io/json11.cpp
Labels: maintenance

#2844 [R-package] cleaned up formatting in R C/C++ files
  include/LightGBM/R_object_helper.h
  include/LightGBM/lightgbm_R.h
  src/lightgbm_R.cpp
Labels: awaiting review, maintenance

#2888 fixed cpplint errors and disable warning only for VS
  include/LightGBM/bin.h
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  include/LightGBM/meta.h
  include/LightGBM/utils/openmp_wrapper.h
  src/c_api.cpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/gpu_tree_learner.h
Labels: maintenance

#2896 [docs] add link to blog post about Optuna to Parameters-Tuning.rst
  docs/Parameters-Tuning.rst
Labels: doc

#2895 fix release-drafter.yml
  .github/release-drafter.yml
Labels: maintenance

#2909 [R-package] added command to remove build/ dir in install.libs.R
  R-package/src/install.libs.R
Labels: maintenance

#2917 [R-package] removed duplicated code figuring out build_dir in install.libs.R
  R-package/src/install.libs.R
Labels: maintenance

#2893 [docs] Add LightGBM Tuner by Optuna links to README.md
  README.md
Labels: doc

#2907 [python] fix the bug when use different params with reference
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: fix

#2906 [python] Fix continued train by reusing the same dataset
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: fix

#2891 Fix Booster read/write locale dependency
  include/LightGBM/utils/locale_context.h
  src/c_api.cpp
Labels: fix

#2803 [R-package] [ci] added more linters
  .ci/lint_r_code.R
  R-package/R/callback.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
  R-package/demo/basic_walkthrough.R
  R-package/demo/boost_from_prediction.R
  R-package/demo/cross_validation.R
  R-package/demo/early_stopping.R
  R-package/demo/multiclass.R
  R-package/demo/multiclass_custom_objective.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_parameters.R
Labels: maintenance

#2924 [ci] fix VS project files
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: maintenance

#2904 [python] handle RandomState object in Scikit-learn Api
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: awaiting review, feature

#2850 Fix SWIG methods that return char**
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  src/lightgbm_R.cpp
  swig/StringArray.hpp
  swig/StringArray.i
  swig/StringArray_API_extensions.i
  swig/lightgbmlib.i
Labels: fix

#2928 [R-package] fixed NOTE about unrecognized global variable
  R-package/R/lightgbm.R
Labels: maintenance

#2927 [ci] fixed cpplint errors about namespace using-directives
  src/c_api.cpp
  src/lightgbm_R.cpp
Labels: maintenance

#2903 [R-package] added test on uncovered line of lgb.plot.importance()
  R-package/tests/testthat/test_lgb.plot.importance.R
Labels: maintenance

#2914 [R-package] fixed handling of multiple evaluation metrics (fixes #2913)
  R-package/R/utils.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_utils.R
Labels: fix

#2916 [R-package] fixed evaluation on valids in lightgbm() (fixes #2915)
  R-package/R/lightgbm.R
  R-package/tests/testthat/test_basic.R
Labels: awaiting review, fix

#2908 [R-package] fixed some minor issues with testing on Windows
  .gitignore
  R-package/src/install.libs.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: awaiting review, fix

#2920 changed sprintf uses to snprintf
  include/LightGBM/utils/common.h
Labels: maintenance

#2770 Improving monotone constraints ("Fast" method; linked to #2305, #2717)
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/tree.h
  src/io/config.cpp
  src/io/config_auto.cpp
  src/io/tree.cpp
  src/treelearner/leaf_splits.hpp
  src/treelearner/monotone_constraints.hpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  tests/python_package_test/test_engine.py
Labels: feature

#2901 [R-package] Use Rprintf for logging in the R package (fixes #1440, fixes #1909)
  CMakeLists.txt
  R-package/src/cmake/modules/FindLibR.cmake
  R-package/src/install.libs.R
  include/LightGBM/R_object_helper.h
  include/LightGBM/utils/log.h
Labels: feature

#2942 [R-package] [ci] added check on number of R CMD CHECK notes
  .ci/test_r_package.sh
Labels: maintenance

#2954 [ci] changed CRAN mirror to fix failing installs
  .ci/test.sh
  .ci/test_r_package.sh
Labels: maintenance

#2956 [ci][docs] fixed broken link
  docs/Advanced-Topics.rst
  docs/Features.rst
Labels: blocking, maintenance

#2940 fix inf in json model dump
  src/boosting/gbdt_model_text.cpp
Labels: fix

#2957 [R-package] [ci] Add option to skip installation in build_r.R
  .ci/test_r_package.sh
  build_r.R
Labels: maintenance
