Repository microsoft/LightGBM, pull requests merged in 2020-08, with the labels that each got.

#3095 [R-package] deprecate lgb.prepare() and lgb.prepare2()
  R-package/NAMESPACE
  R-package/R/lgb.convert.R
  R-package/R/lgb.convert_with_rules.R
  R-package/R/lgb.prepare.R
  R-package/R/lgb.prepare_rules2.R
  R-package/R/removed.R
  R-package/demo/categorical_features_rules.R
  R-package/man/lgb.convert.Rd
  R-package/man/lgb.convert_with_rules.Rd
  R-package/man/lgb.prepare.Rd
  R-package/man/lgb.prepare2.Rd
  R-package/man/lgb.prepare_rules.Rd
  R-package/man/lgb.prepare_rules2.Rd
  R-package/pkgdown/_pkgdown.yml
  R-package/tests/testthat/test_lgb.convert.R
  R-package/tests/testthat/test_lgb.convert_with_rules.R
  R-package/tests/testthat/test_lgb.prepare.R
  R-package/tests/testthat/test_lgb.prepare_rules.R
Labels: awaiting review, breaking

#3259 [R-package] fix early_stopping_round <= 0
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#3204 [python] add return_cvbooster flag to cv func and publish _CVBooster (#283,#2105,#1445)
  docs/Python-API.rst
  python-package/lightgbm/__init__.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: feature

#3271 [R-package] add some R build files to gitignore
  .gitignore
Labels: maintenance

#3268 Fast single row predict API v2
  include/LightGBM/c_api.h
  src/c_api.cpp
  swig/lightgbmlib.i
Labels: fix

#3256 update multi-class objective (softmax)
  R-package/tests/testthat/test_basic.R
  src/objective/multiclass_objective.hpp
Labels: fix

#3263 create buffer for gradients and hessians with goss and customized objective (fixes #3243)
  src/boosting/goss.hpp
Labels: fix

#3275 [doc] better doc for `keep_training_booster`
  python-package/lightgbm/engine.py
Labels: doc

#3270 [R-package] move all examples to dontrun() to fix R CMD CHECK notes
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.convert.R
  R-package/R/lgb.convert_with_rules.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.importance.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.model.dt.tree.R
  R-package/R/lgb.plot.importance.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.train.R
  R-package/R/lgb.unloader.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/dim.Rd
  R-package/man/dimnames.lgb.Dataset.Rd
  R-package/man/getinfo.Rd
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.Dataset.construct.Rd
  R-package/man/lgb.Dataset.create.valid.Rd
  R-package/man/lgb.Dataset.save.Rd
  R-package/man/lgb.Dataset.set.categorical.Rd
  R-package/man/lgb.Dataset.set.reference.Rd
  R-package/man/lgb.convert.Rd
  R-package/man/lgb.convert_with_rules.Rd
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.dump.Rd
  R-package/man/lgb.get.eval.result.Rd
  R-package/man/lgb.importance.Rd
  R-package/man/lgb.interprete.Rd
  R-package/man/lgb.load.Rd
  R-package/man/lgb.model.dt.tree.Rd
  R-package/man/lgb.plot.importance.Rd
  R-package/man/lgb.plot.interpretation.Rd
  R-package/man/lgb.save.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lgb.unloader.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  R-package/man/setinfo.Rd
  R-package/man/slice.Rd
  docs/conf.py
Labels: maintenance

#3269 [R-package] refactor and improvements to lgb.convert() functions (fixes #2678, #2681)
  R-package/NAMESPACE
  R-package/R/lgb.convert.R
  R-package/R/lgb.convert_with_rules.R
  R-package/R/removed.R
  R-package/demo/00Index
  R-package/demo/categorical_features_prepare.R
  R-package/man/lgb.convert.Rd
  R-package/man/lgb.convert_with_rules.Rd
  R-package/pkgdown/_pkgdown.yml
  R-package/tests/testthat/test_lgb.convert.R
  R-package/tests/testthat/test_lgb.convert_with_rules.R
Labels: breaking

#3272 [Python] add start_iteration to python predict interface (#3058)
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Predictor.R
  R-package/man/predict.lgb.Booster.Rd
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_Predictor.R
  docs/Parameters.rst
  include/LightGBM/boosting.h
  include/LightGBM/c_api.h
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  src/application/application.cpp
  src/application/predictor.hpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/boosting/gbdt_prediction.cpp
  src/c_api.cpp
  src/io/config_auto.cpp
  swig/lightgbmlib.i
  tests/c_api_test/test_.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#3279 [CI] fix R's installation
  .ci/test_r_package.sh
Labels: blocking, maintenance

#3071 v3.0.0rc1
  .appveyor.yml
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/main.yml
  R-package/DESCRIPTION
  R-package/configure
  R-package/configure.ac
  R-package/recreate-configure.sh
  VERSION.txt
  build-cran-package.sh
Labels: maintenance

#3281 bump version for development
  .appveyor.yml
  VERSION.txt
  python-package/README.rst
Labels: maintenance

#3277 [R-package] suppress warning about empty 'compute' directory and fix Rtools installation
  .ci/test_r_package_windows.ps1
  .github/workflows/main.yml
  build_r.R
  docs/requirements_base.txt
  docs/requirements_rtd.txt
Labels: maintenance

#3297 [ci][docs] fix current master failures for docs test
  docs/Parallel-Learning-Guide.rst
  include/LightGBM/c_api.h
Labels: blocking, maintenance

#3296 [docs] Fix repetition of `tree_method` hyper-parameter in xgboost_hist
  docs/Experiments.rst
Labels: doc

#3295 [ci][python] fix sklearn FutureWarning about positional args
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_plotting.py
Labels: maintenance

#3294 [python] try to use bundled distutils to setuptools during setup
  python-package/setup.py
Labels: maintenance

#3288 simplify start_iteration param for predict in Python and some code cleanup for start_iteration
  R-package/R/lgb.Booster.R
  R-package/tests/testthat/test_Predictor.R
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  src/application/predictor.hpp
  src/boosting/gbdt_prediction.cpp
  tests/python_package_test/test_engine.py
Labels: maintenance

#3285 [R-package] Add docs on building and using precompiled binaries for the R package
  R-package/README.md
Labels: doc

#3298 [R-package] DESCRIPTION changes to address CRAN feedback
  R-package/.Rbuildignore
  R-package/DESCRIPTION
  R-package/cran-comments.md
  build-cran-package.sh
Labels: fix

#3304 fix vc project
  windows/LightGBM.vcxproj.filters
Labels: maintenance

#3305 fix zero bin in categorical split
  include/LightGBM/bin.h
  src/io/bin.cpp
  src/io/dense_bin.hpp
  src/io/sparse_bin.hpp
  src/treelearner/feature_histogram.hpp
Labels: fix

#3309 fix typo
  src/io/dense_bin.hpp
  src/io/sparse_bin.hpp
Labels: maintenance

#3307 [R] Fix 32-bit build
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/utils.R
  R-package/tests/testthat/test_dataset.R
Labels: fix

#3311 [ci] Test 32-bit builds for R package
  .ci/test_r_package_windows.ps1
  R-package/README.md
Labels: maintenance

#3315 [ci][docs] explicitly recuire fresh versions of RTD stuff
  docs/requirements_rtd.txt
Labels: maintenance

#3318 [R-package] remove blank lines and not-really-comments from .Rbuildignore
  R-package/.Rbuildignore
Labels: maintenance

#3324 [ci][docs] update Doxygen link in docs
  docs/README.rst
Labels: maintenance

#3323 [ci] bump Xcode version at Travis
  .ci/setup.sh
  .travis.yml
Labels: maintenance

#3322 Add Logo to readme
  README.md
Labels: maintenance

#3330 [docs][python][sklearn] remove excess fit arguments from docstrings
  python-package/lightgbm/sklearn.py
Labels: doc

#3335 [R-package] [ci] Reduce manual effort for version updates
  .ci/test_r_package.sh
  R-package/DESCRIPTION
  R-package/README.md
  R-package/configure
  R-package/configure.ac
  R-package/recreate-configure.sh
  build-cran-package.sh
  build_r.R
Labels: maintenance

#3340 [docs] uploaded hex logo for R-package in SVG format
  docs/logo/LightGBM-logo-hex.cdr
  docs/logo/LightGBM-logo-hex.svg
Labels: doc

#3341 [ci] fix R CMD check issue 'unable to verify current time'
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: maintenance

#3336 [R-package] Add R logo (fixes #3331, #3332)
  R-package/README.md
  R-package/man/figures/logo.svg
  R-package/pkgdown/favicon/apple-touch-icon-120x120.png
  R-package/pkgdown/favicon/apple-touch-icon-152x152.png
  R-package/pkgdown/favicon/apple-touch-icon-180x180.png
  R-package/pkgdown/favicon/apple-touch-icon-60x60.png
  R-package/pkgdown/favicon/apple-touch-icon-76x76.png
  R-package/pkgdown/favicon/apple-touch-icon.png
  R-package/pkgdown/favicon/favicon-16x16.png
  R-package/pkgdown/favicon/favicon-32x32.png
  R-package/pkgdown/favicon/favicon.ico
  docs/logo/LightGBM-logo-hex.cdr
  docs/logo/LightGBM-logo-hex.svg
  docs/logo/LightGBM_logo-hex.png
Labels: doc
