Repository microsoft/LightGBM, pull requests merged in 2021-12, with the labels that each got.

#4840 [python-package] fix mypy error about missing type hint in dask.py
  python-package/lightgbm/dask.py
Labels: maintenance

#4838 [python-package] fix mypy errors in plotting.py
  python-package/lightgbm/plotting.py
Labels: maintenance

#4833 [tests][dask] fix argument names in custom eval function in Dask test
  tests/python_package_test/test_dask.py
Labels: maintenance

#4822 [python][sklearn] respect parameters for predictions in `init()` and `set_params()` methods
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#4837 [python-package] fix mypy errors in sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4844 [python-package] [dask] fix mypy errors from dask.py docstrings
  python-package/lightgbm/dask.py
Labels: maintenance

#4839 [python-package] fix mypy errors in engine.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
Labels: maintenance

#4829 Add C API function that returns all parameter names with their aliases
  R-package/R/aliases.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_parameters.R
  helpers/parameter_generator.py
  include/LightGBM/c_api.h
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  src/io/config_auto.cpp
  tests/python_package_test/test_basic.py
Labels: feature

#4848 [R-package] fix `--no-build-vignettes` option for `build-cran-package.sh`
  build-cran-package.sh
Labels: fix

#4685 [R-package] enable saving Booster with saveRDS() and loading it with readRDS() (fixes #4296)
  R-package/NAMESPACE
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Predictor.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.drop_serialized.R
  R-package/R/lgb.make_serializable.R
  R-package/R/lgb.restore_handle.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.drop_serialized.Rd
  R-package/man/lgb.load.Rd
  R-package/man/lgb.make_serializable.Rd
  R-package/man/lgb.restore_handle.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lgb_shared_params.Rd
  R-package/man/lightgbm.Rd
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: breaking

#4849 [ci] migrate CI from macOS 10.14 to 10.15 and drop support of Mojave
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
  python-package/README.rst
Labels: breaking

#4850 [python-package] remove unused imports
  helpers/parameter_generator.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4845 [python][sklearn] unify values of `best_iteration` for sklearn and standard APIs
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_dask.py
Labels: breaking

#4855 [python] remove workaround for `UnboundLocalError` in early stopping callback for Python 2
  python-package/lightgbm/callback.py
Labels: maintenance

#4856 [R-package] remove support for '...' in Booster reset_parameter()
  R-package/R/lgb.Booster.R
Labels: breaking

#4857 [R-package] remove support for '...' in predict()
  R-package/R/lgb.Booster.R
  R-package/man/predict.lgb.Booster.Rd
Labels: breaking

#4851 [python-package] [dask] fix mypy error about worker_addresses
  python-package/lightgbm/dask.py
Labels: maintenance

#4852 [python-package][dask] handle failures parsing worker host names
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#4854 [R-package] remove Dataset setinfo()
  R-package/NAMESPACE
  R-package/R/lgb.Dataset.R
  R-package/man/getinfo.Rd
  R-package/man/setinfo.Rd
  R-package/tests/testthat/test_dataset.R
  docs/FAQ.rst
Labels: breaking

#4860 [R-package] remove support for '...' in lgb.cv()
  R-package/R/lgb.cv.R
  R-package/man/lgb.cv.Rd
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_learning_to_rank.R
Labels: breaking

#4864 [R-package] remove Dataset getinfo()
  R-package/NAMESPACE
  R-package/R/lgb.Dataset.R
  R-package/man/getinfo.Rd
  R-package/tests/testthat/test_dataset.R
Labels: breaking

#4867 [R-package] [docs] add Michael Mayer to DESCRIPTION
  R-package/DESCRIPTION
Labels: doc

#4866 [R-package] remove support for 'info' in Dataset
  R-package/R/lgb.Dataset.R
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.Dataset.create.valid.Rd
  R-package/man/lgb_shared_dataset_params.Rd
Labels: breaking

#4865 [R-package] remove support for '...' in `create_valid()`
  R-package/R/lgb.Dataset.R
  R-package/man/lgb.Dataset.create.valid.Rd
Labels: breaking

#4863 [R-package] remove support for '...' in lgb.train()
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/man/lgb.train.Rd
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
  R-package/tests/testthat/test_lgb.unloader.R
  R-package/tests/testthat/test_parameters.R
  R-package/vignettes/basic_walkthrough.Rmd
Labels: breaking

#4868 [python] reset storages in early stopping callback after finishing training
  python-package/lightgbm/callback.py
  tests/python_package_test/test_sklearn.py
Labels: fix

#4873 [R-package] remove support for '...' in `dim.lgb.Dataset()`
  R-package/R/lgb.Dataset.R
  R-package/man/dim.Rd
Labels: breaking

#4874 [R-package] remove support for '...' in `lgb.Dataset()`
  R-package/R/lgb.Dataset.R
  R-package/man/lgb.Dataset.Rd
  R-package/tests/testthat/test_basic.R
Labels: breaking

#4872 [R-package] remove support for '...' in `slice()`
  R-package/R/lgb.Dataset.R
  R-package/man/slice.Rd
  R-package/tests/testthat/test_dataset.R
Labels: breaking

#4846 [python][sklearn] Remove `early_stopping_rounds` argument of `fit()` method
  examples/python-guide/sklearn_example.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#4871 [R-package] remove unused callback cb.reset.parameter
  R-package/R/callback.R
Labels: maintenance

#4877 [python] remove `verbose` argument of `model_from_string()` method of Booster class
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: breaking

#4878 [python] remove `verbose_eval` argument of `train()` and `cv()` functions
  examples/python-guide/notebooks/interactive_plot_example.ipynb
  examples/python-guide/plot_example.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_plotting.py
Labels: breaking

#4889 Add support for Visual Studio 2022
  .github/workflows/r_package.yml
  R-package/src/install.libs.R
  docs/Installation-Guide.rst
  python-package/setup.py
Labels: feature

#4892 [docs] Update link to FLAML code example
  README.md
Labels: doc

#4879 [R-package] reduce verbosity in some unit tests
  R-package/README.md
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.importance.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
  R-package/tests/testthat/test_lgb.unloader.R
  R-package/tests/testthat/test_weighted_loss.R
Labels: awaiting review, maintenance

#4891 [python] Drop Python 3.6 support
  .appveyor.yml
  .ci/test.sh
  .github/workflows/python_package.yml
  .vsts-ci.yml
  python-package/setup.py
Labels: breaking

#4884 [python][sklearn] do not replace empty dict with `None` for `evals_result_`
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#4885 [python] reset storage in record evaluation callback each time before starting training
  python-package/lightgbm/callback.py
  tests/python_package_test/test_sklearn.py
Labels: fix

#4895 [tests][python-package] change boston dataset to synthetic dataset in tests that don't check score
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/utils.py
Labels: maintenance

#4896 [R-package] reduce verbosity in tests using lgb.train()
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_custom_objective.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#4902 [R-package] remove unnecessary comments and fix typos in comments
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/utils.R
Labels: maintenance

#4901 [R-package] fix CVBooster reset_parameter() method (fixes #4900)
  R-package/R/lgb.cv.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#4882 [python] remove `evals_result` argument of `train()` function
  examples/python-guide/notebooks/interactive_plot_example.ipynb
  examples/python-guide/plot_example.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_plotting.py
Labels: breaking

#4890 clear memory allocated for sampled data when constructing Dataset from text file
  src/io/dataset_loader.cpp
Labels: awaiting review, efficiency

#4899 [R-package] update parameter 'verbosity' based on keyword arg 'verbose'
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#4908 [python] remove `early_stopping_rounds` argument of `train()` and `cv()` functions
  docs/Parameters-Tuning.rst
  docs/Python-Intro.rst
  examples/python-guide/simple_example.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: breaking

#4918 [R-package] added argument eval_train_metric to lgb.cv() (fixes #4911)
  R-package/R/lgb.cv.R
  R-package/man/lgb.cv.Rd
  R-package/tests/testthat/test_basic.R
Labels: feature

#4916 [R-package][tests] remove uses of `testthat::expect_is()`
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.convert_with_rules.R
Labels: maintenance

#4914 [R-package] fix handling of duplicate parameters (fixes #4521)
  R-package/R/utils.R
  R-package/tests/testthat/test_utils.R
Labels: fix

#4915 [R-package] [tests] remove uses of testthat::context()
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_custom_objective.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_lgb.convert_with_rules.R
  R-package/tests/testthat/test_lgb.importance.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.importance.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
  R-package/tests/testthat/test_lgb.unloader.R
  R-package/tests/testthat/test_metrics.R
  R-package/tests/testthat/test_parameters.R
  R-package/tests/testthat/test_utils.R
  R-package/tests/testthat/test_weighted_loss.R
Labels: maintenance

#4815 [python] raise an informative error instead of segfaulting when custom objective produces incorrect output
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: fix
