Repository microsoft/LightGBM, pull requests merged in 2021-06, with the labels that each got.

#4325 [fix] skip empty bins when calculating cnt_in_bin in BinMapper::FindBin (fix #4301)
  src/io/bin.cpp
Labels: fix

#4329 Add linear leaf models to json output (fixes #4186)
  include/LightGBM/tree.h
  src/io/tree.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#4337 [R-package] remove unused code in lgb.params2str()
  R-package/R/utils.R
Labels: maintenance

#4338 [R-package] remove uses of ... in Predictor constructor
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Predictor.R
  R-package/R/lgb.train.R
Labels: maintenance

#4340 [docs] make building of C++ tests section collapsable
  docs/_static/js/script.js
Labels: doc

#4342 [R-package] remove unused argument in early stopping callback
  R-package/R/callback.R
Labels: maintenance

#4344 [R-package] remove lgb.last_error() and LGBM_GetLastError_R()
  R-package/R/utils.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_utils.R
  build_r.R
Labels: maintenance

#4343 [R-package] factor out lgb.check.r6.class()
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/utils.R
  R-package/tests/testthat/test_utils.R
Labels: maintenance

#4341 [R-package] resolve test warning about is.na() and handles
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#4348 [python-package] updated test_consistency.py to use f-strings
  tests/python_package_test/test_consistency.py
Labels: maintenance

#4356 [python-package] use f-strings for concatenation in examples/python-guide/logistic_regression.py
  examples/python-guide/logistic_regression.py
Labels: maintenance

#4354 [R-package] remove unnecessary library() calls in tests
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#4359 Updated tests/python_package_test/test_plotting.py to use f-strings
  tests/python_package_test/test_plotting.py
Labels: maintenance

#4358 [python] improving the syntax of the fstring in the file : tests/python_package_test/test_dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#4346 [docs] document how to pass multi-value params from Python and R fixes #4345)
  docs/Parameters.rst
Labels: doc

#4361 [R-package] remove defaults in internal functions
  R-package/R/callback.R
  R-package/R/lgb.cv.R
Labels: maintenance

#4366 [docs] add anchor for nightly builds in docs
  docs/Installation-Guide.rst
Labels: doc

#4373 [tests][python] fix f-string in test_dask.py
  tests/python_package_test/test_dask.py
Labels: fix

#4364 [docs][python] enhance `keep_training_booster` param description
  python-package/lightgbm/engine.py
Labels: doc

#4360 [R-package] avoid unnecessary computation of std deviations in lgb.cv()
  R-package/R/lgb.cv.R
  R-package/man/lgb.cv.Rd
  R-package/tests/testthat/test_basic.R
Labels: efficiency

#4353 [R-package] move more finalizer logic into C++ side to address memory leaks
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/src/lightgbm_R.cpp
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: fix

#4365 [docs] document sanitizers
  docs/Development-Guide.rst
  docs/Installation-Guide.rst
Labels: doc

#4376 [python] add type hints to python-package/setup.py
  python-package/setup.py
Labels: maintenance

#4382 [python] add type hints to check_dynamic_dependencies.py
  helpers/check_dynamic_dependencies.py
Labels: maintenance

#4380 [dask] Dask Vector types for group, init_score, sample_weights (fixes #4375)
  python-package/lightgbm/dask.py
Labels: doc

#4352 [ci] [R-package] add unit tests on monotone constraints
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#4377 [tests] replace pytest.parametrize
  tests/python_package_test/test_engine.py
Labels: maintenance

#4381 [R-package] consolidate duplicate lists of Dataset info keys
  R-package/R/lgb.Dataset.R
Labels: maintenance

#4385 [ci] Increase timeout value for QEMU builds
  .vsts-ci.yml
Labels: maintenance

#4383 [R-package] remove unnecessary comments
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.model.dt.tree.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
Labels: maintenance

#4324 [fix] fix Sample when sampling only one element (fix #4134)
  include/LightGBM/utils/random.h
Labels: fix

#4389 fix: typo in python class _InnerPredictor docstring
  python-package/lightgbm/basic.py
Labels: doc

#4336 Log warning instead of fatal when parsing float get under/overflow.
  include/LightGBM/utils/common.h
  tests/cpp_tests/test_common.cpp
Labels: fix

#4280 Fix undefined behavior in ArrayArgs::Partition() when interval size is 1 (fixes #4272)
  include/LightGBM/utils/array_args.h
  tests/cpp_tests/test_array_args.cpp
Labels: fix

#4395 [docs][R-package] add authors in R-package description
  R-package/DESCRIPTION
Labels: doc

#4396 [python] Improving the syntax of `print`s in `simple_example.py` and `sklearn_example.py`
  examples/python-guide/simple_example.py
  examples/python-guide/sklearn_example.py
Labels: maintenance

#4386 [python] Improving the syntax of the fstrings in the file: .\examples\python-guide\advanced_example.py
  examples/python-guide/advanced_example.py
Labels: maintenance

#4401 [docs] update link to LightGBM example in MMLSpark repo
  docs/Parallel-Learning-Guide.rst
Labels: doc

#4332 sync for init score of binary objective function
  src/objective/binary_objective.hpp
Labels: fix

#4387 fix param aliases
  R-package/R/aliases.R
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  src/io/config_auto.cpp
  tests/python_package_test/test_engine.py
Labels: fix

#4404 [ci] [R-package] increase timeout on valgrind job
  .github/workflows/r_valgrind.yml
Labels: maintenance

#4330 [tests][ci] run cpp tests with sanitizers on Linux and macOS
  .ci/test.sh
  .ci/test_windows.ps1
  .vsts-ci.yml
  CMakeLists.txt
  cmake/Sanitizer.cmake
Labels: maintenance

#4399 [dask] pass additional predict() parameters through when input is a Dask Array
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: fix

#4408 [docs] Add shapash to the list of related projects
  README.md
Labels: doc

#4391 [R-package] fix protection stack imbalance and unprotected objects (fixes #4390)
  R-package/src/lightgbm_R.cpp
Labels: fix

#4412 [tests][dask] add missing compute() in Dask test
  tests/python_package_test/test_dask.py
Labels: maintenance

#4410 [python] replace numpy.zeros with numpy.empty for the speedup
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  tests/c_api_test/test_.py
  tests/python_package_test/test_engine.py
Labels: efficiency

#4367 [python] Add type hints to python-package/lightgbm/plotting.py
  python-package/lightgbm/plotting.py
Labels: maintenance

#4101 [dask] add support for eval sets and custom eval functions
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_dask.py
Labels: feature

#4327 [CUDA] fix CUDA memory error by reducing block number (#4315)
  src/treelearner/cuda_kernel_launcher.cu
Labels: fix

#4413 [dask] fix typehint on _pad_eval_names()
  python-package/lightgbm/dask.py
Labels: maintenance

#4418 [tests] fix compiler warning about types conversion in cpp tests
  tests/cpp_tests/test_array_args.cpp
Labels: maintenance

#4419 [SWIG] fix compiler warning about unused variable in SWIG
  swig/StringArray.i
  swig/StringArray_API_extensions.i
Labels: maintenance
