Repository microsoft/LightGBM, pull requests merged in 2021-07, with the labels that each got.

#4420 [python-package] Add type hints to init for LGBMModel
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4422 [python] migrate to pathlib in create_nuget.py
  .nuget/create_nuget.py
Labels: maintenance

#4421 [python-package] f-string format updated in plot_example.py
  examples/python-guide/plot_example.py
Labels: maintenance

#4089 [python-package] Create Dataset from multiple data files
  .ci/test.sh
  .ci/test_windows.ps1
  docs/Python-API.rst
  docs/Python-Intro.rst
  examples/python-guide/README.md
  examples/python-guide/dataset_from_multi_hdf5.py
  include/LightGBM/c_api.h
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  src/c_api.cpp
  tests/python_package_test/test_basic.py
Labels: feature

#4427 [python] migrate to pathlib in conf.py
  docs/conf.py
Labels: maintenance

#4429 [ci] add h5 files into `.gitignore`
  .gitignore
Labels: maintenance

#4431 [docs] add lleaves to README
  README.md
Labels: doc

#4432 [ci] ensure interactive_plot_example notebook is run in interactive mode at CI
  .ci/test.sh
  .ci/test_windows.ps1
Labels: maintenance

#4430 [python] migrate to f-strings in interactive_plot_example.ipynb
  examples/python-guide/notebooks/interactive_plot_example.ipynb
Labels: maintenance

#4435 [python] migrate to pathlib in python tests
  tests/c_api_test/test_.py
  tests/cpp_tests/test.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_consistency.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/test_utilities.py
Labels: maintenance

#4254 [tests][cli] distributed training
  .gitignore
  tests/distributed/_test_distributed.py
  tests/distributed/conftest.py
Labels: maintenance

#4434 [python] migrate to pathlib in helper scripts
  helpers/check_dynamic_dependencies.py
  helpers/parameter_generator.py
Labels: maintenance

#4428 [python] migrate to pathlib in python examples
  examples/python-guide/advanced_example.py
  examples/python-guide/dask/ranking.py
  examples/python-guide/dataset_from_multi_hdf5.py
  examples/python-guide/notebooks/interactive_plot_example.ipynb
  examples/python-guide/plot_example.py
  examples/python-guide/simple_example.py
  examples/python-guide/sklearn_example.py
Labels: maintenance

#4436 [python-package] convert string concatenation to f-strings in test_engine.py (fixes #4136)
  tests/python_package_test/test_engine.py
Labels: maintenance

#4439 [tests] fix deprecation numpy warning
  tests/python_package_test/test_basic.py
Labels: maintenance

#4437 [tests][python] refactor file loading routine in C API test
  tests/c_api_test/test_.py
Labels: maintenance

#4441 [docs][python] add versionadded to Sequence class in Python wrapper
  python-package/lightgbm/basic.py
Labels: doc

#4442 [python] minor refactoring of Python code
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#4443 [python] migrate to pathlib in distributed tests
  tests/distributed/_test_distributed.py
  tests/distributed/conftest.py
Labels: maintenance

#4446 [python-package] use toarray() instead of todense() in tests and examples
  examples/python-guide/dask/ranking.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#4450 [fix] fix Reservoir Sampling in Sample of random.h (fix #4371 and #4134)
  include/LightGBM/utils/random.h
Labels: fix

#4378 [dask] Make output of feature contribution predictions for sparse matrices match those from sklearn estimators (fixes #3881)
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: breaking

#4440 [python] allow to pass some params as pathlib.Path objects
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/libpath.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_consistency.py
  tests/python_package_test/test_engine.py
Labels: feature

#4452 [tests] clarify RuntimeError in distributed tests
  tests/distributed/_test_distributed.py
Labels: maintenance

#4351 [dask] determine output shape of array in predict (fixes #4285)
  .ci/test.sh
  python-package/lightgbm/dask.py
Labels: fix

#4453 [ci] bump CUDA version from 11.2.2 to 11.4.0 at CI
  .github/workflows/cuda.yml
Labels: maintenance

#4411 [docs] clarify description of prediction early stopping
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#4457 [tests][python] added tests for early stop in prediction in ranking task
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#4454 [ci] add support for 8.0 and 8.6 CUDA archs
  CMakeLists.txt
Labels: maintenance

#4444 [python] migrate to pathlib in setup.py and use `absolute()` on paths first
  .nuget/create_nuget.py
  docs/conf.py
  helpers/parameter_generator.py
  python-package/lightgbm/__init__.py
  python-package/lightgbm/libpath.py
  python-package/setup.py
  tests/c_api_test/test_.py
  tests/cpp_tests/test.py
Labels: maintenance

#4449 [ci] Add CI job running rchk on the R package (fixes #4400)
  .ci/test.sh
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
Labels: maintenance

#4463 [ci] remove preinstalled possibly conflicting software from PATH in CI jobs
  .ci/test_r_package_windows.ps1
Labels: maintenance

#4462 [python] parallelize MinGW make similarly to Unix make command
  python-package/setup.py
Labels: maintenance

#4468 Fix undefined behavior with NaN input in CategoricalDecision()
  include/LightGBM/tree.h
Labels: fix

#4478 [refactor] Use CreateSampleIndices in c_api.cc
  src/c_api.cpp
Labels: maintenance

#4474 [python] Add type hints to helpers/parameter_generator.py
  helpers/parameter_generator.py
Labels: maintenance

#4486 remove examples/.gitignore
  .gitignore
  examples/.gitignore
Labels: maintenance

#4485 [docs] document CLI behavior when label_column is omitted
  docs/Parameters.rst
  examples/binary_classification/train.conf
  examples/lambdarank/train.conf
  examples/multiclass_classification/train.conf
  examples/parallel_learning/train.conf
  examples/regression/train.conf
  examples/xendcg/train.conf
  include/LightGBM/config.h
Labels: doc

#4488 [docs][ci] bump versions of R-package dependencies at RTD
  docs/conf.py
Labels: maintenance

#4472 [python] support Dataset.get_data for Sequence input.
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: feature

#4494 [R-package] limit exported symbols in DLL
  R-package/src/lightgbm-win.def
Labels: maintenance

#4495 [python][tests] refactor tests with Sequence input
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: maintenance
