Repository microsoft/LightGBM, pull requests merged in 2021-10, with the labels that each got.

#4648 [ci] ignore certificates for kitware apt channel in CUDA jobs (fixes #4646)
  .ci/setup.sh
Labels: blocking, maintenance

#4643 remove unused BinMapper::SizeForSpecificBin()
  include/LightGBM/bin.h
  src/io/bin.cpp
Labels: maintenance

#4644 remove duplicated debug printing in `CMakeLists.txt` for MPI
  CMakeLists.txt
Labels: maintenance

#4637 add param aliases from scikit-learn
  R-package/R/aliases.R
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  src/io/config_auto.cpp
Labels: feature

#4608 allow inclusion in C programs
  include/LightGBM/c_api.h
Labels: feature

#4636 [python][sklearn] add `__sklearn_is_fitted__()` method to be better compatible with scikit-learn API
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4650 remove unused DCGCalculator::CalDCGAtK()
  include/LightGBM/metric.h
  src/metric/dcg_calculator.cpp
Labels: maintenance

#4749 [python] Make dummy classes constructible with any arguments
  python-package/lightgbm/compat.py
Labels: maintenance

#4732 [ci] indicate support of Monterey
  .ci/test.sh
Labels: maintenance

#4752 [R-package] remove temporary files created in configure.win
  R-package/configure.win
Labels: maintenance

#4756 [docs] improve docs about `nthreads` parameter
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/sklearn.py
Labels: doc

#4754 [R-package] allow use of custom R executable when building CRAN package
  .ci/test_r_package_valgrind.sh
  .github/workflows/r_package.yml
  R-package/README.md
  build-cran-package.sh
Labels: maintenance
