Repository microsoft/LightGBM, pull requests merged in 2021-11, with the labels that each got.

#4750 [docs][python] add `datatable` to the mocked modules during docs building process and sort them alphabetically
  docs/conf.py
Labels: maintenance

#4763 [ci] upgrade actions/checkout to v2.4.0
  .github/workflows/linkchecker.yml
  .github/workflows/optional_checks.yml
  .github/workflows/python_package.yml
  .github/workflows/r_configure.yml
  .github/workflows/r_package.yml
  .github/workflows/r_solaris.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/static_analysis.yml
  .github/workflows/triggering_comments.yml
Labels: maintenance

#4765 [ci] use wch1/r-debug image in Solaris tests
  .ci/test_r_package_solaris.sh
  .github/workflows/r_solaris.yml
  .github/workflows/r_valgrind.yml
Labels: maintenance

#4770 [ci] Temporary pin dask version at CI
  .ci/test.sh
Labels: blocking, maintenance

#4766 [python] improve warning message about aliases in `cv()` function
  python-package/lightgbm/engine.py
Labels: maintenance

#4767 [ci] only use conda-forge when installing R packages in docs builds
  docs/conf.py
Labels: doc

#4753 [python][sklearn] add `n_estimators_` and `n_iter_` post-fit attributes
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#3946 [R-package] [docs] add intro vignette
  .ci/lint_r_code.R
  .ci/test_r_package.sh
  .ci/test_r_package_solaris.sh
  .ci/test_r_package_valgrind.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  R-package/DESCRIPTION
  R-package/README.md
  R-package/pkgdown/_pkgdown.yml
  R-package/vignettes/basic_walkthrough.Rmd
  build-cran-package.sh
  build_r.R
  docs/conf.py
Labels: doc

#4773 [ci] increase timeout for valgrind job to 240 minutes
  .github/workflows/r_valgrind.yml
Labels: maintenance

#4776 [ci] Revert temp workaround for `freetype` version
  .ci/test_windows.ps1
Labels: maintenance

#4738 [docs] [R-package] update cran-comments for v3.3.1 release
  R-package/cran-comments.md
Labels: doc

#4778 [ci][tests][python] remove assertion for `filename` that is no longer true with new version of graphviz
  tests/python_package_test/test_plotting.py
Labels: blocking, maintenance

#4774 [docs] add specific estimator names to sklearn fit() docs
  python-package/lightgbm/sklearn.py
Labels: doc

#4716 [docs] [dask] Add return information to Dask fit() docs (fixes #4402)
  python-package/lightgbm/dask.py
Labels: doc

#4768 Suppress categorical warning (fixes #3379)
  python-package/lightgbm/basic.py
  tests/python_package_test/test_utilities.py
Labels: maintenance

#4725 Always respect forced splits, even when feature_fraction < 1.0 (fixes #4601)
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  tests/python_package_test/test_engine.py
Labels: fix

#4525 [R-package] parallelize compilation in CMake-based builds
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  R-package/README.md
  R-package/src/install.libs.R
  build_r.R
Labels: awaiting review, efficiency

#4489 cmake: use object library to avoid duplicate compilation.
  CMakeLists.txt
Labels: maintenance

#4758 [python][sklearn] respect objective aliases
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#4580 [python-package] early stopping min_delta (fixes #2526)
  python-package/lightgbm/callback.py
  tests/python_package_test/test_engine.py
Labels: feature

#4746 Add 'nrounds' as an alias for 'num_iterations' (fixes #4743)
  R-package/R/aliases.R
  R-package/tests/testthat/test_basic.R
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  src/io/config_auto.cpp
Labels: feature

#4787 [python] Faster categorical column names selection
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
Labels: efficiency

#4795 [docs] fix broken SynapseML link
  docs/Parallel-Learning-Guide.rst
Labels: doc

#4686 [R-package] Add `print()` and `summary()` methods for Booster
  R-package/NAMESPACE
  R-package/R/lgb.Booster.R
  R-package/man/print.lgb.Booster.Rd
  R-package/man/summary.lgb.Booster.Rd
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_lgb.Booster.R
Labels: feature

#4798 [ci] use pure `endif()` and `endfunction()` without expression inside in `CMakeLists.txt`
  CMakeLists.txt
  cmake/modules/FindLibR.cmake
Labels: maintenance

#4796 [ci] fix CMakeLint `linelength` errors
  CMakeLists.txt
  cmake/IntegratedOpenCL.cmake
  cmake/Sanitizer.cmake
  cmake/modules/FindLibR.cmake
Labels: maintenance

#4799 [ci] simplify processing of `CMAKE_CUDA_FLAGS` variable in `CMakeLists.txt`
  CMakeLists.txt
Labels: maintenance

#4794 [ci] fix CMakeLint errors related to function naming case
  .ci/test.sh
  CMakeLists.txt
Labels: maintenance

#4801 [ci] ignore CMakeLint errors related to package names
  .ci/test.sh
Labels: maintenance

#4697 [c_api] Improve ANSI compatibility by avoiding <stdbool.h>
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
Labels: maintenance

#4547 [python] add type hints for custom objective and metric functions in scikit-learn interface
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4782 Add customized parser support
  README.md
  docs/Parameters.rst
  include/LightGBM/boosting.h
  include/LightGBM/config.h
  include/LightGBM/dataset.h
  include/LightGBM/utils/common.h
  include/LightGBM/utils/text_reader.h
  src/application/predictor.hpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/boosting/gbdt_model_text.cpp
  src/io/config_auto.cpp
  src/io/dataset_loader.cpp
  src/io/parser.cpp
  tests/python_package_test/test_basic.py
Labels: feature

#4806 [ci] fix getting status of optional workflows in PRs with a lot of comments
  .ci/get_workflow_status.py
Labels: maintenance

#4775 [R-package] [docs] add intro vignette (#3946)
  .ci/lint_r_code.R
  .ci/test_r_package.sh
  .ci/test_r_package_solaris.sh
  .ci/test_r_package_valgrind.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  R-package/DESCRIPTION
  R-package/README.md
  R-package/pkgdown/_pkgdown.yml
  R-package/vignettes/basic_walkthrough.Rmd
  build-cran-package.sh
  build_r.R
  docs/conf.py
Labels: doc

#4811 [ci] Fix CI job for R artifact
  .vsts-ci.yml
Labels: blocking, maintenance

#4812 [R-package] Move R6 to Imports
  R-package/DESCRIPTION
Labels: maintenance

#4800 [python] Remove `silent` argument
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_plotting.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#4824 [python] add type hints to `_compare_params_for_warning()` and make it reusable
  python-package/lightgbm/basic.py
Labels: maintenance

#4816 [python][docs] fix type hints for custom functions and remove vague `array-like` wording
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: fix

#4819 [python] Remove `print_evaluation()` function
  python-package/lightgbm/__init__.py
  python-package/lightgbm/callback.py
Labels: breaking

#4818 [python] remove "auto" value of `ylabel` argument of `plot_metric()` function
  python-package/lightgbm/plotting.py
Labels: breaking

#4830 [docs][python] simplify mocking in docs
  docs/conf.py
Labels: maintenance

#4831 [python] remove `learning_rates` argument of `train()` function
  examples/python-guide/advanced_example.py
  python-package/lightgbm/engine.py
Labels: breaking

#4832 [python][sklearn] remove `verbose` argument from `fit()` method
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_plotting.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#4836 [python-package] fix mypy errors in compat.py and setup.py
  python-package/lightgbm/compat.py
  python-package/setup.py
Labels: maintenance
