Repository microsoft/LightGBM, pull requests merged in 2021-01, with the labels that each got.

#3705 [R-package] fix incorrect passing builds in valgrind checks (fixes #3704)
  .ci/test_r_package_valgrind.sh
Labels: maintenance

#3678 Added static cast from double to float
  include/LightGBM/dataset.h
Labels: fix

#3686 [R-package] remove unused R_AS_INT64
  R-package/src/R_object_helper.h
Labels: awaiting review, maintenance

#3662 [R-package] allow access to params in Booster
  R-package/R/lgb.Booster.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/tests/testthat/test_lgb.Booster.R
  src/c_api.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#3664 [R-package] remove broken default for `file` in readRDS / saveRDS functions
  .gitignore
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
Labels: fix

#3647 [R-package] add support for non-ASCII feature names (fixes #2983)
  R-package/tests/testthat/test_basic.R
Labels: feature

#3711 [python][ci] remove line in MANIFEST for nonexistent file
  python-package/MANIFEST.in
Labels: maintenance

#3710 [docs] Remove Gitter and Slack (fixes #3689)
  README.md
Labels: doc

#3715 [python][tests] small Python tests cleanup
  .gitignore
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#3723 [ci] remove flaky MinGW job for R
  .github/workflows/r_package.yml
Labels: maintenance

#3725 [ci] remove maxParallel limits on Azure DevOps
  .vsts-ci.yml
Labels: maintenance

#3724 [docs] [R-package] improve R-package docs on testing
  R-package/README.md
Labels: doc

#3728 [docs][R-package] change obsolete wordings in R README
  R-package/README.md
Labels: doc

#3703 [R-package] Add explicit return statement to R functions.
  R-package/R/aliases.R
  R-package/R/callback.R
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.plot.importance.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/metrics.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/R/utils.R
  build_r.R
Labels: maintenance

#3683 fix test_monotone_constraints often fails on MPI builds
  src/treelearner/feature_histogram.hpp
Labels: fix

#3729 Fix compiler warnings caused by implicit type conversion (fixes #3677)
  include/LightGBM/dataset.h
  src/io/dataset_loader.cpp
  src/io/tree.cpp
  src/treelearner/linear_tree_learner.cpp
  src/treelearner/linear_tree_learner.h
Labels: fix

#3721 Fix bug in ExtractFeaturesFromMemory when predidct_fun_ is used
  src/io/dataset_loader.cpp
Labels: fix

#3730 support more filesystem as the storage for model file
  src/boosting/gbdt_model_text.cpp
Labels: feature

#3726 [ci] Move check-docs and lint jobs off Travis
  .ci/setup.sh
  .ci/test.sh
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .travis.yml
  README.md
Labels: maintenance

#3738 [ci][docs] replace file extensions in docs during Sphinx build
  .ci/test.sh
  docs/_static/js/script.js
  docs/conf.py
Labels: maintenance

#3737 [ci] run Azure linux tasks on self-hosted runner pool
  .vsts-ci.yml
Labels: awaiting review, maintenance

#3742 move CheckParamConflict() after LogLevel processing
  src/io/config.cpp
Labels: fix

#3745 [ci] move Python Mac jobs from Travis to GitHub Actions
  .github/workflows/python_package.yml
  .travis.yml
  README.md
Labels: maintenance

#3694 Fix bug in corner case with histogram bin mismatch
  src/io/dataset.cpp
  src/io/train_share_states.cpp
Labels: fix

#3709 Initialize any_nan_ property of LinearTreeLearner
  src/treelearner/linear_tree_learner.cpp
Labels: fix

#3748 Ensure CUDA vector length is consistent with AlignedSize
  include/LightGBM/cuda/vector_cudahost.h
Labels: fix

#3544 [docs][python] add conda-forge install instructions
  docs/Python-Intro.rst
  python-package/README.rst
Labels: doc

#3672 [ci] remove Travis (fixes #3519)
  .ci/setup.sh
  .ci/test.sh
  .travis.yml
  .vsts-ci.yml
  R-package/.Rbuildignore
  README.md
Labels: maintenance

#3749 [ci] indicate support of Big Sur and drop High Sierra
  .ci/test.sh
Labels: breaking

#3740 [ci] improve experience with optional GitHub workflows
  .ci/append_comment.sh
  .ci/get_workflow_status.py
  .ci/rerun_workflow.sh
  .ci/set_commit_status.sh
  .ci/trigger_dispatch_run.sh
  .github/workflows/optional_checks.yml
  .github/workflows/r_artifacts.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/triggering_comments.yml
  R-package/README.md
Labels: maintenance

#3750 Update CUDA treelearner according to changes introduced for linear trees
  .github/workflows/cuda.yml
  src/treelearner/cuda_tree_learner.cpp
  src/treelearner/cuda_tree_learner.h
Labels: fix

#3762 [ci] Slightly optimize optional workflows checks
  .ci/get_workflow_status.py
  .github/workflows/optional_checks.yml
Labels: maintenance

#3764 [python][tests] Migrates test_basic.py to use pytest
  tests/python_package_test/test_basic.py
Labels: maintenance

#3766 [dask] [python-package] Search for available ports when setting up network (fixes #3753)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: fix

#3767 [tests][python] completely remove tempfile from test_basic
  tests/python_package_test/test_basic.py
Labels: maintenance

#3773 [ci][docs] update linkchecker
  .ci/test.sh
Labels: maintenance

#3699 [R-package] enable use of trees with linear models at leaves (fixes #3319)
  R-package/configure
  R-package/configure.ac
  R-package/configure.win
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  build-cran-package.sh
  build_r.R
  docs/Parameters.rst
  include/LightGBM/config.h
  src/treelearner/linear_tree_learner.cpp
  src/treelearner/tree_learner.cpp
Labels: feature

#3783 [R-package][tests] remove unused lines in tests for the speedup
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#3784 [ci] revert forcing CMake to try compile static library for R-package
  CMakeLists.txt
Labels: maintenance

#3777 Minor C API cleanup in predictor & SingleRowPredictor
  src/application/predictor.hpp
  src/c_api.cpp
Labels: maintenance

#3772 [docs] expand documentation on 'group' for ranking task
  R-package/R/lgb.Dataset.R
  R-package/man/getinfo.Rd
  R-package/man/setinfo.Rd
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
Labels: doc

#3785 [ci][docs] set limit for max requests per second to one host in linkchecker
  docs/.linkcheckerrc
Labels: maintenance

#3786 [dask] reduce test times
  tests/python_package_test/test_dask.py
Labels: maintenance

#3779 [R-package] Add GPU install options (fixes #3765)
  R-package/README.md
  R-package/src/install.libs.R
  build_r.R
Labels: feature

#3787 [docs] fix current RTD failures
  docs/Parameters.rst
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#3727 [ci][SWIG] update SWIG version and use separate CI job to produce SWIG artifacts
  .ci/setup.sh
  .ci/test.sh
  .ci/test_windows.ps1
  .vsts-ci.yml
Labels: breaking

#3788 [dask] fix Dask import order
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#3789 [dask] allow parameter aliases for local_listen_port, num_threads, tree_learner (fixes #3671)
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: fix

#3799 [docs] fix min CMake version in docs for macOS
  docs/Installation-Guide.rst
Labels: doc

#3801 [docs] remove unused argument in docs config
  docs/conf.py
Labels: doc

#3803 [docs] bump min sphinx_rtd_theme version
  docs/requirements_base.txt
Labels: doc

#3771 Fix thread-safety in C API's PredictSingleRow
  src/c_api.cpp
Labels: fix

#3802 remove unused code
  include/LightGBM/config.h
Labels: maintenance

#3806 [python][tests] remove unused import
  tests/python_package_test/test_consistency.py
Labels: maintenance

#3800 [python][tests] migrate test_engine.py to pytest
  tests/python_package_test/test_engine.py
Labels: maintenance

#3708 [python-package] [dask] Add DaskLGBMRanker
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#3774 [dask] Support pred_contrib in Dask predict() methods (fixes #3713)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#3810 [python][tests] use default tolerance for dual GPU+CPU test
  tests/python_package_test/test_dual.py
Labels: maintenance

#3755 [dask] [python-package] use keyword args for internal function calls
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#3819 [dask] Address flaky test_ranker tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#3811 [python-package] migrate test_plotting.py to pytest
  tests/python_package_test/test_plotting.py
Labels: maintenance

#3821 [python][tests] transfer test_save_and_load_linear to test_engine
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#3752 Don't copy more than has been allocated to device_features.
  src/treelearner/cuda_tree_learner.cpp
Labels: awaiting review, fix

#3824 [ci] make sure we use documented Xcode version for producing artifacts
  .ci/setup.sh
Labels: maintenance

#3827 [dask][tests] move make_ranking into utils
  tests/python_package_test/test_dask.py
  tests/python_package_test/utils.py
Labels: maintenance

#3826 [ci] improve optional checks
  .github/workflows/triggering_comments.yml
Labels: maintenance

#3828 [dask][tests] reduce code duplication in Dask tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#3820 [python] Allow to register custom logger in Python-package
  docs/Python-API.rst
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_utilities.py
Labels: feature

#3843 [dask] Drop aliases of core network parameters
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
Labels: fix

#3822 [dask][docs] initial setup for Dask docs
  README.md
  docs/FAQ.rst
  docs/Parallel-Learning-Guide.rst
  docs/Python-API.rst
  docs/conf.py
  python-package/README.rst
  python-package/lightgbm/__init__.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  python-package/setup.py
Labels: doc

#3848 [dask] warn if attempting to use tree_learner other than data parallel
  python-package/lightgbm/dask.py
Labels: doc

#3852 [dask][tests] skip Dask tests when Dask is not installed and improve imports in Dask tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#3849 [dask] factor dask-ml out of tests (fixes #3796)
  .ci/test.sh
  tests/python_package_test/test_dask.py
Labels: maintenance

#3720 Change Dataset::CopySubrow from group-wise to column-wise
  include/LightGBM/feature_group.h
  src/io/dataset.cpp
Labels: efficiency

#3854 [R-package][docs] improve grouping in R API reference
  R-package/pkgdown/_pkgdown.yml
Labels: doc

#3842 [dask] merge local_predict tests into other tests (fixes #3833)
  tests/python_package_test/test_dask.py
Labels: maintenance

#3853 [dask] [python] Store co-local data parts as dicts instead of lists
  python-package/lightgbm/dask.py
Labels: maintenance

#3844 [python-package] migrate test_sklearn.py to pytest
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#3757 [ci] run artifacts packaging job on Ubuntu
  .vsts-ci.yml
Labels: maintenance

#3840 Create a new TcpSocket when connection failed
  src/network/linkers_socket.cpp
Labels: fix

#3813 [python-package] respect parameter aliases for network params
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  tests/python_package_test/test_basic.py
Labels: fix

#3859 [dask] rename _LGBMModel to _DaskLGBMModel
  python-package/lightgbm/dask.py
Labels: maintenance

#3855 [dask] fix Dask docstrings and mimic sklearn wrapper importing way
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
Labels: fix

#3860 [python][tests] minor Python tests cleanup
  tests/python_package_test/test_dual.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#3862 [python] use better names for imported classes from extra libraries
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#3864 [python] simplify param aliases handling
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#3865 [dask] add tests on warnings, fix incorrect variable in log
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#3868 [ci] add mypy to linting task
  .ci/test.sh
Labels: maintenance

#3863 [docs] fix docs for machine_list_filename param
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
Labels: doc

#3825 [ci] improve and run CUDA jobs for every commit and PR
  .ci/setup.sh
  .github/workflows/cuda.yml
  README.md
Labels: maintenance

#3877 [ci] fix R linting job (fixes #3873)
  .ci/test.sh
Labels: blocking, maintenance

#3874 [ci] ignore CUDA-related strings in Python logger test
  src/treelearner/cuda_tree_learner.cpp
  tests/python_package_test/test_utilities.py
Labels: blocking, maintenance

#3876 [ci] fall back to source installs of R packages if binary missing (fixes #3875)
  .ci/test_r_package.sh
Labels: maintenance

#3878 [ci][R-package] remove CI workaround with manual withr installation
  .ci/test_r_package.sh
Labels: maintenance

#3869 [dask] fix teardown issues in Dask tests (fixes #3829)
  tests/python_package_test/test_dask.py
Labels: maintenance

#3879 [dask][tests] increase client close timeout for Dask tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#3866 [dask] Add type hints in Dask package
  docs/conf.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
Labels: doc

#3428 [docs] document CUDA version support
  docs/Installation-Guide.rst
  docs/Parameters.rst
  docs/_static/js/script.js
  include/LightGBM/config.h
  python-package/README.rst
  python-package/setup.py
Labels: doc

#3880 [CUDA] Support CUDA 9 and test different CUDA versions at CI
  .ci/setup.sh
  .github/workflows/cuda.yml
  CMakeLists.txt
Labels: fix

#3693 [python] Start supporting Python 3.9
  .github/workflows/cuda.yml
  .github/workflows/python_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  python-package/setup.py
Labels: feature

#3884 [docs][ci] drop special dependency requirements for RTD site
  .readthedocs.yml
  docs/requirements_rtd.txt
Labels: maintenance

#3887 [docs] improve wordings and code style
  docs/GPU-Tutorial.rst
  docs/Installation-Guide.rst
  python-package/README.rst
Labels: doc
