Repository microsoft/LightGBM, pull requests merged in 2021-08, with the labels that each got.

#4499 [R-package] quote path variables in build-cran-package.sh
  build-cran-package.sh
Labels: maintenance

#4490 Update c_api LGBM_SampleIndices() comment.
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
Labels: maintenance

#4498 [dask] find all needed ports in each host at once (fixes #4458)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: fix

#4505 [R-package] remove unused variable R_SCRIPT in configure.win
  R-package/configure.win
Labels: maintenance

#4501 [tests][dask] reduce number of collisions tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#4509 [docs] Update link to mlr3-compliant interface in README
  README.md
Labels: doc

#4503 [ci] move Solaris and valgrind test steps into scripts
  .ci/test_r_package_solaris.sh
  .ci/test_r_package_valgrind.sh
  .github/workflows/r_solaris.yml
  .github/workflows/r_valgrind.yml
Labels: maintenance

#4519 [ci] replace uses of backticks in test.sh with $()
  .ci/test.sh
Labels: maintenance

#4513 [docs] [R-package] use CRAN-style builds when building pkgdown site
  docs/conf.py
Labels: doc

#4504 [R-package] use C++ compiler for pre-compile checks on Windows
  .ci/test_r_package_valgrind.sh
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  R-package/README.md
  R-package/configure.win
Labels: fix

#4524 [ci] use flag '--allow-releaseinfo-change' in some 'apt-get update' calls
  .github/workflows/r_package.yml
Labels: maintenance

#4520 [docs] Add notes in installation guide, including ones about OpenMP
  docs/Installation-Guide.rst
  python-package/README.rst
Labels: doc

#4522 [R-package] add deprecation warnings about some uses of '...'
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/man/dim.Rd
  R-package/man/getinfo.Rd
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/man/setinfo.Rd
Labels: maintenance

#4506 [R-package] pass R-configured compiler flags to checks in configure
  R-package/configure
  R-package/configure.ac
Labels: fix

#4523 [R-package] remove unused '...' in Booster constructor
  R-package/R/lgb.Booster.R
Labels: maintenance

#4507 [R-package] fix OpenMP checking on macOS (fixes #4131)
  R-package/configure
  R-package/configure.ac
Labels: fix

#4526 [python] add type hints in docs/conf.py
  docs/conf.py
Labels: maintenance

#4532 [docs] Update link to `daal4py` in README
  README.md
Labels: doc

#4527 [python] add type hints to logging functions in basic.py
  python-package/lightgbm/basic.py
Labels: maintenance

#4536 [ci] Add checks that MM_PREFETCH and MM_MALLOC are used in CRAN builds
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: maintenance

#4538 [ci] Add checks that OpenMP is used in R-package builds
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: maintenance

#4530 consolidate duplicate conditions in TextReader
  include/LightGBM/utils/text_reader.h
Labels: efficiency

#4529 [doc] Add link to Neptune hyperparam tuning guide
  README.md
Labels: doc

#4540 [ci] Check for MM_PREFETCH and MM_MALLOC not only in CRAN builds
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: maintenance

#4541 factor out .size() checks in GetDataType()
  src/io/parser.cpp
Labels: efficiency

#4533 [python] add parameter object_hook to method dump_model
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: feature

#4545 [docs] Clarify the fact that predict() on a file does not support saved Datasets (fixes #4034)
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.Dataset.create.valid.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_lgb.Booster.R
  docs/Python-Intro.rst
  python-package/lightgbm/basic.py
  src/io/parser.cpp
Labels: maintenance

#4548 [R-package] add deprecation warnings on uses of '...' in predict() and reset_parameter()
  R-package/NAMESPACE
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#4564 [docs] update links to SynapseML (former MMLSpark)
  README.md
  docs/Parallel-Learning-Guide.rst
Labels: doc

#4563 [docs] add José Morales to repo maintainers
  .github/CODEOWNERS
  docs/FAQ.rst
Labels: doc

#4567 [R-package] use {testthat} SummaryReporter in tests
  R-package/tests/testthat.R
Labels: maintenance

#4565 [python][docs] Refer to string type as `str` in docstrings
  python-package/lightgbm/dask.py
Labels: doc

#4568 [R-package] fix warnings in examples
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/lgb.unloader.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/lgb.Dataset.set.reference.Rd
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.dump.Rd
  R-package/man/lgb.get.eval.result.Rd
  R-package/man/lgb.load.Rd
  R-package/man/lgb.save.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lgb.unloader.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
Labels: doc

#4569 [R-package] fix warnings in demos
  .gitignore
  R-package/demo/basic_walkthrough.R
  R-package/demo/categorical_features_rules.R
  R-package/demo/early_stopping.R
  R-package/demo/leaf_stability.R
  R-package/demo/multiclass.R
  R-package/demo/multiclass_custom_objective.R
  R-package/demo/weight_param.R
Labels: doc

#4558 [dask] Fixed Dask type annotation
  python-package/lightgbm/dask.py
Labels: fix

#4572 [R-package] deprecate uses of '...' in Dataset slice() method
  R-package/R/lgb.Dataset.R
Labels: maintenance

#4575 [docs][python] Refer to functions as `callable` in docstrings
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: doc
