Repository microsoft/LightGBM, pull requests merged in 2021-03, with the labels that each got.

#4032 [dask] [ci] add support for scikit-learn 0.24+ in tests (fixes #4031)
  tests/python_package_test/test_dask.py
Labels: blocking, maintenance

#4035 [docs] Add alt text to image in Parameters-Tuning.rst
  docs/Parameters-Tuning.rst
Labels: doc

#4042 [ci] [R-package] upgrade to R 4.0.4 in CI
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: blocking, maintenance

#4027 [docs] update description of deterministic parameter
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#3950 [dask] Include support for init_score
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_dask.py
Labels: feature

#4047 [ci] ignore untitle Jupyter notebooks in .gitignore
  .gitignore
Labels: maintenance

#4054 [ci] prevent getting incompatible dask and distributed versions
  .ci/test.sh
Labels: blocking, maintenance

#4055 [ci] fix R CMD CHECK note about example timings (fixes #4049)
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: maintenance

#4053 [ci] add CMake + R 3.6 test back (fixes #3469)
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
Labels: maintenance

#4048 [dask] include multiclass-classification task in tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#4029 [docs] Add alt text on images in index.rst
  docs/index.rst
Labels: doc

#4059 [dask] raise more informative error for duplicates in 'machines' (fixes #4057)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#4030 [dask] add tutorial documentation (fixes #3814, fixes #3838)
  docs/Parallel-Learning-Guide.rst
  docs/_static/images/dask-concat.svg
  docs/_static/images/dask-initial-setup.svg
  examples/python-guide/README.md
  examples/python-guide/dask/README.md
  examples/python-guide/dask/binary-classification.py
  examples/python-guide/dask/multiclass-classification.py
  examples/python-guide/dask/prediction.py
  examples/python-guide/dask/ranking.py
  examples/python-guide/dask/regression.py
Labels: doc

#4061 [ci] set 'pending' commit status for running R Solaris optional workflow
  .github/workflows/r_solaris.yml
Labels: maintenance

#4056 Set `is_linear_` to false when it is absent from the model file
  src/io/tree.cpp
Labels: fix

#3555 Add CMake option to enable sanitizers and build gtest
  .gitignore
  CMakeLists.txt
  cmake/Sanitizer.cmake
  cmake/modules/FindASan.cmake
  cmake/modules/FindLSan.cmake
  cmake/modules/FindTSan.cmake
  cmake/modules/FindUBSan.cmake
  tests/cpp_test/test_main.cpp
Labels: maintenance

#4064 [ci] run Dask examples on CI
  .ci/test.sh
  docs/Parallel-Learning-Guide.rst
  examples/python-guide/dask/binary-classification.py
  examples/python-guide/dask/multiclass-classification.py
  examples/python-guide/dask/prediction.py
  examples/python-guide/dask/ranking.py
  examples/python-guide/dask/regression.py
  python-package/README.rst
Labels: maintenance

#4068 [python-package] add type hints on Booster.set_network()
  python-package/lightgbm/basic.py
Labels: maintenance

#3916 [python-package] Some mypy fixes
  python-package/lightgbm/callback.py
  python-package/lightgbm/compat.py
Labels: maintenance

#4071 [dask] [ci] fix flaky network-setup test
  tests/python_package_test/test_dask.py
Labels: maintenance

#4075 [tests][dask] simplify code in Dask tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#4076 [ci] install Dask from main conda channel
  .ci/test.sh
Labels: maintenance

#3942 Fix parsing of non-finite values
  include/LightGBM/utils/common.h
Labels: fix

#4079 [dask] remove unused imports from typing
  python-package/lightgbm/dask.py
Labels: maintenance

#4069 Range check for DCG position discount lookup
  include/LightGBM/metric.h
  src/io/metadata.cpp
  src/metric/dcg_calculator.cpp
  src/metric/rank_metric.hpp
  src/objective/rank_objective.hpp
Labels: fix

#4084 [ci] upgrade R CI scripts to work on Ubuntu 20.04
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  R-package/AUTOCONF_UBUNTU_VERSION
  R-package/README.md
  R-package/recreate-configure.sh
Labels: maintenance

#3997 [SWIG] Add streaming data support + cpp tests
  .ci/test.sh
  include/LightGBM/utils/chunked_array.hpp
  swig/ChunkedArray_API_extensions.i
  swig/StringArray.hpp
  swig/lightgbmlib.i
  tests/cpp_test/test_chunked_array.cpp
Labels: feature

#4087 store all CMake files in one place
  CMakeLists.txt
  build-cran-package.sh
  build_r.R
  cmake/IntegratedOpenCL.cmake
  cmake/modules/FindLibR.cmake
  python-package/MANIFEST.in
  python-package/setup.py
Labels: maintenance

#4094 [ci] Bump version for development
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#4095 [ci] fix flaky Azure Pipelines jobs
  .ci/setup.sh
  .ci/test.sh
Labels: blocking, maintenance

#4096 [docs] add Hummingbird to the list of external projects
  README.md
Labels: doc

#4097 [ci] fix flaky Azure Pipelines jobs (2)
  .ci/setup.sh
Labels: blocking, maintenance

#4098 [docs] add dtreeviz to the list of external projects
  README.md
Labels: doc

#4104 [ci] restrict CMake version for CUDA+Clang jobs
  .ci/setup.sh
Labels: maintenance

#4058 Fix tcp_no_deplay setting by using int type
  src/network/socket_wrapper.hpp
Labels: fix

#4038 [docs] Add alt text on images (related to #4036)
  docs/Features.rst
  docs/GPU-Performance.rst
  docs/GPU-Windows.rst
Labels: doc

#4109 [R-package] fix typo in linear learner test
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#4111 [ci] attach archives with complete source code of the repo to releases
  .vsts-ci.yml
Labels: maintenance

#4112 [ci] bump CUDA version and pull dockers from NVIDIA NGC
  .github/workflows/cuda.yml
Labels: maintenance

#4113 [tests][dask] Create an informative categorical feature
  tests/python_package_test/test_dask.py
Labels: maintenance

#4024 [dask] Include support for raw_score in predict (fixes #3793)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#4117 [ci] build CRAN R-package on Azure with every commit and attach it to releases
  .github/workflows/r_artifacts.yml
  .github/workflows/triggering_comments.yml
  .vsts-ci.yml
  R-package/README.md
Labels: maintenance

#4122 [docs] remove macOS installation method with Homebrew formula
  docs/Installation-Guide.rst
Labels: breaking

#4123 [ci] remove output parametrization from two Dask tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#4092 [ci] apply cpplint to cpp tests
  .ci/test.sh
  include/LightGBM/utils/chunked_array.hpp
  swig/ChunkedArray_API_extensions.i
  swig/StringArray.i
  tests/cpp_test/test_chunked_array.cpp
Labels: awaiting review, maintenance

#4129 [ci] Added curl library to the installed packages list inside dockerfile-python installation
  docker/dockerfile-python
Labels: maintenance

#4127 update CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#4130 [docs] add missed CUDA device type in docs
  docs/Installation-Guide.rst
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#4132 [dask] run one training task on each worker
  python-package/lightgbm/dask.py
Labels: fix

#4137 [ci] use f-strings in `libpath.py`
  python-package/lightgbm/libpath.py
Labels: maintenance

#4119 [tests][dask] test all boosting types (fixes #3896)
  tests/python_package_test/test_dask.py
Labels: maintenance

#4139 [docs] fix param name typo in comments
  python-package/lightgbm/dask.py
Labels: maintenance

#4145 [python] added f-strings to python-package/setup.py
  python-package/setup.py
Labels: maintenance

#4140 [ci] use GitHub Actions to re-generate R configure
  .github/workflows/r_configure.yml
  .github/workflows/triggering_comments.yml
  R-package/README.md
Labels: maintenance

#4133 [dask] make random port search more resilient to random collisions (fixes #4057)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: fix
