Repository microsoft/LightGBM, pull requests merged in 2021-04, with the labels that each got.

#4151 [tests][dask] use dy_true mean in denominator for _r2_score
  tests/python_package_test/test_dask.py
Labels: maintenance

#4088 [tests][dask] Add voting_parallel algorithm in tests (fixes #3834)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#4126 clarify DEBUG-level log about tree depth
  docs/GPU-Targets.rst
  src/treelearner/linear_tree_learner.cpp
  src/treelearner/serial_tree_learner.cpp
Labels: maintenance

#4161 [ci] run 'brew update' in macOS jobs (fixes #4160)
  .ci/test_r_package.sh
Labels: blocking, maintenance

#4147 [python] added f-strings to docs/conf.py
  docs/conf.py
Labels: maintenance

#4159 [tests][dask] replace client fixture with cluster fixture
  tests/python_package_test/test_dask.py
Labels: maintenance

#4157 [docs] update link to Boost binaries
  docs/Installation-Guide.rst
Labels: doc

#4167 [ci] Stop running CUDA tests at CI
  .github/workflows/cuda.yml
Labels: blocking, maintenance

#4158 [ci] upgrade R to 4.0.5 in CI
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
Labels: blocking, maintenance

#4168 [ci] Restrict breathe version at CI
  docs/requirements.txt
Labels: blocking, maintenance

#4093 [python-package] Add type hints to the callback file
  python-package/lightgbm/callback.py
Labels: maintenance

#4043 enforce interaction constraints with monotone_constraints_method = intermediate/advanced
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  tests/python_package_test/test_engine.py
Labels: fix

#4164 [ci] Add debian-clang-devel CI job for the R package
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  R-package/cran-comments.md
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#4162 Migrated to f-strings for .\.nuget\create_nuget.py #4136
  .nuget/create_nuget.py
Labels: maintenance

#4169 v3.2.1 release
  .appveyor.yml
  R-package/configure
  VERSION.txt
Labels: maintenance

#4171 [ci] Bump version for development
  .appveyor.yml
  R-package/configure
  VERSION.txt
Labels: maintenance

#4172 [ci] Restore CUDA jobs at CI
  .github/workflows/cuda.yml
Labels: maintenance

#4177 fix: Dataset::CreateValid init fields which saves to binary.
  src/io/dataset.cpp
Labels: fix

#4103 [swig] add wrapper for LGBM_DatasetGetFeatureNames
  swig/StringArray_API_extensions.i
Labels: feature

#4182 [docs] bring back macOS installation method with Homebrew formula in docs
  docs/Installation-Guide.rst
Labels: doc

#4183 [ci] unpin CMake version for CUDA + Clang toolchain
  .ci/setup.sh
Labels: maintenance

#4166 [ci] run cpp tests at CI
  .ci/test.sh
  .ci/test_windows.ps1
  .github/CODEOWNERS
  .vsts-ci.yml
  CMakeLists.txt
  docs/Development-Guide.rst
  docs/Installation-Guide.rst
  tests/cpp_tests/predict.conf
  tests/cpp_tests/test.py
  tests/cpp_tests/test_chunked_array.cpp
  tests/cpp_tests/test_main.cpp
  tests/cpp_tests/train.conf
Labels: maintenance

#4187 [docs] Add changes to gcc-tips
  docs/_static/images/gcc-bars.png
  docs/_static/images/gcc-chart.png
  docs/_static/images/gcc-comparison-1.png
  docs/_static/images/gcc-meetup-1.png
  docs/_static/images/gcc-meetup-2.png
  docs/_static/images/gcc-table.png
  docs/gcc-Tips.rst
Labels: doc

#4191 [docs] fix markdown in docs
  docs/gcc-Tips.rst
Labels: doc

#4190 [docs] add working dir to R package docker run examples
  R-package/README.md
Labels: doc

#4194 [R-package] Make returned feature importances from lgb.importance() visible by default
  R-package/R/lgb.importance.R
Labels: maintenance

#4199 [docs][R-package] Update the explanation of num_threads (fixes #4192)
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lightgbm.Rd
Labels: doc

#4197 [R-package] change default nrounds to 100 to match LightGBM core library default
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lightgbm.Rd
Labels: breaking

#4188 [python] Migrate to f-strings in python-package/lightgbm/sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4202 [R-package] clarify parameter documentation (fixes #4193)
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lgb_shared_params.Rd
  R-package/man/lightgbm.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
Labels: doc

#4198 [ci] parallelize R package installs in CI jobs
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  .github/workflows/r_solaris.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/static_analysis.yml
  R-package/README.md
Labels: maintenance

#4214 [dask] Fix typo mentioned in 4101
  python-package/lightgbm/dask.py
Labels: maintenance

#4215 [R-package] fix grammar in comments
  R-package/R/lgb.Dataset.R
Labels: maintenance

#4185 [fix] Fix bug in data distributed learning with local empty leaf
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: fix

#4163 [R-package] Move error handling into C++ side
  R-package/R/lgb.Dataset.R
  R-package/R/utils.R
  R-package/src/lightgbm_R.cpp
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#4205 added aliases to params
  docs/Parameters.rst
  include/LightGBM/config.h
  src/io/config_auto.cpp
Labels: feature

#4222 [ci][docs] Unpin Breathe version in requirements.txt
  docs/requirements.txt
Labels: maintenance

#4224 [docs] fix broken MS MPI link in Installation Guide
  docs/Installation-Guide.rst
Labels: doc

#3192 [python][scikit-learn] change MRO
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#4225 [R-package] fix warnings in unit tests
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#4231 Fix typo in binary file already exists error message.
  src/io/dataset.cpp
Labels: fix

#4233 [ci] [python-package] remove unused import in tests
  tests/python_package_test/test_dual.py
Labels: maintenance

#4232 [R-package] avoid misleading warnings when using interaction constraints (fixes #4108)
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
Labels: fix

#4128 show specific error message in TCP accept/send/receive logs
  src/network/socket_wrapper.hpp
Labels: maintenance

#4238 [ci] Install graphviz system-widely
  .ci/setup.sh
  .ci/test.sh
Labels: maintenance

#4243 [docs][python][scikit-learn] added note for LGBMRanker
  python-package/lightgbm/sklearn.py
Labels: doc

#4155 [R-package] prevent symbol lookup conflicts (fixes #4045)
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/R/utils.R
  R-package/src/lightgbm_R.cpp
  R-package/tests/testthat/test_dataset.R
  build_r.R
Labels: fix
