Repository microsoft/LightGBM, pull requests merged in 2021-02, with the labels that each got.

#3885 [CUDA][docs] explicitly require CUDA 9.0 or higher
  CMakeLists.txt
  docs/Installation-Guide.rst
  python-package/README.rst
Labels: doc

#3886 [CUDA] added support for Clang
  .ci/setup.sh
  .github/workflows/cuda.yml
  CMakeLists.txt
  docs/Installation-Guide.rst
Labels: feature

#3888 [ci] added compiler in CUDA job name
  .github/workflows/cuda.yml
Labels: maintenance

#3892 [dask] [python] client.rebalance on dask ranker test
  tests/python_package_test/test_dask.py
Labels: maintenance

#3890 [ci] move link checking to a cron job
  .ci/test.sh
  .github/workflows/linkchecker.yml
  README.md
  docs/.linkcheckerrc
Labels: maintenance

#3893 [ci] install Linkchecker only for check-links job
  .ci/test.sh
  .github/workflows/linkchecker.yml
Labels: maintenance

#3883 [dask] remove 'client' kwarg from fit() and predict() (fixes #3808)
  .ci/test.sh
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#3651 Add new task type: "save_binary".
  docs/Parameters.rst
  include/LightGBM/config.h
  src/application/application.cpp
  src/io/config.cpp
  src/io/dataset_loader.cpp
Labels: feature

#3901 [docs] make link checks badge clickable
  README.md
Labels: doc

#3902 [docs][dask] Add type of client_ property to docs
  python-package/lightgbm/dask.py
Labels: doc

#3903 [ci] Rename linkchecker job
  .github/workflows/linkchecker.yml
Labels: maintenance

#3904 [dask] remove unused private _client attribute
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#3906 [dask] remove extra 'client' kwarg in DaskLGBMRegressor
  python-package/lightgbm/dask.py
Labels: fix

#3895 [SWIG] add size_t manipulation functions
  swig/pointer_manipulation.i
Labels: feature

#3914 fix typos in log messages
  src/io/dataset.cpp
  src/network/network.cpp
  src/treelearner/cuda_tree_learner.cpp
  src/treelearner/gpu_tree_learner.cpp
Labels: maintenance

#3908 [dask] Support Dask dataframes with 'category' columns (fixes #3861)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#3913 [ci][R-package] run R CRAN checks on Solaris by optional workflow
  .ci/run_rhub_solaris_checks.R
  .github/workflows/optional_checks.yml
  .github/workflows/r_solaris.yml
  .github/workflows/triggering_comments.yml
  R-package/README.md
Labels: maintenance

#3917 [ci] update e-mail and token for R Hub builds
  .ci/run_rhub_solaris_checks.R
  .github/workflows/r_solaris.yml
Labels: maintenance

#3911 [dask] Add unit tests that signatures are the same between Dask and scikit-learn estimators
  tests/python_package_test/test_dask.py
Labels: maintenance

#3920 [ci] encode token in the same way as e-mail address for RHub
  .ci/run_rhub_solaris_checks.R
  .github/workflows/r_solaris.yml
Labels: maintenance

#3919 [dask] Add support for 'pred_leaf' in Dask estimators (fixes #3792)
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#3921 [docs] simplify bug report template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: doc

#3898 [docs] fix typo: one-hot coding should be one-hot encoding
  docs/Python-Intro.rst
Labels: doc

#3922 [docs] fix typo in ChatOps command
  R-package/README.md
Labels: maintenance

#3926 [ci] remove unused variable from PATH
  .vsts-ci.yml
Labels: maintenance

#3897 [dask] test training when a worker has no data
  tests/python_package_test/test_dask.py
Labels: maintenance

#3928 [ci] prefer curl to wget
  .ci/setup.sh
  .ci/test_r_package.sh
  docker/dockerfile-python
  docker/gpu/dockerfile.gpu
Labels: maintenance

#3889 fix compilation warnings in CUDA treelearner
  src/treelearner/cuda_tree_learner.h
Labels: maintenance

#3930 [dask] [docs] Fix inaccuracies in API docs for Dask module (fixes #3871)
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_dask.py
Labels: doc

#3932 [dask] test that Dask automatically treats 'category' columns as categorical features
  tests/python_package_test/test_dask.py
Labels: maintenance

#3933 [docs][python] fix shape description of returned result for predict_proba
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: doc

#3935 [docs][dask] add versionadded note to Dask docs
  docs/Python-API.rst
Labels: doc

#3936 Fix access violation exception that can occur during invocation of loop lambda function when inner_start >= inner_end in 'For' template.
  include/LightGBM/utils/threading.h
Labels: fix

#3923 openmp_wrapper.h stubs signature use __GOMP_NOTHROW
  include/LightGBM/utils/openmp_wrapper.h
Labels: maintenance

#3945 [DOCS] Update docs about linear tree and monotone constraints
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#3955 [R-package] fix duplicated return values in docs
  R-package/R/lgb.Dataset.R
  R-package/man/dimnames.lgb.Dataset.Rd
  R-package/man/getinfo.Rd
  R-package/man/setinfo.Rd
Labels: doc

#3954 [docs] add reference to Rust binding
  README.md
Labels: doc

#3959 [ci][python] apply isort to docs/conf.py (#3958)
  docs/conf.py
Labels: maintenance

#3960 [docs] fix typos in network docs
  src/network/linkers.h
Labels: doc

#3961 [ci][python] apply isort to examples/python-guide/advanced_example.py #3958
  examples/python-guide/advanced_example.py
Labels: maintenance

#3962 [ci][python] apply isort to examples/python-guide/logistic_regression.py #3958
  examples/python-guide/logistic_regression.py
Labels: maintenance

#3963 [ci][python] apply isort to examples/python-guide/plot_example.py #3958
  examples/python-guide/plot_example.py
Labels: maintenance

#3964 [ci][python] apply isort to examples/python-guide/simple_example.py #3958
  examples/python-guide/simple_example.py
Labels: maintenance

#3891 [python-package] fix some warnings from mypy
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  python-package/setup.py
Labels: in progress, maintenance

#3965 [ci][python] apply isort to examples/python-guide/sklearn_example.py #3958
  examples/python-guide/sklearn_example.py
Labels: maintenance

#3979 [ci][python] apply isort to tests/python_package_test/test_dask.py #3958
  tests/python_package_test/test_dask.py
Labels: maintenance

#3971 [ci][python] apply isort to python-package/lightgbm/libpath.py #3958
  python-package/lightgbm/libpath.py
Labels: maintenance

#3980 [ci][python] apply isort to tests/python_package_test/test_dual.py #3958
  tests/python_package_test/test_dual.py
Labels: maintenance

#3975 [ci][python] apply isort to tests/c_api_test/test_.py #3958
  tests/c_api_test/test_.py
Labels: maintenance

#3976 [ci][python] apply isort to tests/cpp_test/test.py #3958
  tests/cpp_test/test.py
Labels: maintenance

#3972 [ci][python] apply isort to python-package/lightgbm/plotting.py #3958
  python-package/lightgbm/plotting.py
Labels: maintenance

#3974 [ci][python] apply isort to python-package/setup.py #3958
  python-package/setup.py
Labels: maintenance

#3984 [ci][python] apply isort to tests/python_package_test/test_utilities.py #3958
  tests/python_package_test/test_utilities.py
Labels: maintenance

#3982 [ci][python] apply isort to tests/python_package_test/test_plotting.py #3958
  tests/python_package_test/test_plotting.py
Labels: maintenance

#3978 [ci][python] apply isort to tests/python_package_test/test_consistency.py #3958
  tests/python_package_test/test_consistency.py
Labels: maintenance

#3977 [ci][python] apply isort to tests/python_package_test/test_basic.py #3958
  tests/python_package_test/test_basic.py
Labels: maintenance

#3973 [ci][python] apply isort to python-package/lightgbm/sklearn.py #3958
  python-package/lightgbm/sklearn.py
Labels: maintenance

#3966 [ci][python] apply isort to python-package/lightgbm/__init__.py #3958
  python-package/lightgbm/__init__.py
Labels: maintenance

#3967 [ci][python] apply isort to python-package/lightgbm/basic.py #3958
  python-package/lightgbm/basic.py
Labels: maintenance

#3981 [ci][python] apply isort to tests/python_package_test/test_engine.py #3958
  tests/python_package_test/test_engine.py
Labels: maintenance

#3970 [ci][python] apply isort to python-package/lightgbm/engine.py #3958
  python-package/lightgbm/engine.py
Labels: maintenance

#3968 [ci][python] apply isort to python-package/lightgbm/compat.py #3958
  python-package/lightgbm/compat.py
Labels: maintenance

#3990 [ci][python] run isort in CI linting job
  .ci/get_workflow_status.py
  .ci/test.sh
  .editorconfig
  .nuget/create_nuget.py
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#3948 Run tests and build Python wheels for aarch64 architecture
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
Labels: feature

#3992 [ci][python] hotfix imports order
  tests/python_package_test/test_dask.py
Labels: maintenance

#3927 Optimize array-from-ctypes in basic.py
  python-package/lightgbm/basic.py
Labels: efficiency

#3937 Fix for CreatePredictor function and VS2017 Debug build
  src/c_api.cpp
Labels: fix

#3993 [tests][dask] make find-open-port test more reliable
  tests/python_package_test/test_dask.py
Labels: maintenance

#3947 [tests][dask] add scikit-learn compatibility tests (fixes #3894)
  tests/python_package_test/test_dask.py
Labels: maintenance

#3999 remove commented-out code in cross-entropy metric source
  src/metric/xentropy_metric.hpp
Labels: maintenance

#4000 [docs] Change some 'parallel learning' references to 'distributed learning'
  CMakeLists.txt
  README.md
  docs/Advanced-Topics.rst
  docs/Experiments.rst
  docs/Features.rst
  docs/Installation-Guide.rst
  docs/Parallel-Learning-Guide.rst
  docs/Parameters.rst
  docs/Quick-Start.rst
  docs/index.rst
  examples/binary_classification/train.conf
  examples/binary_classification/train_linear.conf
  examples/lambdarank/train.conf
  examples/parallel_learning/README.md
  examples/regression/train.conf
  examples/xendcg/train.conf
  include/LightGBM/config.h
  include/LightGBM/dataset.h
  python-package/lightgbm/basic.py
  src/application/application.cpp
  src/io/config.cpp
  src/io/dataset_loader.cpp
  src/io/metadata.cpp
Labels: doc

#3938 Use high precision conversion from double to string in Tree::ToString() for new linear tree members
  src/io/tree.cpp
Labels: fix

#4004 [dask] use more specific method names on _DaskLGBMModel
  python-package/lightgbm/dask.py
Labels: maintenance

#4010 [ci] prefer older binary to new source for R packages on Mac builds (fixes #4008)
  .ci/test_r_package.sh
Labels: blocking, maintenance

#3987 Fix evalution of linear trees with a single leaf.
  include/LightGBM/tree.h
  src/io/tree.cpp
Labels: fix

#3951 [doc] Reorganize documentation on distributed learning (fixes #3596)
  docs/Advanced-Topics.rst
  docs/Features.rst
  docs/Parallel-Learning-Guide.rst
  examples/parallel_learning/README.md
Labels: doc

#4006 [DOCS] Update docs to note that pred_contrib is not available for linear trees
  docs/Parameters.rst
  include/LightGBM/config.h
  src/application/predictor.hpp
Labels: doc

#3994 [dask] allow tight control over ports
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#4016 [dask] Reuse addresses saved in variable
  python-package/lightgbm/dask.py
Labels: maintenance

#3823 [dask] use random ports in network setup
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: efficiency

#4015 [tests][python] Add test for single leaf in linear tree
  tests/python_package_test/test_engine.py
Labels: maintenance

#3943 [dask] [python-package] include support for column array as label
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#4018 [tests][dask] simplify fit calls in Dask tests
  tests/python_package_test/test_dask.py
Labels: maintenance

#4013 [docs] Add FLAML for efficient hyperparameter optimization
  README.md
  docs/Parameters-Tuning.rst
Labels: doc
