Repository microsoft/LightGBM, pull requests merged in 2021-09, with the labels that each got.

#4570 [python] add 'auto' value for `importance_type` param in plotting
  python-package/lightgbm/plotting.py
  tests/python_package_test/test_plotting.py
Labels: breaking

#4582 [R-package] fix inaccurate comments, remove unnecessary comments
  R-package/R/callback.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.convert_with_rules.R
  R-package/R/lgb.importance.R
  R-package/R/lgb.interprete.R
Labels: maintenance

#4588 [R-package] fix inaccurate error message in Dataset get_colnames() method
  R-package/R/lgb.Dataset.R
Labels: maintenance

#4579 [ci] explicitly set --platform when running aarch64 image in QEMU builds
  .vsts-ci.yml
Labels: maintenance

#4592 [ci] simplify docker info parsing in QEMU builds
  .vsts-ci.yml
Labels: maintenance

#4577 [RFC][python] deprecate `silent` and standalone `verbose` args. Prefer global `verbose` param
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: breaking

#4600 [ci] skip Dask tests on QEMU builds
  tests/python_package_test/test_dask.py
Labels: maintenance

#4593 prefer spaces to tabs in CMakeLists.txt
  CMakeLists.txt
Labels: maintenance

#4595 [tests][dask] Use workers hostname in tests (fixes #4594)
  tests/python_package_test/test_dask.py
Labels: maintenance

#4584 [docs] add lightgbm_ray to docs
  README.md
  docs/Parallel-Learning-Guide.rst
Labels: doc

#4603 [ci] fix link to LightGBM public e-mail
  .github/workflows/r_solaris.yml
Labels: maintenance

#4599 [python][sklearn] respect `eval_at` aliases in keyword arguments
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: awaiting review, fix

#4587 [R-package] avoid unnecessary computation and add tests for Dataset set_reference() method
  R-package/R/lgb.Dataset.R
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#4574 [RFC][python] deprecate advanced args of `train()` and `cv()` functions and sklearn wrapper
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_utilities.py
Labels: breaking

#4604 [python] rename `print_evaluation()` into `log_evaluation()`
  docs/Python-API.rst
  python-package/lightgbm/__init__.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_utilities.py
Labels: breaking

#4611 [ci] Stop running CUDA tests at CI
  .github/workflows/cuda.yml
Labels: blocking, maintenance

#4597 [R-package] Fix R memory leaks (fixes #4282, fixes #3462)
  R-package/src/lightgbm_R.cpp
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  include/LightGBM/utils/log.h
Labels: fix

#4150 [python-package] Support 2d collections as input for `init_score` in multiclass classification task
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_dask.py
Labels: feature

#4606 [docs] update link to MinGW-w64 site
  R-package/README.md
  docs/Installation-Guide.rst
  python-package/README.rst
Labels: doc

#4615 [python] fix mypy error in `dask.py`
  python-package/lightgbm/dask.py
Labels: maintenance

#4620 [python] initialize installation options with boolean values in `setup.py`
  python-package/setup.py
Labels: maintenance

#4616 [docs] add Mars to docs
  README.md
  docs/Parallel-Learning-Guide.rst
Labels: doc

#4617 [ci] Run cmakelint at CI and fix some errors
  .ci/test.sh
  CMakeLists.txt
  cmake/modules/FindLibR.cmake
Labels: maintenance

#4613 [R-package] prevent memory leak if pointer fails to allocate
  R-package/src/lightgbm_R.cpp
Labels: fix

#4542 simplify and speed up comparisons for splits with identical gains
  src/treelearner/split_info.hpp
Labels: efficiency

#4496 move Network method implementations from network.h to network.cpp (fixes #4464)
  include/LightGBM/network.h
  src/network/network.cpp
Labels: fix

#4621 [ci] Recover running CUDA tests at CI (fixed #4611)
  .github/workflows/cuda.yml
Labels: maintenance

#4614 [python] add placeholders to titles in plotting functions
  python-package/lightgbm/plotting.py
  tests/python_package_test/test_plotting.py
Labels: feature

#4624 [python] deprecate "auto" value of `ylabel` argument of `plot_metric()` function
  python-package/lightgbm/plotting.py
Labels: breaking

#4571 [R-package] introduce Dataset methods set_field() and get_field()
  R-package/DESCRIPTION
  R-package/NAMESPACE
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.plot.interpretation.R
  R-package/demo/basic_walkthrough.R
  R-package/demo/boost_from_prediction.R
  R-package/demo/cross_validation.R
  R-package/demo/early_stopping.R
  R-package/demo/multiclass_custom_objective.R
  R-package/man/get_field.Rd
  R-package/man/lgb.interprete.Rd
  R-package/man/lgb.plot.interpretation.Rd
  R-package/man/set_field.Rd
  R-package/man/slice.Rd
  R-package/pkgdown/_pkgdown.yml
  R-package/tests/testthat/test_custom_objective.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
Labels: maintenance

#4586 [R-package] fix segfaults caused by missing Booster and Dataset handles (fixes #4208)
  R-package/R/lgb.Dataset.R
  R-package/src/lightgbm_R.cpp
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: in progress, fix

#4628 [ci] bump CUDA version from 11.4.0 to 11.4.2 at CI
  .github/workflows/cuda.yml
Labels: maintenance
