Repository microsoft/LightGBM, pull requests merged in 2022-08, with the labels that each got.

#5398 [ci] temporarily pin scipy version and fix Python linting error
  .ci/test.sh
  python-package/lightgbm/basic.py
Labels: blocking, maintenance

#5395 Fix potential overflow in linear trees
  src/treelearner/linear_tree_learner.cpp
Labels: fix

#5394 Minor CUDA cleanup
  python-package/README.rst
  src/boosting/cuda/cuda_score_updater.cu
Labels: maintenance

#5406 [python-package] add type hints on Booster.save_model()
  python-package/lightgbm/basic.py
Labels: maintenance

#5409 [python-package] prefix NUMERIC_TYPES with _ to make it a internal object
  python-package/lightgbm/basic.py
Labels: maintenance

#5119 [python-package] highlight the path a sample takes through a tree in `plot_tree` and `create_tree_digraph` (fixes #4784)
  python-package/lightgbm/basic.py
  python-package/lightgbm/plotting.py
  tests/python_package_test/test_plotting.py
Labels: feature

#5299 feature: Add true streaming APIs to reduce client-side memory usage
  CMakeLists.txt
  include/LightGBM/bin.h
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  include/LightGBM/feature_group.h
  src/c_api.cpp
  src/io/dataset.cpp
  src/io/metadata.cpp
  src/io/sparse_bin.hpp
  swig/pointer_manipulation.i
  tests/cpp_tests/test_stream.cpp
  tests/cpp_tests/testutils.cpp
  tests/cpp_tests/testutils.h
Labels: feature

#5407 [python-package] add more type hints in basic.py
  python-package/lightgbm/basic.py
Labels: maintenance

#5414 [ci] increase valgrind timeout to 5 hours
  .github/workflows/r_valgrind.yml
Labels: maintenance

#5421 [python] Prefix `basic.is_numeric()` with _
  python-package/lightgbm/basic.py
Labels: maintenance

#5160 [python-package] support saving and loading CVBooster (fixes #3556)
  python-package/lightgbm/engine.py
  tests/python_package_test/test_callback.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/utils.py
Labels: feature

#5413 Add default definition for GetColWiseData and GetColWiseData
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  src/io/bin.cpp
  src/io/dense_bin.cpp
  src/io/multi_val_dense_bin.cpp
  src/io/multi_val_sparse_bin.cpp
  src/io/sparse_bin.cpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: fix

#5429 [ci] increase valgrind bytes lost limit to 352
  .ci/test_r_package_valgrind.sh
Labels: maintenance

#5403 [fix] change the destructor of ScoreUpdater to virtual (fixes #5400)
  src/boosting/score_updater.hpp
Labels: fix

#5432 [python-package] add more type hints on Booster
  python-package/lightgbm/basic.py
Labels: awaiting review, maintenance

#5431 [python-package] add more type hints on Dataset
  python-package/lightgbm/basic.py
Labels: maintenance

#5287 [ci] bump CUDA version from `11.6.2` to `11.7.0` at CI
  .github/workflows/cuda.yml
Labels: maintenance

#5422 update tree to if-else
  src/io/tree.cpp
Labels: maintenance

#5433 [python-package] add type hints on Booster eval methods
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/sklearn.py
Labels: awaiting review, maintenance

#5412 [python-package] ignore training set on early stopping callback (fixes #5354)
  python-package/lightgbm/callback.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/test_utilities.py
Labels: fix

#5442 [ci] bump CUDA version from `11.7.0` to `11.7.1` at CI
  .github/workflows/cuda.yml
Labels: maintenance

#5443 [python] remove unused import
  python-package/lightgbm/plotting.py
Labels: maintenance

#5416 include parameters from reference dataset on subset (fixes #5402)
  src/io/dataset.cpp
  tests/python_package_test/test_basic.py
Labels: fix

#5444 [R-package] Fix docstrings for predict functions
  R-package/src/lightgbm_R.h
Labels: doc

#5438 [ci][fix] Fix cuda_exp ci
  .github/workflows/cuda.yml
  include/LightGBM/cuda/cuda_utils.h
  include/LightGBM/tree_learner.h
  src/boosting/cuda/cuda_score_updater.cpp
  src/boosting/cuda/cuda_score_updater.cu
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/boosting/rf.hpp
  src/io/cuda/cuda_tree.cu
  src/objective/objective_function.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp
  tests/python_package_test/test_utilities.py
Labels: awaiting review, maintenance

#5447 [python-package] fix mypy error about type change in Dataset.feature_num_bin()
  python-package/lightgbm/basic.py
Labels: maintenance

#5445 [python-package] add type hints on empty initializations
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
Labels: maintenance

#5451 [docs] Fix links
  docs/GPU-Windows.rst
  docs/Parallel-Learning-Guide.rst
Labels: doc

#5450 [python-package] fix mypy errors about callbacks
  python-package/lightgbm/engine.py
Labels: maintenance

#5446 [python-package] fix type hints on ctypes array converters
  python-package/lightgbm/basic.py
Labels: maintenance

#5425 [CUDA] Add binary objective for cuda_exp
  CMakeLists.txt
  include/LightGBM/cuda/cuda_objective_function.hpp
  include/LightGBM/objective_function.h
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/objective/binary_objective.hpp
  src/objective/cuda/cuda_binary_objective.cpp
  src/objective/cuda/cuda_binary_objective.cu
  src/objective/cuda/cuda_binary_objective.hpp
  src/objective/objective_function.cpp
  tests/python_package_test/test_utilities.py
Labels: awaiting review, feature

#5452 [CUDA] L2 regression objective for cuda_exp
  include/LightGBM/cuda/cuda_algorithms.hpp
  include/LightGBM/objective_function.h
  src/cuda/cuda_algorithms.cu
  src/objective/cuda/cuda_regression_objective.cpp
  src/objective/cuda/cuda_regression_objective.cu
  src/objective/cuda/cuda_regression_objective.hpp
  src/objective/objective_function.cpp
Labels: awaiting review, feature

#5455 [R-package] fix function references in error messages
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
Labels: maintenance
