Repository microsoft/LightGBM, pull requests merged in 2022-06, with the labels that each got.

#5258 [c++][fix] check nullable of bin mappers in dataset_loader.cpp (fix #5221)
  src/io/dataset_loader.cpp
Labels: fix

#5264 [docs] add Microsoft security policy (fixes #5235)
  SECURITY.md
Labels: doc

#5265 [docs] Update broken links in docs
  docs/GPU-Windows.rst
Labels: doc

#5254 [python-package] make a shallow copy on dataframe rename (fixes #4596)
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: efficiency

#5251 [R-package] [docs] upgrade docs to roxygen2==7.2.0
  R-package/DESCRIPTION
  docs/env.yml
Labels: doc

#5255 [python] add more type hints in basic.py
  python-package/lightgbm/basic.py
Labels: maintenance

#5267 [tests][python] Make test that checks original pandas data isn't modified more strict
  tests/python_package_test/test_basic.py
Labels: maintenance

#5164 Clear split info buffer in cost efficient gradient boosting before every iteration (fix partially #3679)
  src/treelearner/cost_effective_gradient_boosting.hpp
  src/treelearner/serial_tree_learner.cpp
  tests/python_package_test/test_engine.py
Labels: fix

#5272 [python-package] remove Booster.set_attr() and Booster.attr()
  python-package/lightgbm/basic.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#5282 [ci] Run Linux OpenCL tests against POCL instead of the AMD App SDK
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
  docs/GPU-Targets.rst
Labels: maintenance

#5284 [docs] Use https links in docs
  docs/GPU-Targets.rst
Labels: doc

#5273 [R-package] [docs] document difference between lightgbm() and lgb.train() (fixes #5203)
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/man/lgb.train.Rd
  R-package/man/lightgbm.Rd
Labels: doc

#5290 [ci] Pin lintr to <3.0
  .ci/test.sh
Labels: maintenance

#5108 [R-package] Add sparse feature contribution predictions
  R-package/NAMESPACE
  R-package/R/lgb.Predictor.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_Predictor.R
Labels: feature

#5105 [python-package] Use scikit-learn interpretation of negative `n_jobs` and change default to number of cores
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_consistency.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#5271 [python-package] add type hints on cv()
  python-package/lightgbm/compat.py
  python-package/lightgbm/engine.py
Labels: maintenance

#5300 [R-package] Specify concrete linting rule that is being ignored via `nolint` mark
  R-package/R/utils.R
  R-package/inst/make-r-def.R
  R-package/src/install.libs.R
  build_r.R
Labels: maintenance

#5286 [ci] Install PoCL in Docker for old Ubuntu 14.04
  .ci/setup.sh
Labels: maintenance

#5289 [python] preserve None in _choose_param_value()
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: maintenance

#5302 [python-package] add some type hints on Booster
  python-package/lightgbm/basic.py
Labels: maintenance

#5306 [ci] [R-package] Add any_is_na_linter
  .ci/lint_r_code.R
  R-package/tests/testthat/test_metrics.R
Labels: maintenance

#5308 [python][sklearn] Simplify params handling in `predict()` with `_choose_param_value()`
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5307 [ci] [R-package] Add class_equals linter
  .ci/lint_r_code.R
  R-package/R/utils.R
Labels: maintenance

#5310 [ci] [R-package] Add duplicate_argument_linter
  .ci/lint_r_code.R
  R-package/tests/testthat/test_utils.R
Labels: maintenance

#5322 [docs] set language = 'en' in Sphinx config
  docs/conf.py
Labels: blocking, doc

#5309 [python-package] add more type hints on Booster
  python-package/lightgbm/basic.py
Labels: maintenance

#5324 [ci] [R-package] Add string_boundary_linter
  .ci/lint_r_code.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  build_r.R
Labels: maintenance

#5301 [python-package] add more type hints in engine.py
  python-package/lightgbm/engine.py
Labels: maintenance

#5327 [ci][R-package] Minor refactoring for `lintr` code
  .ci/lint_r_code.R
  R-package/R/utils.R
Labels: maintenance

#5326 [docs][python] Fix return types in docstrings
  python-package/lightgbm/basic.py
Labels: doc

#4909 [python-package] check feature names in predict with dataframe (fixes #812)
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  src/c_api.cpp
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#5133 [R-package] Use `type` argument to control prediction types
  R-package/R/lgb.Booster.R
  R-package/demo/boost_from_prediction.R
  R-package/demo/leaf_stability.R
  R-package/demo/multiclass.R
  R-package/demo/multiclass_custom_objective.R
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: breaking

#5211 [python-package] allow custom weighing in fobj for scikit-learn API (closes #5027)
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/utils.py
Labels: breaking
