Repository microsoft/LightGBM, pull requests merged in 2022-11, with the labels that each got.

#5563 [ci] fix R-package CI jobs and compatibility with OpenMP 15+ (fixes #5549, #5562)
  .ci/test_r_package_windows.ps1
  CMakeLists.txt
  R-package/configure
  R-package/configure.ac
Labels: fix

#5570 [ci] upgrade macOS_regular job to Python 3.9 (fixes #5569)
  .vsts-ci.yml
Labels: maintenance

#5533 [docs] bump development version to 3.3.3.99
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#5555 [ci] prefer CPython in Linux and macOS test environment
  .ci/test.sh
Labels: maintenance

#5554 [docs] Improve docs: fix consistency of dots in C API and add notes about new ``time-costs`` Python-package build option
  include/LightGBM/c_api.h
  python-package/README.rst
Labels: doc

#5559 [python-package] remove unused imports
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5545 [python-package] prefix several internal functions with _
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: maintenance

#5491 [CUDA] Add multiclass_ova objective for cuda_exp
  src/objective/cuda/cuda_binary_objective.cpp
  src/objective/cuda/cuda_binary_objective.cu
  src/objective/cuda/cuda_multiclass_objective.cpp
  src/objective/cuda/cuda_multiclass_objective.hpp
  src/objective/multiclass_objective.hpp
  src/objective/objective_function.cpp
Labels: feature

#5580 [ci] switch to manylinux_2_28 for Linux artifacts (fixes #5514, fixes #5589)
  .ci/setup.sh
  .vsts-ci.yml
  docs/Installation-Guide.rst
  helpers/check_dynamic_dependencies.py
  python-package/README.rst
Labels: breaking

#5561 prefer 'vsnprintf' to 'vsprintf'
  include/LightGBM/utils/log.h
Labels: fix

#5544 [tests][dask] fix workers without data test (fixes #5537)
  tests/python_package_test/test_dask.py
Labels: fix

#5602 [ci] switch from MiKTeX to tinytex on Windows R jobs (fixes #5600)
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
Labels: awaiting review, maintenance

#5396 [ci] migrate CI from macOS 10.15 to 11 (fixes #5391)
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
  python-package/README.rst
  tests/python_package_test/test_dask.py
Labels: breaking

#5603 [swig] switch to SWIG_ADD_LIBRARY() in CMakeLists.txt (fixes #5586)
  CMakeLists.txt
Labels: maintenance

#5598 [ci] [python-package] correct tag on x86_64 wheels
  .ci/test.sh
  .vsts-ci.yml
Labels: fix

#5590 [ci] update versions of GitHub Actions
  .github/workflows/linkchecker.yml
  .github/workflows/optional_checks.yml
  .github/workflows/python_package.yml
  .github/workflows/r_configure.yml
  .github/workflows/r_package.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/static_analysis.yml
  .github/workflows/triggering_comments.yml
Labels: maintenance

#5486 [CUDA] Add Poisson regression objective for cuda_exp and refactor objective functions for cuda_exp
  include/LightGBM/cuda/cuda_algorithms.hpp
  include/LightGBM/cuda/cuda_objective_function.hpp
  src/cuda/cuda_algorithms.cu
  src/objective/binary_objective.hpp
  src/objective/cuda/cuda_binary_objective.cpp
  src/objective/cuda/cuda_binary_objective.cu
  src/objective/cuda/cuda_binary_objective.hpp
  src/objective/cuda/cuda_multiclass_objective.cpp
  src/objective/cuda/cuda_multiclass_objective.cu
  src/objective/cuda/cuda_multiclass_objective.hpp
  src/objective/cuda/cuda_rank_objective.cpp
  src/objective/cuda/cuda_rank_objective.cu
  src/objective/cuda/cuda_rank_objective.hpp
  src/objective/cuda/cuda_regression_objective.cpp
  src/objective/cuda/cuda_regression_objective.cu
  src/objective/cuda/cuda_regression_objective.hpp
  src/objective/objective_function.cpp
  src/objective/rank_objective.hpp
  src/objective/regression_objective.hpp
  tests/python_package_test/test_engine.py
Labels: awaiting review, feature

#5582 [ci] add docs and specific error messages in check_dynamic_dependencies.py
  helpers/check_dynamic_dependencies.py
Labels: maintenance

#5607 [R-package] correctly quote paths on Windows for CMake-based builds
  build_r.R
Labels: fix

#5551 Fix OpenMP thread allocation in Linux
  include/LightGBM/bin.h
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  include/LightGBM/feature_group.h
  src/c_api.cpp
  src/io/sparse_bin.hpp
  tests/cpp_tests/test_stream.cpp
Labels: fix

#5610 [ci] detect non-default dynamic symbols in check_dynamic_dependencies.py
  helpers/check_dynamic_dependencies.py
Labels: maintenance
