Repository microsoft/LightGBM, pull requests merged in 2022-09, with the labels that each got.

#5457 [CUDA] Add L1 regression objective for cuda_exp
  include/LightGBM/cuda/cuda_algorithms.hpp
  include/LightGBM/cuda/cuda_utils.h
  src/cuda/cuda_algorithms.cu
  src/objective/cuda/cuda_regression_objective.cpp
  src/objective/cuda/cuda_regression_objective.cu
  src/objective/cuda/cuda_regression_objective.hpp
Labels: awaiting review, feature

#5461 Rename Metadata num_classes to be more clear
  include/LightGBM/dataset.h
  src/io/metadata.cpp
Labels: maintenance

#5462 [CUDA] Add Huber regression objective for cuda_exp
  include/LightGBM/tree_learner.h
  src/boosting/gbdt.cpp
  src/boosting/rf.hpp
  src/objective/cuda/cuda_regression_objective.cpp
  src/objective/cuda/cuda_regression_objective.cu
  src/objective/cuda/cuda_regression_objective.hpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  tests/python_package_test/test_engine.py
Labels: awaiting review, feature

#5463 [docs]fix a typo in docs/Features.rst
  docs/Features.rst
Labels: doc

#5437 Add streaming concurrency tests
  tests/cpp_tests/test_stream.cpp
  tests/cpp_tests/testutils.cpp
  tests/cpp_tests/testutils.h
Labels: maintenance

#5458 [python-package] add type hints on Dataset constructors
  python-package/lightgbm/basic.py
Labels: maintenance

#5466 Fix CUDA `#ifndef` guards
  include/LightGBM/cuda/cuda_column_data.hpp
  include/LightGBM/cuda/cuda_metadata.hpp
  include/LightGBM/cuda/cuda_objective_function.hpp
  include/LightGBM/cuda/cuda_row_data.hpp
  src/objective/cuda/cuda_regression_objective.hpp
Labels: maintenance

#5453 [CUDA] Add lambdarank objective for cuda_exp
  include/LightGBM/cuda/cuda_algorithms.hpp
  src/cuda/cuda_algorithms.cu
  src/objective/cuda/cuda_rank_objective.cpp
  src/objective/cuda/cuda_rank_objective.cu
  src/objective/cuda/cuda_rank_objective.hpp
  src/objective/objective_function.cpp
  src/objective/rank_objective.hpp
Labels: awaiting review, feature

#5467 fix: Revert leftover debugging in streaming test
  tests/cpp_tests/test_stream.cpp
Labels: maintenance

#5465 [python] Fix typehints in Sequence API
  python-package/lightgbm/basic.py
Labels: maintenance

#5468 fix references to 'object function'
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
Labels: maintenance

#5469 [CUDA] Add fair regression objective for cuda_exp
  src/objective/cuda/cuda_regression_objective.cpp
  src/objective/cuda/cuda_regression_objective.cu
  src/objective/cuda/cuda_regression_objective.hpp
  src/objective/objective_function.cpp
  tests/python_package_test/test_engine.py
Labels: awaiting review, feature

#5472 [CUDA] Add rank_xendcg objective for cuda_exp
  src/objective/cuda/cuda_rank_objective.cpp
  src/objective/cuda/cuda_rank_objective.cu
  src/objective/cuda/cuda_rank_objective.hpp
  src/objective/objective_function.cpp
Labels: awaiting review, feature

#5474 [CUDA] Add feature interaction constraint for cuda_exp (fix #4785)
  include/LightGBM/cuda/cuda_tree.hpp
  src/io/cuda/cuda_tree.cpp
  src/treelearner/cuda/cuda_best_split_finder.cpp
  src/treelearner/cuda/cuda_best_split_finder.cu
  src/treelearner/cuda/cuda_best_split_finder.hpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp
  tests/python_package_test/test_engine.py
Labels: awaiting review, feature

#5456 [python-package] simplify Dataset processing of label
  python-package/lightgbm/basic.py
Labels: efficiency

#5473 [CUDA] Add multiclass objective for cuda_exp
  src/objective/cuda/cuda_multiclass_objective.cpp
  src/objective/cuda/cuda_multiclass_objective.cu
  src/objective/cuda/cuda_multiclass_objective.hpp
  src/objective/multiclass_objective.hpp
  src/objective/objective_function.cpp
Labels: feature

#5480 Remove redundant whitespaces
  src/io/bin.cpp
  src/network/socket_wrapper.hpp
  src/objective/binary_objective.hpp
  src/treelearner/cuda/cuda_data_partition.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/monotone_constraints.hpp
Labels: maintenance

#5479 [R-package] [ci] restore R 3.6 Windows cran CI job (fixes #5036)
  .github/workflows/r_package.yml
  build-cran-package.sh
Labels: maintenance

#5460 [python-package] add more hints in sklearn.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5448 [ci] [R-package] ensure that MSVC jobs fail when tests fail (fixes #5439)
  .ci/test_r_package_windows.ps1
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#5485 [R-package] improve safety of index selection in plotting
  R-package/R/lgb.plot.importance.R
  R-package/R/lgb.plot.interpretation.R
Labels: blocking, maintenance

#5484 [ci] test against R 4.2 for macOS and Linux CI jobs
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
Labels: maintenance
