Repository microsoft/LightGBM, pull requests merged in 2022-03, with the labels that each got.

#5034 [tests][python] move tests that use `train()` function defined in `engine.py` from `test_basic.py` to `test_engine.py`
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#5049 [ci] temporarily remove R3.6 CRAN CI build
  .github/workflows/r_package.yml
Labels: maintenance

#5044 [docs] update categorical feature description in Advanced Topics
  docs/Advanced-Topics.rst
Labels: doc

#5054 [python-package][docs] Booster eval methods accept list of callables
  python-package/lightgbm/basic.py
Labels: doc

#5050 [fix] fix duplicate added initial scores for single-leaf trees
  src/boosting/gbdt.cpp
  tests/python_package_test/test_engine.py
Labels: fix

#5068 [ci] fix current `master` fails with graphviz-related error
  .ci/test_windows.ps1
Labels: blocking, maintenance

#5059 Build Windows artifacts in `windows-2019` image instead of `vs2017-win2016`
  .vsts-ci.yml
Labels: breaking

#4973 [R-package] Rename `data` -> `newdata` in `predict`
  R-package/R/lgb.Booster.R
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_Predictor.R
Labels: breaking

#4266 Minimal Varianсe Sampling booster
  .ci/test_windows.ps1
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/utils/array_args.h
  python-package/lightgbm/sklearn.py
  src/boosting/boosting.cpp
  src/boosting/mvs.cpp
  src/boosting/mvs.hpp
  src/io/config.cpp
  src/io/config_auto.cpp
  tests/cpp_tests/test_mvs_threshold_search.cpp
  tests/python_package_test/test_dask.py
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: in progress, feature

#5066 [python-package] [R-package] propagate the best iteration of cvbooster into the individual boosters
  R-package/R/lgb.cv.R
  R-package/tests/testthat/test_basic.R
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: feature

#5063 [ci] update CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#5065 [python-package] Better column dtype logging when column has "bad dtype"
  python-package/lightgbm/basic.py
Labels: maintenance

#5048 [c-api][python-package][R-package] expose feature num bin
  R-package/R/lgb.Dataset.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_dataset.R
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  tests/python_package_test/test_basic.py
Labels: feature

#5079 [ci] remove Visual Studio 2017 CI job for R-package
  .github/workflows/r_package.yml
Labels: blocking, maintenance

#5012 [python] make `early_stopping` callback pickleable
  .ci/test_windows.ps1
  python-package/lightgbm/callback.py
  tests/python_package_test/test_callback.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/utils.py
Labels: feature

#5078 [docs] Improve rendering of class properties in docs
  docs/_static/js/script.js
Labels: doc

#5082 [ci] Add text file with GitHub commit hash to nightly builds
  .vsts-ci.yml
Labels: maintenance

#5083 clarify no-meaningful-features warning in Dataset construction (fixes #5081)
  src/io/dataset.cpp
  tests/python_package_test/test_utilities.py
Labels: maintenance

#4975 [R-package] Rename `weight` -> `weights`
  R-package/R/lightgbm.R
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
Labels: feature

#4448 Log warnings for number of bins of categorical features
  include/LightGBM/dataset_loader.h
  src/io/dataset_loader.cpp
  src/treelearner/cuda_tree_learner.cpp
  src/treelearner/gpu_tree_learner.cpp
Labels: maintenance

#4880 [python] allow to register any custom logger (fixes #4783)
  python-package/lightgbm/basic.py
  tests/python_package_test/test_utilities.py
Labels: feature

#5101 [python] make `log_evaluation` callback pickleable
  python-package/lightgbm/callback.py
  tests/python_package_test/test_callback.py
Labels: feature

#5107 [python] make `record_evaluation` callback pickleable
  python-package/lightgbm/callback.py
  tests/python_package_test/test_callback.py
Labels: feature

#5110 [R-package] add assertions to test on lightgbm() weights
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#5109 [python] make `reset_parameter` callback pickleable
  python-package/lightgbm/callback.py
  tests/python_package_test/test_callback.py
Labels: feature
