Repository microsoft/LightGBM, pull requests merged in 2022-01, with the labels that each got.

#4913 [R-package] respect aliases for objective and metric and lgb.train() and lgb.cv()
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#4922 [R-package] [docs] fix calculation of R test coverage (fixes #4919)
  R-package/README.md
  R-package/tests/testthat/test_lgb.unloader.R
Labels: doc

#4923 [R-package] Apply patch for R4.2 on Windows
  src/network/socket_wrapper.hpp
Labels: fix

#4903 [R-package] respect 'verbose' argument in lgb.cv() (fixes #4667)
  R-package/R/lgb.Dataset.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#4933 [ci] Bump version for development
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#4928 gpu allocate memory overflow
  src/treelearner/gpu_tree_learner.cpp
Labels: fix

#4937 [ci] bump CUDA version from 11.4.2 to 11.5.0 at CI
  .github/workflows/cuda.yml
Labels: maintenance

#4941 [R-package] Fix custom objective detection in `print.lgb.Booster()`
  R-package/R/lgb.Booster.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
Labels: fix

#4940 [tests][R-package] use one `#` symbol for comments
  R-package/R/lgb.cv.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_learning_to_rank.R
Labels: maintenance

#4939 [ci] use `-1` for exit code in case of failure
  .github/workflows/r_package.yml
Labels: maintenance

#4938 [docs] minor docs improvements
  docs/FAQ.rst
  python-package/README.rst
Labels: doc

#4920 [dask] add support for custom objective functions (fixes #3934)
  docs/Parallel-Learning-Guide.rst
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: feature

#4950 reduce duplicate computation in poisson, gamma, and tweedie objectives
  src/objective/regression_objective.hpp
Labels: efficiency

#4894 [python-package] support customizing Dataset creation in Booster.refit() (fixes #3038)
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: feature

#4967 [ci] bump CUDA version from `11.5.0` to `11.5.1` at CI
  .ci/setup.sh
  .github/workflows/cuda.yml
Labels: maintenance
