Repository microsoft/LightGBM, pull requests merged in 2022-10, with the labels that each got.

#5510 [ci] prefer CPython in Windows test environment and use safer approach for cleaning up network (fixes #5509)
  .ci/test_windows.ps1
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: awaiting review, blocking, maintenance

#5506 replace `pandas.Series.iteritems` with `pandas.Series.items`
  python-package/lightgbm/basic.py
Labels: maintenance

#5519 [docs] Fix link to Optuna's LightGBMTuner example
  README.md
Labels: doc

#5504 [R-package] [docs] use CRAN canonical form for package links
  R-package/README.md
Labels: doc

#5520 [python-package] prefix is_numpy_1d_array with _
  python-package/lightgbm/basic.py
Labels: maintenance

#5527 [ci] run CI on pull requests targeting release/ branches
  .github/workflows/cuda.yml
  .github/workflows/optional_checks.yml
  .github/workflows/python_package.yml
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
Labels: maintenance

#5528 [ci] run Appveyor checks on PRs targeting release/ branches
  .appveyor.yml
Labels: awaiting review, maintenance

#5526 [R-package] fix test on non-ASCII features in non-UTF8 locales
  R-package/tests/testthat/test_basic.R
Labels: fix

#5503 [ci] [R-package] use R 4.2.1 in Windows CI jobs (fixes #4881)
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  R-package/README.md
  R-package/configure.win
  R-package/tests/testthat/test_dataset.R
Labels: fix

#5521 renamed tmp_num_sample_values to non_na_cnt
  src/io/bin.cpp
Labels: maintenance

#5253 suppress alias warnings with verbosity<0 (fixes #4518)
  include/LightGBM/config.h
  src/application/application.cpp
  src/io/config.cpp
  tests/python_package_test/test_engine.py
Labels: maintenance

#5532 [python-package] prefix cast_numpy_array_to_dtype with _
  python-package/lightgbm/basic.py
Labels: maintenance

#5424 [python-package][R-package] load parameters from model file (fixes #2613)
  R-package/R/lgb.Booster.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_lgb.Booster.R
  helpers/parameter_generator.py
  include/LightGBM/boosting.h
  include/LightGBM/c_api.h
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  src/boosting/gbdt.h
  src/c_api.cpp
  src/io/config_auto.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#5522 renamed cur_cat => cur_cat_idx and added some comments
  src/io/bin.cpp
Labels: maintenance

#5531 [python-package] prefix is_numpy_column_array with _
  python-package/lightgbm/basic.py
Labels: maintenance

#5497 [python-package] add install option to enable printing of time costs
  python-package/README.rst
  python-package/setup.py
Labels: feature

#5481 [tests] Fix cpp streaming data tests
  tests/cpp_tests/test_stream.cpp
Labels: maintenance
