Repository microsoft/LightGBM, pull requests merged in 2022-05, with the labels that each got.

#5190 fix some wrong format specifiers
  src/application/application.cpp
  src/io/config.cpp
  src/io/dataset_loader.cpp
  src/network/linkers_socket.cpp
Labels: fix

#5187 fix precision lost in tree's ToIfElse
  src/io/tree.cpp
Labels: fix

#5169 [ci] fix git checkout for comment-triggered CI jobs
  .github/workflows/r_configure.yml
  .github/workflows/r_solaris.yml
  .github/workflows/r_valgrind.yml
Labels: maintenance

#5192 [R-package] update roles in DESCRIPTION
  R-package/DESCRIPTION
Labels: doc

#5197 [ci] Prevent Python downgrading to pypy on Windows
  .ci/test_windows.ps1
Labels: blocking, maintenance

#5198 [ci] Prevent Python downgrading to pypy on Windows (2)
  .ci/test_windows.ps1
Labels: maintenance

#5199 [R-package] ensure that callbacks respect verbosity from params
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#5189 Fix potential overflow "Multiplication result converted to larger type"
  src/boosting/gbdt.h
  src/io/dataset_loader.cpp
  src/network/linker_topo.cpp
  src/objective/binary_objective.hpp
  src/objective/multiclass_objective.hpp
  src/objective/regression_objective.hpp
  src/objective/xentropy_objective.hpp
  tests/python_package_test/test_sklearn.py
Labels: fix

#5204 [R-package] remove lgb.unloader()
  R-package/NAMESPACE
  R-package/R/lgb.unloader.R
  R-package/demo/weight_param.R
  R-package/man/lgb.unloader.Rd
  R-package/pkgdown/_pkgdown.yml
  R-package/tests/testthat/test_lgb.unloader.R
  docs/FAQ.rst
Labels: breaking

#5208 [R-package] silence more logs in tests
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#5210 [ci] fix R Hub token
  .ci/run_rhub_solaris_checks.R
Labels: maintenance

#5212 [R-package] minor improvements on weight demo
  R-package/demo/weight_param.R
Labels: maintenance

#5116 [python-package][R-package] allow using feature names when retrieving number of bins
  R-package/R/lgb.Dataset.R
  R-package/tests/testthat/test_dataset.R
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: feature

#5215 Cleanup codeowners
  .github/CODEOWNERS
Labels: maintenance

#5209 [R-package] stop automatically calculating eval metrics on training data in lightgbm()
  R-package/R/lightgbm.R
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lgb_shared_params.Rd
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
Labels: breaking

#5226 remove support for Solaris (fixes #5216)
  .ci/run_rhub_solaris_checks.R
  .ci/test_r_package_solaris.sh
  .github/workflows/optional_checks.yml
  .github/workflows/r_solaris.yml
  .github/workflows/triggering_comments.yml
  R-package/DESCRIPTION
  R-package/README.md
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  R-package/tests/testthat/test_learning_to_rank.R
  include/LightGBM/utils/common.h
  include/LightGBM/utils/common_legacy_solaris.h
  src/network/ifaddrs_patch.cpp
  src/network/ifaddrs_patch.h
  src/network/socket_wrapper.hpp
Labels: breaking

#5225 [python-package] make a shallow copy when replacing categorical features with codes (fixes #4596)
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: efficiency

#5230 [ci] switch CRAN mirror to RStudio
  .ci/test_r_package.sh
  .ci/test_r_package_valgrind.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
Labels: blocking, maintenance

#5227 [R-package] silence more logs in unit tests
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#5232 [R-package] remove semicolon in R code
  R-package/R/lgb.Booster.R
Labels: maintenance

#5159 Check existence of inet_pton for win32 in CMakeLists.txt (fixes #5019)
  CMakeLists.txt
  R-package/configure.win
  src/network/socket_wrapper.hpp
Labels: fix

#5213 [python] Fix training on subset constructed without params
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: fix

#5240 [R-package] standardize style for placement of braces
  R-package/R/lgb.convert_with_rules.R
  R-package/R/utils.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#5238 [python] add type hints on sklearn metric and eval wrappers
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5248 Remove leftovers after the drop of Solaris support
  include/LightGBM/utils/common.h
  src/io/tree.cpp
Labels: maintenance

#5250 [R-package] [ci] silence more logs in tests (fixes #4862)
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#5249 [R-package] address linter warnings about portable paths
  R-package/inst/make-r-def.R
  R-package/src/install.libs.R
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#5239 [python] add more type hints on LGBMModel methods
  python-package/lightgbm/sklearn.py
Labels: maintenance
