Repository microsoft/LightGBM, pull requests merged in 2022-04, with the labels that each got.

#4972 [R-package] Promote number of threads to top-level argument in `lightgbm()` and change default to number of cores
  .ci/test_r_package.sh
  .ci/test_r_package_solaris.sh
  .ci/test_r_package_valgrind.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  .vsts-ci.yml
  R-package/DESCRIPTION
  R-package/NAMESPACE
  R-package/R/lgb.restore_handle.R
  R-package/R/lightgbm.R
  R-package/R/utils.R
  R-package/man/lgb.restore_handle.Rd
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
Labels: breaking

#4971 [R-package] Remove `reshape` argument in `predict`
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/demo/multiclass.R
  R-package/demo/multiclass_custom_objective.R
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_Predictor.R
Labels: breaking

#5118 [R-package] Add missed packages into dependencies list
  .github/workflows/static_analysis.yml
  R-package/README.md
Labels: maintenance

#5117 [python-package] remove is_reshape argument in Booster.predict (fixes #5115)
  python-package/lightgbm/basic.py
Labels: breaking

#5121 [R-package] ensure boosting happens in tests on small datasets
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#5125 [docs] use 'docker run --rm' in autoconf instructions
  R-package/README.md
Labels: doc

#4977 [R-package] Keep row names in output from `predict`
  R-package/R/lgb.Predictor.R
  R-package/tests/testthat/test_Predictor.R
Labels: feature

#5126 [ci] Remove temp workaround for graphviz installation
  .ci/test_windows.ps1
Labels: maintenance

#5127 [docs] use 'docker run --rm' in valgrind instructions
  R-package/README.md
Labels: doc

#5120 [ci] use lee-dohm/no-response to close stale issues (fixes #5060)
  .github/no-response.yml
  .github/workflows/no-response.yml
Labels: maintenance

#5129 [ci] fail R macOS CI jobs earlier when installations fail
  .ci/test_r_package.sh
Labels: maintenance

#5136 [ci] have no-response bot post as github-actions user
  .github/workflows/no-response.yml
Labels: maintenance

#5132 [docs] Document behaviour of the first linear estimator
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#5137 [ci] update to R 4.1.3 and use macOS-latest for R jobs (fixes #4990)
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  docs/env.yml
Labels: maintenance

#5141 [R-package] reduce cost of repeated parameter alias checks
  R-package/R/aliases.R
  R-package/tests/testthat/test_parameters.R
Labels: efficiency

#5148 [python] Use predefined constant in feature importance type comparison instead of raw int literal
  python-package/lightgbm/basic.py
Labels: maintenance

#5146 check nullable of bin_mappers in DatasetLoader::CheckCategoricalFeatureNumBin (fix #5145)
  src/io/dataset_loader.cpp
Labels: fix

#5149 [ci] bump CUDA version from `11.5.1` to `11.6.2` at CI
  .github/workflows/cuda.yml
Labels: maintenance

#5152 [ci] fix git checkout for CI jobs (fixes #5151)
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
Labels: maintenance

#5154 [docs] Fix formula in path smoothing docs (fixes #5139)
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#5052 [python-package] remove 'fobj' in favor of passing custom objective function in params (fixes #3244)
  examples/python-guide/advanced_example.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/utils.py
Labels: breaking

#5174 [ci] temporarily pin Azure Devops jobs to ubuntu 20.04
  .vsts-ci.yml
Labels: maintenance

#5168 fix typo in CEGB method name
  src/treelearner/cost_effective_gradient_boosting.hpp
  src/treelearner/serial_tree_learner.cpp
Labels: maintenance

#5122 [R-package] ensure values in params override keyword arguments to predict() (fixes #4670)
  R-package/R/lgb.Booster.R
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_Predictor.R
Labels: fix

#5175 [ci] skip auto-injected tasks at Azure Pipelines
  .vsts-ci.yml
Labels: maintenance

#5172 [ci] Update version of Azure REST API
  docs/_static/js/script.js
Labels: maintenance

#5173 [tests] replace `fobj` with `custom objective` in test comments and make tests stricter
  tests/python_package_test/test_engine.py
Labels: maintenance

#5167 [CUDA] Fix integer overflow in cuda row-wise data
  src/io/cuda/cuda_row_data.cpp
  src/treelearner/cuda/cuda_histogram_constructor.cu
Labels: fix

#5183 [c-api] check number of features when retrieving number of bins
  src/c_api.cpp
  tests/python_package_test/test_basic.py
Labels: fix

#5184 [R-package] allow use of categorical_features in Dataset when raw data does not have column names (fixes #4374)
  R-package/R/lgb.Dataset.R
  R-package/tests/testthat/test_dataset.R
Labels: fix

#5188 [python] remove unused import from `basic.py`
  python-package/lightgbm/basic.py
Labels: maintenance
