Repository microsoft/LightGBM, pull requests merged in 2022-02, with the labels that each got.

#4989 [ci] upgrade to R 4.1.2 in CI, change approach to macOS-latest R CI builds (fixes #4988)
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
Labels: maintenance

#4953 [ci] use conda-forge in Linux and macOS CI jobs
  .ci/setup.sh
  .ci/test.sh
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/python_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
Labels: maintenance

#4992 Add Nyoka to README
  README.md
Labels: doc

#4994 [docs] document `conda-forge` channel preference over `default` one and describe possible workaround for OpenMP conflicts in FAQ
  docs/FAQ.rst
  python-package/README.rst
Labels: doc

#4993 [ci] use conda-forge in Windows CI jobs and Docker images
  .appveyor.yml
  .ci/test_windows.ps1
  .vsts-ci.yml
  docker/dockerfile-python
  docker/gpu/README.md
  docker/gpu/dockerfile.gpu
Labels: maintenance

#4978 [tests][python] remove compatibility code for old versions in tests
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#5006 [python] enforce a floor of Python 3.6 (fixes #5004)
  python-package/setup.py
Labels: maintenance

#4947 [python-package] make record_evaluation compatible with cv (fixes #4943)
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: breaking

#5002 Change docs for feval
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
Labels: doc

#5009 [docs] document rounding behavior of floating point numbers in categorical features
  docs/Advanced-Topics.rst
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: doc

#4974 [R-package] remove behavior where lightgbm() saves model to disk
  R-package/R/lgb.restore_handle.R
  R-package/R/lightgbm.R
  R-package/man/lgb.restore_handle.Rd
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_parameters.R
Labels: breaking

#4985 Pass train dataset parser config to valid dataset loading parser
  src/io/dataset_loader.cpp
Labels: awaiting review, fix

#4893 [python] Start supporting Python 3.10
  .appveyor.yml
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/python_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  python-package/setup.py
Labels: feature

#5007 [R-package] prefer params to keyword argument in lgb.train()
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
  R-package/tests/testthat/test_basic.R
Labels: breaking

#5015 [ci] Enclose Python versions in quotes in config yml files
  .appveyor.yml
  .vsts-ci.yml
Labels: maintenance

#4957 [ci] [docs] use miniforge for readthedocs builds (fixes #4954)
  .ci/test.sh
  .gitignore
  .readthedocs.yaml
  docs/README.rst
  docs/build-docs.sh
  docs/conf.py
  docs/env.yml
  docs/requirements.txt
  docs/requirements_base.txt
Labels: maintenance

#5014 [R-package] raise informative errors directly when Booster creation fails
  R-package/R/lgb.Booster.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#4963 CUDATreeLearner: free GPU memory in destructor if any allocated
  src/treelearner/cuda_tree_learner.cpp
Labels: fix

#4959 [docs] clarify that categorical features will be converted to integers internally
  docs/Advanced-Topics.rst
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: doc

#5022 [ci] use Python 3.8 for `bdist` CI job in old Ubuntu container
  .vsts-ci.yml
Labels: maintenance

#5021 [R-package] remove internal function lgb.check.obj()
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
  R-package/tests/testthat/test_basic.R
Labels: maintenance

#5026 [docs] improve docs for sklearn wrapper
  docs/README.rst
  docs/conf.py
  docs/env.yml
Labels: doc

#5013 [Docs] Weights non-negative for train data
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: doc

#4927 [python-package] add support for pandas nullable types
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
Labels: feature

#4979 Correct documentation for sparse predictions
  include/LightGBM/c_api.h
Labels: doc

#5030 [python] fixes for supporting 2d numpy arrays for predictions, grads and hess in multiclass custom objective and eval
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
Labels: fix
