Repository microsoft/LightGBM, pull requests merged in 2023-11, with the labels that each got.

#6034 [python-package] Allow to pass Arrow table as training data
  .ci/test-python-oldest.sh
  .ci/test.sh
  .ci/test_windows.ps1
  include/LightGBM/arrow.h
  include/LightGBM/arrow.tpp
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  python-package/pyproject.toml
  src/c_api.cpp
  tests/cpp_tests/test_arrow.cpp
  tests/python_package_test/test_arrow.py
Labels: feature

#6171 [R-package] Use `cat()` instead of `print()` for metrics and callbacks
  .ci/lint_r_code.R
  R-package/R/callback.R
  R-package/tests/testthat/test_basic.R
Labels: in progress, maintenance

#6177 allow new files in include/LightGBM
  .gitignore
Labels: maintenance

#6161 [docs] fix broken links
  docs/.linkcheckerrc
  docs/Experiments.rst
  docs/FAQ.rst
  docs/GPU-Performance.rst
  docs/Installation-Guide.rst
  docs/Parallel-Learning-Guide.rst
  docs/gcc-Tips.rst
Labels: doc

#6163 [python-package] Allow to pass Arrow array as labels
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  src/c_api.cpp
  src/io/dataset.cpp
  src/io/metadata.cpp
  tests/python_package_test/test_arrow.py
Labels: awaiting review, feature

#6108 [python-package] fix access to Dataset metadata in scikit-learn custom metrics and objectives
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/utils.py
Labels: breaking

#6180 [R-package] remove unreachable code
  R-package/R/lgb.Booster.R
Labels: blocking, maintenance

#6174 [python-package] Accept numpy generators as `random_state`
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#6179 [R-package] standardize naming of internal functions
  R-package/R/callback.R
  R-package/R/lgb.Booster.R
  R-package/R/lgb.DataProcessor.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.drop_serialized.R
  R-package/R/lgb.importance.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.make_serializable.R
  R-package/R/lgb.model.dt.tree.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.restore_handle.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/R/utils.R
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_utils.R
Labels: maintenance

#6181 [docs] reduce redirects in docs links
  docs/Experiments.rst
  docs/Features.rst
  docs/GPU-Performance.rst
  docs/Installation-Guide.rst
  docs/Parallel-Learning-Guide.rst
  docs/Parameters.rst
  docs/Quick-Start.rst
  include/LightGBM/config.h
Labels: doc

#6156 [python-package] consolidate pandas-to-numpy conversion code
  python-package/lightgbm/basic.py
Labels: maintenance

#6198 [python-package] ignore mypy errors related to ctypes string buffers
  python-package/lightgbm/basic.py
Labels: maintenance

#6166 [python-package] Allow to pass Arrow array as groups
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  python-package/lightgbm/basic.py
  src/io/dataset.cpp
  src/io/metadata.cpp
  tests/python_package_test/test_arrow.py
Labels: feature

#6208 [R-package] Fix inefficiency in retrieving pointers
  R-package/src/lightgbm_R.cpp
Labels: efficiency

#6192 [python-package] fix libpath.py
  python-package/lightgbm/libpath.py
Labels: fix

#6216 [R-package] use safer pattern for error formatting (fixes #6212)
  R-package/src/lightgbm_R.cpp
Labels: awaiting review, blocking, fix
