Repository microsoft/LightGBM, pull requests merged in 2023-10, with the labels that each got.

#6120 [python-package] simplify Dataset._compare_params_for_warning()
  python-package/lightgbm/basic.py
Labels: maintenance

#6114 [python-package] reorganize early stopping callback
  python-package/lightgbm/callback.py
  tests/python_package_test/test_callback.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#6061 [ci] [R-package] test against R 4.3 on Windows
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  CMakeLists.txt
  R-package/README.md
Labels: awaiting review, maintenance

#6124 fix compiler warnings for CPP tests
  tests/cpp_tests/test_byte_buffer.cpp
  tests/cpp_tests/testutils.cpp
Labels: maintenance

#6126 ignore unknown parameters when loading from model file
  src/boosting/gbdt.h
  tests/python_package_test/test_engine.py
Labels: fix

#6130 [ci] [R-package] enforce more {lintr} checks
  .ci/lint_r_code.R
  R-package/demo/basic_walkthrough.R
  R-package/demo/boost_from_prediction.R
  R-package/demo/early_stopping.R
  R-package/tests/testthat.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#5933 [CUDA] CUDA Quantized Training (fixes #5606)
  .ci/check_python_dists.sh
  include/LightGBM/cuda/cuda_algorithms.hpp
  include/LightGBM/cuda/cuda_column_data.hpp
  include/LightGBM/cuda/cuda_metadata.hpp
  include/LightGBM/cuda/cuda_metric.hpp
  include/LightGBM/cuda/cuda_objective_function.hpp
  include/LightGBM/cuda/cuda_row_data.hpp
  include/LightGBM/cuda/cuda_split_info.hpp
  include/LightGBM/cuda/cuda_utils.hu
  include/LightGBM/sample_strategy.h
  src/boosting/cuda/cuda_score_updater.hpp
  src/cuda/cuda_utils.cpp
  src/io/config.cpp
  src/metric/cuda/cuda_binary_metric.hpp
  src/metric/cuda/cuda_pointwise_metric.hpp
  src/metric/cuda/cuda_regression_metric.hpp
  src/treelearner/cuda/cuda_best_split_finder.cpp
  src/treelearner/cuda/cuda_best_split_finder.cu
  src/treelearner/cuda/cuda_best_split_finder.hpp
  src/treelearner/cuda/cuda_data_partition.cpp
  src/treelearner/cuda/cuda_data_partition.cu
  src/treelearner/cuda/cuda_data_partition.hpp
  src/treelearner/cuda/cuda_gradient_discretizer.cu
  src/treelearner/cuda/cuda_gradient_discretizer.hpp
  src/treelearner/cuda/cuda_histogram_constructor.cpp
  src/treelearner/cuda/cuda_histogram_constructor.cu
  src/treelearner/cuda/cuda_histogram_constructor.hpp
  src/treelearner/cuda/cuda_leaf_splits.cpp
  src/treelearner/cuda/cuda_leaf_splits.cu
  src/treelearner/cuda/cuda_leaf_splits.hpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cu
  src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp
Labels: awaiting review, efficiency

#6132 remove unnecessary allocations in HistogramSumReducer
  include/LightGBM/bin.h
Labels: maintenance

#6133 factor out uses of omp_get_num_threads() and omp_get_max_threads() outside of OpenMP wrapper
  src/objective/rank_objective.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/linear_tree_learner.cpp
Labels: maintenance

#6135 set explicit number of threads in every OpenMP `parallel` region
  .ci/lint-cpp.sh
  R-package/src/lightgbm_R.cpp
  include/LightGBM/feature_group.h
  include/LightGBM/tree.h
  include/LightGBM/utils/common.h
  include/LightGBM/utils/threading.h
  src/application/application.cpp
  src/application/predictor.hpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/boosting/gbdt_model_text.cpp
  src/boosting/rf.hpp
  src/boosting/score_updater.hpp
  src/c_api.cpp
  src/io/dataset.cpp
  src/io/dataset_loader.cpp
  src/io/metadata.cpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/io/train_share_states.cpp
  src/io/tree.cpp
  src/metric/binary_metric.hpp
  src/metric/map_metric.hpp
  src/metric/multiclass_metric.hpp
  src/metric/rank_metric.hpp
  src/metric/regression_metric.hpp
  src/metric/xentropy_metric.hpp
  src/objective/binary_objective.hpp
  src/objective/multiclass_objective.hpp
  src/objective/rank_objective.hpp
  src/objective/regression_objective.hpp
  src/objective/xentropy_objective.hpp
  src/treelearner/col_sampler.hpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/data_partition.hpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/gradient_discretizer.cpp
  src/treelearner/leaf_splits.hpp
  src/treelearner/linear_tree_learner.cpp
  src/treelearner/linear_tree_learner.h
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  src/treelearner/voting_parallel_tree_learner.cpp
Labels: fix

#6140 [ci] use `mamba` instead of `conda` in macOS and Linux CI jobs
  .ci/test.sh
Labels: maintenance

#6154 [ci] resolve warning in tests
  tests/python_package_test/test_engine.py
Labels: maintenance
