Repository microsoft/LightGBM, pull requests merged in 2023-05, with the labels that each got.

#5859 [ci] remove R 3.6 macOS CI jobs
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
Labels: blocking, maintenance

#5838 [ci] [python-package] check distributions with pydistcheck
  .ci/check_python_dists.sh
Labels: maintenance

#5858 [ci] [python-package] resolve remaining mypy errors in dask.py
  python-package/lightgbm/dask.py
Labels: maintenance

#5837 [ci] [python-package] replace 'python setup.py' with a shell script
  .appveyor.yml
  .ci/test.sh
  .ci/test_windows.ps1
  .gitignore
  build-python.sh
  docker/dockerfile-python
  docker/gpu/dockerfile.gpu
  docs/FAQ.rst
  docs/GPU-Tutorial.rst
  python-package/README.rst
  python-package/setup.py
Labels: breaking

#5800 Add quantized training (CPU part)
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  docs/Parameters.rst
  include/LightGBM/bin.h
  include/LightGBM/config.h
  include/LightGBM/dataset.h
  include/LightGBM/train_share_states.h
  src/io/config.cpp
  src/io/config_auto.cpp
  src/io/dataset.cpp
  src/io/dense_bin.hpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/io/sparse_bin.hpp
  src/io/train_share_states.cpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/gradient_discretizer.cpp
  src/treelearner/gradient_discretizer.hpp
  src/treelearner/leaf_splits.hpp
  src/treelearner/parallel_tree_learner.h
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  src/treelearner/split_info.hpp
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: awaiting review, efficiency, feature

#5869 [ci] minor fixes to build-python.sh
  build-python.sh
Labels: maintenance

#5870 [ci] use lowercase library names in linker flags
  CMakeLists.txt
  R-package/src/Makevars.win.in
Labels: maintenance

#5873 [ci] use Python 3.11 in linting CI job
  .github/workflows/static_analysis.yml
Labels: maintenance

#5872 [ci] [python-package] move tool configuration to pyproject.toml
  .ci/lint-python.sh
  .ci/test.sh
  build-python.sh
  python-package/README.rst
  python-package/pyproject.toml
  python-package/setup.cfg
Labels: maintenance

#5874 [ci] [python-package] tell mypy 'auto' has a special meaning for feature_name and categorical_feature
  python-package/lightgbm/basic.py
Labels: maintenance

#5881 [docs] recommend a more efficient source installation of the python package
  docs/FAQ.rst
  python-package/README.rst
Labels: doc

#5877 [ci] fix wheel renaming in test.sh
  .ci/test.sh
  .ci/test_windows.ps1
Labels: maintenance

#5883 [ci] [python-package] fix mypy error in Dataset.set_categorical_feature()
  python-package/lightgbm/basic.py
Labels: awaiting review, maintenance

#5886 [ci] [python-package] fix mypy errors in sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5871 [ci] [python-package] use ruff, enforce flake8-bugbear and flake8-comprehensions checks
  .ci/lint-python.sh
  .ci/test.sh
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  python-package/pyproject.toml
  tests/distributed/_test_distributed.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#5880 add CMakeLists options to disable building CLI, installing headers
  .ci/test.sh
  CMakeLists.txt
  python-package/setup.py
Labels: awaiting review, feature

#5903 [ci] use an MRAN snapshot for R 3.6 Linux jobs (fixes #5898)
  .ci/test_r_package.sh
  .ci/test_windows.ps1
Labels: blocking, maintenance

#5884 update MSBuild solution to Windows SDK v10.0, add inet_pton define (fixes #5856)
  windows/LightGBM.vcxproj
Labels: fix
