Repository microsoft/LightGBM, pull requests merged in 2023-01, with the labels that each got.

#5292 [ci][dask][gpu] Run Dask tests with LightGBM GPU version
  tests/python_package_test/test_dask.py
Labels: maintenance

#5662 [ci] [R-package] fix clang 15 warning about unqualified calls (fixes #5661)
  .github/workflows/r_package.yml
  src/io/json11.cpp
Labels: fix

#5638 [ci] run r-package Linux jobs in containers
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
Labels: awaiting review, maintenance

#5671 [ci] fix brew errors in R macOS jobs (fixes #5670)
  .ci/test_r_package.sh
Labels: maintenance

#5656 [python-package] remove `Dataset.feature_penalty`
  python-package/lightgbm/basic.py
Labels: maintenance

#5655 [python-package] make public API members explicit with module-level __all__ variables
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/libpath.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
Labels: breaking

#5659 [ci] [python-package] enforce flake8 checks (fixes #5566)
  .ci/test.sh
  docs/conf.py
  python-package/lightgbm/compat.py
  python-package/setup.py
  tests/python_package_test/test_callback.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#5674 [python-package] fix mypy errors for eval_at and basic
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5649 [docs] encourage use of releases for GUI-only installations
  docs/Installation-Guide.rst
Labels: doc

#5678 [python-package] Fix mypy errors for predict() method
  python-package/lightgbm/dask.py
Labels: maintenance

#5681 bump development version to v3.3.5.99
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  VERSION.txt
Labels: maintenance

#5668 [ci] speed up conda setup for some jobs
  .ci/test.sh
Labels: maintenance

#5689 [ci] get clang-15 from bookworm repository (fixes #5688)
  .github/workflows/r_package.yml
Labels: blocking, maintenance

#5652 [docs] [R-package] mention {bonsai} in the docs
  R-package/README.md
  R-package/cran-comments.md
  README.md
Labels: doc

#5685 [R-package] discourage use of regex for fixed string comparisons
  .ci/lint_r_code.R
  R-package/R/utils.R
  R-package/inst/make-r-def.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
  build_r.R
Labels: maintenance

#5679 [python-package] Fix mypy errors for fit() incompatible signature
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: maintenance
