Repository microsoft/LightGBM, pull requests merged in 2023-06, with the labels that each got.

#5900 [docs] Update Quick Start
  docs/Quick-Start.rst
Labels: doc

#5909 [ci] stop relying on cran.microsoft.com in CI jobs
  .ci/test_r_package.sh
Labels: blocking, maintenance

#5910 [c++] support building with Ninja on Linux
  cmake/IntegratedOpenCL.cmake
  docs/Installation-Guide.rst
Labels: feature

#5818 [python-package] adding max_category_values parameter to create_tree_digraph method (fixes #5687)
  python-package/lightgbm/plotting.py
  tests/python_package_test/test_plotting.py
Labels: feature

#5907 [python-package] ensure 'build-python.sh' always reinstalls (fixes #5906)
  .ci/test_windows.ps1
  build-python.sh
Labels: maintenance

#5925 [ci] remove brew update-reset again (fixes #5670)
  .ci/test_r_package.sh
Labels: blocking, maintenance

#5923 [docs] add quantized training paper to docs
  README.md
Labels: doc

#5759 [python-package] [ci] switch to PEP 517 / 518 builds (remove `setup.py`) (fixes #5061)
  .ci/test.sh
  .ci/test_windows.ps1
  CMakeLists.txt
  build-python.sh
  python-package/MANIFEST.in
  python-package/README.rst
  python-package/lightgbm/libpath.py
  python-package/pyproject.toml
  python-package/setup.cfg
  python-package/setup.py
Labels: awaiting review, breaking

#5890 [dask] hold ports until training
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: fix

#5939 [docs] fix broken links in docs
  docs/.linkcheckerrc
  docs/Parallel-Learning-Guide.rst
Labels: awaiting review, doc

#5937 [python-package] add 'pandas' extra
  python-package/README.rst
  python-package/pyproject.toml
  python-package/setup.cfg
Labels: feature

#5942 [python-package] remove hard dependency on 'scikit-learn', fix minimal runtime dependencies
  python-package/README.rst
  python-package/pyproject.toml
  python-package/setup.cfg
Labels: awaiting review, breaking

#5945 [python-package] ignore pip cache dir in build-python.sh
  build-python.sh
Labels: maintenance
