Repository microsoft/LightGBM, pull requests merged in 2023-08, with the labels that each got.

#6003 [R-package] Fix error when passing categorical features to lightgbm() (fixes #6000)
  R-package/R/lgb.train.R
  R-package/tests/testthat/test_basic.R
Labels: fix

#5999 [python-package] replace np.find_common_type with np.result_type
  python-package/lightgbm/basic.py
Labels: maintenance

#5997 [ci] [R-package] use {lintr} 3.1
  .ci/lint_r_code.R
  .ci/test.sh
  R-package/R/lgb.interprete.R
Labels: maintenance

#6032 [ci] enforce dask version to be >=2023.5.0 in some builds (fixes #6030)
  .ci/test.sh
Labels: blocking, maintenance

#6028 [CUDA] Set GPU device ID in threads
  include/LightGBM/cuda/cuda_column_data.hpp
  include/LightGBM/cuda/cuda_metric.hpp
  include/LightGBM/cuda/cuda_objective_function.hpp
  include/LightGBM/cuda/cuda_utils.h
  src/cuda/cuda_utils.cpp
  src/io/cuda/cuda_column_data.cpp
Labels: fix

#5848 fix percentile computation for regression objectives
  src/objective/regression_objective.hpp
  tests/python_package_test/test_engine.py
Labels: fix

#6039 [ci] fix GPG key download for R Linux jobs (fixes #6038)
  .ci/test_r_package.sh
Labels: awaiting review, blocking, maintenance

#6047 [ci] prevent lock-threads from locking issues with label 'feature request'
  .github/workflows/lock.yml
Labels: awaiting review, maintenance

#6049 [ci] [python-package] add more linting checks
  python-package/lightgbm/basic.py
  python-package/lightgbm/plotting.py
  python-package/pyproject.toml
  tests/distributed/_test_distributed.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/utils.py
Labels: maintenance

#6042 [python-package] make it possible to build wheels without internet connection (fixes #5979)
  build-python.sh
  python-package/README.rst
Labels: fix

#6048 [python-package] use dataclass for CallbackEnv
  .ci/test-python-oldest.sh
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  python-package/pyproject.toml
Labels: maintenance

#6057 [python-package] remove CVBooster._append()
  python-package/lightgbm/engine.py
Labels: maintenance

#6059 [docs] fix broken links
  docs/GPU-Windows.rst
  docs/Parallel-Learning-Guide.rst
Labels: doc
