Repository microsoft/LightGBM, pull requests merged in 2023-09, with the labels that each got.

#6071 [docs] Fix typo in README
  python-package/README.rst
Labels: doc

#6073 reduce verbosity of some log messages
  R-package/tests/testthat/test_basic.R
  src/c_api.cpp
  src/io/dataset.cpp
Labels: maintenance

#5929 Treat position bias via GAM in LambdaMART
  docs/Advanced-Topics.rst
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/dataset.h
  python-package/lightgbm/basic.py
  src/io/config_auto.cpp
  src/io/dataset.cpp
  src/io/metadata.cpp
  src/objective/rank_objective.hpp
  tests/python_package_test/test_engine.py
Labels: in progress, feature

#6005 [R-package] Fix misdetected objective when passing `lgb.Dataset` instance to `lightgbm()`
  R-package/R/lightgbm.R
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
Labels: fix

#6075 [ci] [R-package] test against R 4.3 on Linux and macOS
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
Labels: maintenance

#6017 Fix updates in random forest model using GOSS data sample strategy
  src/boosting/rf.hpp
Labels: fix

#6066 [python-package] simplify processing of pandas data
  python-package/lightgbm/basic.py
  python-package/lightgbm/plotting.py
  tests/python_package_test/test_basic.py
Labels: maintenance

#6083 [ci] [docs] fix broken ACM links
  docs/.linkcheckerrc
Labels: doc

#6085 [docs] add vaex-ml to list of external repositories
  README.md
Labels: doc

#5980 [python-package] [docs] Update key format of eval_hist in docstring example
  python-package/lightgbm/engine.py
Labels: doc

#6076 Release v4.1.0
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/pyproject.toml
Labels: maintenance

#6002 [python-package] Fix misdetected objective after multiple calls to `LGBMClassifier.fit`
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: fix

#6090 bump development version to 4.1.0.99
  .appveyor.yml
  R-package/configure
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6092 [fix] fix quantized training (fixes #5982) (fixes #5994)
  src/io/dataset.cpp
  src/treelearner/leaf_splits.hpp
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/serial_tree_learner.h
  tests/python_package_test/test_dask.py
Labels: fix

#6097 [python-package] fix mypy errors related to eval result tuples
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
Labels: maintenance

#6095 [python-package] mark EarlyStopException as part of public API
  python-package/lightgbm/__init__.py
  python-package/lightgbm/callback.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#6096 [python-package] fix mypy errors related to eval result parsing in callbacks
  python-package/lightgbm/callback.py
Labels: maintenance

#6077 [python-package] [R-package] include more params in model text representation (fixes #6010)
  R-package/tests/testthat/helper.R
  R-package/tests/testthat/test_lgb.Booster.R
  helpers/parameter_generator.py
  include/LightGBM/config.h
  src/io/config_auto.cpp
  tests/python_package_test/test_engine.py
Labels: fix

#6100 [ci] Fix typo in dependencies
  .ci/test.sh
Labels: maintenance

#6098 [python-package] fix mypy error from Dataset.pandas_categorical
  python-package/lightgbm/basic.py
Labels: maintenance

#6105 [python-package] fix mypy error about eval result tuples
  python-package/lightgbm/callback.py
Labels: maintenance

#6107 [ci] ensure correct R version is used on GitHub Actions (fixes #5640)
  .ci/test_r_package_windows.ps1
Labels: maintenance

#6106 [python-package] fix mypy errors in Dataset construction
  python-package/lightgbm/basic.py
Labels: maintenance

#6111 [python-package] remove unnecessary allocations in ctypes code
  python-package/lightgbm/basic.py
Labels: maintenance

#6118 [ci] fix sh-compatibility issue in build-cran-package.sh
  build-cran-package.sh
Labels: maintenance

#6099 [CUDA] drop CUDA 10 support, start supporting CUDA 12 (fixes #5789)
  .ci/check_python_dists.sh
  .github/workflows/cuda.yml
  CMakeLists.txt
  docs/Installation-Guide.rst
Labels: breaking
