Repository microsoft/LightGBM, pull requests merged in 2023-03, with the labels that each got.

#5754 [python-package] add type hints on label
  python-package/lightgbm/basic.py
Labels: maintenance

#5755 [python-package] use keyword arguments in predict() calls
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5756 [python-package] [dask] fix mypy errors about Dask fit() return types
  python-package/lightgbm/dask.py
Labels: maintenance

#5690 [R-package] use C++17 in the CRAN package
  .github/workflows/r_package.yml
  R-package/DESCRIPTION
  R-package/configure
  R-package/configure.ac
  R-package/configure.win
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  build-cran-package.sh
  build_r.R
Labels: breaking

#5766 [python-package] [dask] add type annotations on dask._HostWorkers
  python-package/lightgbm/dask.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#5761 [ci] isolate c_api_test library-loading from Python source tree
  tests/c_api_test/test_.py
Labels: awaiting review, maintenance

#5773 [python-package] add type hints for functions accepting dtypes
  python-package/lightgbm/basic.py
Labels: maintenance

#5771 [python-package] add type hints on sklearn properties
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5724 [python-package] fix mypy errors about validation sets in sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5782 [python-package] fix mypy error about dask._HostWorkers.__eq__()
  python-package/lightgbm/dask.py
Labels: maintenance

#5779 [python-package] fix mypy errors about ctypes pointers
  python-package/lightgbm/basic.py
Labels: maintenance

#5774 [python-package] ignore some mypy errors in _DaskLGBMModel
  python-package/lightgbm/dask.py
Labels: maintenance

#5780 [python-package] fix mypy errors about Dataset.params
  python-package/lightgbm/basic.py
Labels: maintenance

#5778 Fix DEBUG-mode GPU builds
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp
Labels: awaiting review, fix

#5665 [CUDA] Add quantile metric for new CUDA version (contribute to #5163)
  src/metric/cuda/cuda_binary_metric.hpp
  src/metric/cuda/cuda_pointwise_metric.cpp
  src/metric/cuda/cuda_pointwise_metric.cu
  src/metric/cuda/cuda_pointwise_metric.hpp
  src/metric/cuda/cuda_regression_metric.cpp
  src/metric/cuda/cuda_regression_metric.hpp
  src/metric/metric.cpp
  tests/python_package_test/test_engine.py
Labels: awaiting review, feature

#5786 [python-package] fix mypy error about cpu_count() methods
  python-package/lightgbm/compat.py
Labels: maintenance

#5784 [python-package] replace uses of scipy.sparse.issparse() with isinstance()
  python-package/lightgbm/basic.py
Labels: maintenance

#5787 [python-package] add hint on dtypes in Dataset.set_field()
  python-package/lightgbm/basic.py
Labels: maintenance

#5605 [CUDA] Add quantile regression objective for new CUDA version
  include/LightGBM/cuda/cuda_row_data.hpp
  src/objective/cuda/cuda_regression_objective.cpp
  src/objective/cuda/cuda_regression_objective.cu
  src/objective/cuda/cuda_regression_objective.hpp
  src/objective/objective_function.cpp
  tests/python_package_test/test_engine.py
Labels: awaiting review, feature

#5788 [python-package] fix mypy errors about scikit-learn properties
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
Labels: awaiting review, maintenance

#5801 remove unused variables from bin.cpp
  src/io/bin.cpp
Labels: maintenance

#5757 [python-packages] [docs] add type hints and define 'array-like' for X, y, group in scikit-learn interface
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#5790 [python-package] fix mypy errors about custom eval and metric functions
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
Labels: awaiting review, maintenance

#5795 [python-package] fix mypy errors about early stopping rounds
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: awaiting review, maintenance

#5794 [python-package] fix mypy error in Booster.get_split_value_histogram()
  python-package/lightgbm/basic.py
Labels: awaiting review, maintenance

#5793 [python-package] fix type annotations for eval result tracking
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
Labels: awaiting review, maintenance

#5811 [python-package] add type annotations on Booster.trees_to_dataframe() inner functions
  python-package/lightgbm/basic.py
Labels: maintenance

#5813 [python-package] add type annotations on some array methods in basic.py
  python-package/lightgbm/basic.py
Labels: maintenance
