Repository microsoft/LightGBM, pull requests merged in 2023-02, with the labels that each got.

#5703 [ci] restore flake8 checks
  .ci/test.sh
Labels: maintenance

#5706 cast data_index as size_t in cuda_row_data to avoid integer overflow
  src/io/cuda/cuda_row_data.cpp
Labels: fix

#5694 [python-package] add more type hints
  python-package/lightgbm/basic.py
Labels: maintenance

#5698 adjusted bagging_freq parameter description
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#5704 [python-package] remove some inner function definitions
  python-package/lightgbm/basic.py
Labels: maintenance

#5709 [python-package] declare the use of inline type hints
  python-package/MANIFEST.in
  python-package/lightgbm/py.typed
  python-package/setup.py
Labels: maintenance

#5707 [ci] [python-package] enforce 'twine check' and 'check-wheel-contents' on Python distributions
  .ci/check_python_dists.sh
  .ci/test.sh
  .ci/test_windows.ps1
  python-package/setup.py
Labels: maintenance

#5708 [python-package] add type hints on plotting code
  python-package/lightgbm/plotting.py
Labels: maintenance

#5341 [R-package] Accept factor labels and use their levels
  R-package/DESCRIPTION
  R-package/R/aliases.R
  R-package/R/lgb.Booster.R
  R-package/R/lgb.DataProcessor.R
  R-package/R/lightgbm.R
  R-package/man/lgb.configure_fast_predict.Rd
  R-package/man/lightgbm.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/tests/testthat/test_basic.R
Labels: feature

#5710 [python-package] add more type hints in sklearn.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5427 feature: Add serialization of reference dataset
  include/LightGBM/bin.h
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  include/LightGBM/dataset_loader.h
  include/LightGBM/feature_group.h
  include/LightGBM/utils/binary_writer.h
  include/LightGBM/utils/byte_buffer.h
  include/LightGBM/utils/file_io.h
  src/c_api.cpp
  src/io/bin.cpp
  src/io/dataset.cpp
  src/io/dataset_loader.cpp
  src/io/dense_bin.hpp
  src/io/file_io.cpp
  src/io/metadata.cpp
  src/io/sparse_bin.hpp
  tests/cpp_tests/test_byte_buffer.cpp
  tests/cpp_tests/test_serialize.cpp
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: awaiting review, feature

#5711 [python-package] fix mypy errors in compat.py and libpath.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/libpath.py
Labels: maintenance

#5712 [python-package] add Booster.set_leaf_output method
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: feature

#5714 [python-package] fix mypy errors about _InnerPredictor
  python-package/lightgbm/basic.py
Labels: maintenance

#5719 [python-package] fix mypy errors around eval metrics in sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5720 [python-package] fix mypy error about log callback
  python-package/lightgbm/basic.py
Labels: maintenance

#5721 [python-package] fix mypy errors about custom eval functions in sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5728 [python-package] [dask] fix mypy errors regarding predict_proba
  python-package/lightgbm/dask.py
Labels: maintenance

#5718 [python-package] change types in sklearn.py initializations
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5725 [python-package] fix mypy errors about cv() internals
  python-package/lightgbm/engine.py
Labels: maintenance

#5722 [python-package] fix mypy errors about Dataset handle
  python-package/lightgbm/basic.py
Labels: maintenance

#5736 [python-package] fix _LGBM_CustomMetricFunction typing
  python-package/lightgbm/engine.py
Labels: maintenance

#5741 [ci] skip Dask tests on GPU builds
  tests/python_package_test/test_dask.py
Labels: maintenance

#5740 [python-package] use _DatasetHandle type hint
  python-package/lightgbm/basic.py
Labels: awaiting review, maintenance

#5730 [python-package] remove default values in internal functions
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/plotting.py
Labels: maintenance

#5723 [python-package] make some Booster and Dataset attributes private
  python-package/lightgbm/basic.py
Labels: breaking

#5743 [ci] speed up conda setup for macOS and Linux jobs
  .ci/test.sh
Labels: maintenance

#5745 [python-package] add type hints on Dataset feature processing
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
Labels: maintenance

#5726 [python-package] fix mypy error about ctypes array creation
  python-package/lightgbm/basic.py
Labels: awaiting review, maintenance

#5729 [python-package] add more type hints in basic.py
  python-package/lightgbm/basic.py
Labels: maintenance

#5749 [python-package] add type hints on Booster predict() methods
  python-package/lightgbm/basic.py
Labels: maintenance

#5748 [python-package] add type hints on fit() return and callbacks in sklearn.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5747 [python-package] add type hints on feature_name and categorical_feature in sklearn interface
  python-package/lightgbm/sklearn.py
Labels: maintenance

#5752 [python-package] add type hints on raw data passed to Dataset and Booster
  python-package/lightgbm/basic.py
Labels: maintenance

#5753 [python-package] add type hints on group, init_score, and weight
  python-package/lightgbm/basic.py
Labels: maintenance
