Repository microsoft/LightGBM, pull requests merged in 2023-07, with the labels that each got.

#5956 [docs] Add scikit-learn for intersphinx (fixes #5954)
  docs/conf.py
Labels: doc

#5953 [ci] increase valgrind timeout to 6 hours
  .github/workflows/r_valgrind.yml
Labels: blocking, maintenance

#5922 [ci] add Python 3.11 test coverage
  .appveyor.yml
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/python_package.yml
  .vsts-ci.yml
  python-package/pyproject.toml
Labels: maintenance

#5936 [ci] [python-package] Add CI job testing compatibility with oldest possible versions
  .ci/test-python-oldest.sh
  .github/workflows/python_package.yml
Labels: maintenance

#5948 [docs] add versionadded notes for v4.0.0 features
  R-package/R/lgb.Booster.R
  R-package/R/lgb.drop_serialized.R
  R-package/R/lgb.make_serializable.R
  R-package/R/lgb.restore_handle.R
  R-package/R/lightgbm.R
  R-package/man/lgb.configure_fast_predict.Rd
  R-package/man/lgb.drop_serialized.Rd
  R-package/man/lgb.make_serializable.Rd
  R-package/man/lgb.restore_handle.Rd
  R-package/man/lgb_shared_params.Rd
  R-package/man/lightgbm.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/man/print.lgb.Booster.Rd
  R-package/man/summary.lgb.Booster.Rd
  docs/Parallel-Learning-Guide.rst
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
Labels: awaiting review, doc

#5959 [docs] fix broken link to contributor GitHub account
  docs/FAQ.rst
Labels: doc

#5970 [python-package] avoid data_has_header check in predict()
  python-package/lightgbm/basic.py
Labels: maintenance

#5952 Release v4.0.0
  .appveyor.yml
  R-package/configure
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#5975 bump development version to 4.0.0.99
  .appveyor.yml
  R-package/configure
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#5961 [python-package] make _InnerPredictor construction stricter
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
Labels: maintenance

#5984 Fix Python Dockerfile
  docker/dockerfile-python
Labels: doc

#5996 [ci] use newer h5py in AppVeyor jobs (fixes #5995)
  .ci/test_windows.ps1
  R-package/tests/testthat/test_dataset.R
Labels: maintenance

#5991 [R-package] remove unused internal variables
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.Predictor.R
  R-package/R/lgb.convert_with_rules.R
  R-package/R/lgb.cv.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: maintenance

#5992 [R-package] consolidate testing constants in helpers file
  R-package/tests/testthat/helper.R
  R-package/tests/testthat/test_Predictor.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_custom_objective.R
  R-package/tests/testthat/test_dataset.R
  R-package/tests/testthat/test_learning_to_rank.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.importance.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
  R-package/tests/testthat/test_weighted_loss.R
Labels: maintenance

#5998 [ci] simplify CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance
