Repository microsoft/LightGBM, pull requests merged in 2023-12, with the labels that each got.

#6193 [docs] remove links to Laurae++ site
  README.md
  docs/FAQ.rst
  docs/Parameters.rst
Labels: doc

#6167 [python-package] Allow to pass Arrow table and array as init scores
  include/LightGBM/c_api.h
  include/LightGBM/dataset.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  src/io/dataset.cpp
  src/io/metadata.cpp
  tests/python_package_test/test_arrow.py
Labels: feature

#6227 Fix null handling for Arrow data
  include/LightGBM/arrow.tpp
  tests/cpp_tests/test_arrow.cpp
  tests/python_package_test/test_arrow.py
Labels: fix

#6224 [R-package] change CRAN maintainer
  R-package/DESCRIPTION
Labels: maintenance

#6218 [python-package] take shallow copy of dataframe in predict (fixes #6195)
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: fix

#6226 [R-package] [c++] add tighter multithreading control, avoid global OpenMP side effects (fixes #4705, fixes #5102)
  .ci/lint-cpp.sh
  CMakeLists.txt
  R-package/NAMESPACE
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.importance.R
  R-package/R/lgb.interprete.R
  R-package/R/lgb.model.dt.tree.R
  R-package/R/lgb.plot.importance.R
  R-package/R/lgb.plot.interpretation.R
  R-package/R/lgb.restore_handle.R
  R-package/R/lgb.train.R
  R-package/R/multithreading.R
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/dim.Rd
  R-package/man/dimnames.lgb.Dataset.Rd
  R-package/man/getLGBMThreads.Rd
  R-package/man/get_field.Rd
  R-package/man/lgb.Dataset.Rd
  R-package/man/lgb.Dataset.construct.Rd
  R-package/man/lgb.Dataset.create.valid.Rd
  R-package/man/lgb.Dataset.save.Rd
  R-package/man/lgb.Dataset.set.categorical.Rd
  R-package/man/lgb.Dataset.set.reference.Rd
  R-package/man/lgb.configure_fast_predict.Rd
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.dump.Rd
  R-package/man/lgb.get.eval.result.Rd
  R-package/man/lgb.importance.Rd
  R-package/man/lgb.interprete.Rd
  R-package/man/lgb.load.Rd
  R-package/man/lgb.model.dt.tree.Rd
  R-package/man/lgb.plot.importance.Rd
  R-package/man/lgb.plot.interpretation.Rd
  R-package/man/lgb.restore_handle.Rd
  R-package/man/lgb.save.Rd
  R-package/man/lgb.train.Rd
  R-package/man/predict.lgb.Booster.Rd
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  R-package/man/setLGBMThreads.Rd
  R-package/man/set_field.Rd
  R-package/man/slice.Rd
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/helper.R
  R-package/tests/testthat/test_multithreading.R
  R-package/vignettes/basic_walkthrough.Rmd
  build-cran-package.sh
  include/LightGBM/c_api.h
  include/LightGBM/utils/openmp_wrapper.h
  src/c_api.cpp
  src/utils/openmp_wrapper.cpp
  tests/c_api_test/test_.py
Labels: fix

#6210 [python-package] Add tests for passing Arrow arrays with empty chunks
  include/LightGBM/arrow.h
  tests/python_package_test/test_arrow.py
Labels: maintenance

#6232 fix errors from MSVC '/permissive-' mode (fixes #6230)
  include/LightGBM/arrow.h
Labels: fix

#6168 [python-package] Allow to pass Arrow table for prediction
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  tests/python_package_test/test_arrow.py
Labels: feature

#6234 Add msvc conformance check
  CMakeLists.txt
Labels: maintenance

#6222 [ci] Upgrade Azure VMSS to use Mariner Linux
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
Labels: maintenance

#6233 [ci] [R-package] allow more possibly-lost warnings from valgrind
  .ci/test_r_package_valgrind.sh
Labels: maintenance

#6191 release v4.2.0
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6245 Fix small typo and grammar in docs
  docs/FAQ.rst
  docs/GPU-Targets.rst
  docs/GPU-Tutorial.rst
  docs/GPU-Windows.rst
  docs/Quick-Start.rst
Labels: doc

#6241 bump development version to 4.2.0.99
  .appveyor.yml
  R-package/configure
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6247 [ci] [docs] add Oliver to CODEOWNERS
  .github/CODEOWNERS
  docs/FAQ.rst
Labels: awaiting review, doc

#6237 [ci] [R-package] speed up valgrind job
  .ci/test_r_package_valgrind.sh
Labels: maintenance

#6246 [R-package] remove readRDS.lgb.Booster() and saveRDS.lgb.Booster()
  R-package/NAMESPACE
  R-package/R/readRDS.lgb.Booster.R
  R-package/R/saveRDS.lgb.Booster.R
  R-package/man/readRDS.lgb.Booster.Rd
  R-package/man/saveRDS.lgb.Booster.Rd
  R-package/pkgdown/_pkgdown.yml
  R-package/tests/testthat/test_lgb.Booster.R
Labels: breaking

#5981 [ci] upgrade to GoogleTest v1.14.0 (fixes #5976)
  CMakeLists.txt
Labels: maintenance
