Repository microsoft/LightGBM, pull requests merged in 2024-04, with the labels that each got.

#6407 [ci] Fix Azure Pipeline Agents
  .vsts-ci.yml
Labels: maintenance

#6364 [R-package] Speed-up lgb.importance()
  R-package/R/lgb.model.dt.tree.R
  R-package/tests/testthat/test_lgb.model.dt.tree.R
Labels: efficiency

#6416 [ci] clean source directory at the beginning of every Azure DevOps build
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
Labels: maintenance

#6410 [c++] remove unused variable 'need_connect_cnt'
  src/network/linkers_socket.cpp
Labels: maintenance

#6395 [ci] reduce hard-coding of host architecture
  .ci/setup.sh
  .ci/test.sh
  .ci/test_r_package.sh
Labels: maintenance

#6403 [python-package] prevent build-python.sh from modifying already-installed dependencies
  build-python.sh
Labels: maintenance

#6406 [python-package] allow use of early_stopping_round<=0 to turn off early stopping (fixes #6401)
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_callback.py
  tests/python_package_test/test_engine.py
Labels: fix

#6396 [docs] document how to use a custom objective function via the C API
  docs/Parameters.rst
  include/LightGBM/config.h
  src/boosting/gbdt.cpp
Labels: doc

#6266 [ci] make shell scripts stricter
  .ci/append_comment.sh
  .ci/check_python_dists.sh
  .ci/lint-cpp.sh
  .ci/lint-python.sh
  .ci/rerun_workflow.sh
  .ci/set_commit_status.sh
  .ci/setup.sh
  .ci/test-python-oldest.sh
  .ci/test.sh
  .ci/test_r_package.sh
  .ci/test_r_package_valgrind.sh
  .ci/trigger_dispatch_run.sh
  .github/workflows/r_package.yml
  R-package/recreate-configure.sh
  build-cran-package.sh
  build-python.sh
  docs/build-docs.sh
Labels: maintenance

#6394 remove unnecessary omp single that cause deadlock (fixes #6273)
  src/utils/openmp_wrapper.cpp
  tests/python_package_test/test_basic.py
Labels: fix

#6418 [cmake] [c++] use .dylib extension unconditionally on macOS
  .ci/test.sh
  CMakeLists.txt
  R-package/.Rbuildignore
  R-package/README.md
  R-package/src/install.libs.R
  build-cran-package.sh
  build-python.sh
  docs/Installation-Guide.rst
  python-package/lightgbm/libpath.py
Labels: breaking

#6375 [ci] raise floors on CI dependencies
  .ci/conda-envs/README.md
  .ci/conda-envs/ci-core-py37.txt
  .ci/conda-envs/ci-core.txt
  .ci/test.sh
  .ci/test_windows.ps1
Labels: maintenance

#6425 [ci] Skip Arrow tests on AppVeyor, use Intel macOS runners, upgrade to XCode 14.3 on macOS jobs, disable MacOS MPI jobs
  .ci/setup.sh
  .ci/test_windows.ps1
  .github/workflows/python_package.yml
  .github/workflows/r_package.yml
  tests/python_package_test/test_arrow.py
Labels: blocking, maintenance

#6426 upgrade CMake in dockerfile-cli (fixes #6420)
  docker/dockerfile-cli
Labels: fix
