Repository microsoft/LightGBM, pull requests merged in 2024-12, with the labels that each got.

#6564 [ci] Introduce `typos` pre-commit hook
  .ci/test-r-package-windows.ps1
  .github/workflows/lock.yml
  .pre-commit-config.yaml
  .typos.toml
  CMakeLists.txt
  R-package/R/lgb.Booster.R
  R-package/R/lgb.importance.R
  R-package/R/lgb.model.dt.tree.R
  R-package/R/lightgbm.R
  R-package/demo/cross_validation.R
  R-package/demo/early_stopping.R
  R-package/man/lgb.configure_fast_predict.Rd
  R-package/man/lgb.importance.Rd
  R-package/man/lgb.model.dt.tree.Rd
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_custom_objective.R
  R-package/tests/testthat/test_lgb.interprete.R
  R-package/tests/testthat/test_lgb.plot.interpretation.R
  cmake/Sanitizer.cmake
  docker/README.md
  docs/Parameters.rst
  docs/_static/js/script.js
  examples/lambdarank/train.conf
  examples/regression/train.conf
  include/LightGBM/cuda/cuda_algorithms.hpp
  include/LightGBM/dataset.h
  include/LightGBM/utils/common.h
  include/LightGBM/utils/random.h
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  src/boosting/bagging.hpp
  src/boosting/gbdt_model_text.cpp
  src/io/metadata.cpp
  src/network/linker_topo.cpp
  src/objective/rank_objective.hpp
  src/treelearner/cuda/cuda_best_split_finder.cpp
  src/treelearner/cuda/cuda_data_partition.cu
  src/treelearner/cuda/cuda_data_partition.hpp
  src/treelearner/cuda/cuda_histogram_constructor.cpp
  src/treelearner/cuda/cuda_histogram_constructor.hpp
  src/treelearner/cuda/cuda_leaf_splits.cpp
  src/treelearner/cuda/cuda_leaf_splits.cu
  src/treelearner/cuda/cuda_leaf_splits.hpp
  src/treelearner/data_parallel_tree_learner.cpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/gpu_tree_learner.cpp
  src/treelearner/kernels/histogram_16_64_256.cu
  src/treelearner/ocl/histogram16.cl
  src/treelearner/ocl/histogram256.cl
  src/treelearner/ocl/histogram64.cl
  src/treelearner/parallel_tree_learner.h
  src/treelearner/serial_tree_learner.cpp
  src/treelearner/voting_parallel_tree_learner.cpp
  tests/cpp_tests/test_chunked_array.cpp
  tests/cpp_tests/test_stream.cpp
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#6696 [docs] update installation guide
  docs/Installation-Guide.rst
  docs/_static/js/script.js
Labels: doc

#6735 [python-package] simplify scikit-learn 1.6+ tags support
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#6736 [c++] include <cstdint> wherever uint8_t is used
  include/LightGBM/bin.h
  include/LightGBM/cuda/cuda_column_data.hpp
  include/LightGBM/cuda/cuda_row_data.hpp
  include/LightGBM/dataset.h
  include/LightGBM/feature_group.h
  include/LightGBM/train_share_states.h
  include/LightGBM/tree.h
  src/c_api.cpp
  src/io/cuda/cuda_column_data.cpp
  src/io/json11.cpp
Labels: maintenance

#6742 [ci] set upper bound on dask
  .ci/conda-envs/ci-core.txt
Labels: maintenance

#6721 [python-package] do not copy column-major numpy arrays when creating Dataset
  python-package/lightgbm/basic.py
  tests/python_package_test/test_basic.py
Labels: efficiency

#6738 [c++] fix parallel_tree_learner_split_info
  src/treelearner/split_info.hpp
Labels: fix

#6746 [R-package] Avoid bashisms (non-POSIX code) in R-package/configure
  R-package/configure
  R-package/configure.ac
Labels: fix

#6752 [fix] resolve potential attack in linker connection building
  src/network/linkers_socket.cpp
Labels: fix

#6751 [python-package] do not copy column-major numpy arrays when predicting
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: efficiency

#6755 [ci] use Ruff linter instead of isort
  .pre-commit-config.yaml
  R-package/tests/testthat/test_basic.R
  examples/python-guide/notebooks/interactive_plot_example.ipynb
  python-package/lightgbm/basic.py
  python-package/pyproject.toml
  src/objective/rank_objective.hpp
  src/treelearner/kernels/histogram_16_64_256.cu
Labels: maintenance

#6760 [ci] remove Docker volumes during Azure cleanup
  .vsts-ci.yml
Labels: maintenance

#6757 [ci] fix linkchecker job
  .ci/test.sh
  docs/.linkcheckerrc
Labels: maintenance

#6749 [python-package] simplify eval result printing
  python-package/lightgbm/callback.py
Labels: maintenance

#6762 [python-package] Rename `cvfolds` variable into `cvbooster` in `engine.cv` function
  python-package/lightgbm/engine.py
Labels: maintenance

#6754 [ci] Add Release Drafter workflow
  .github/workflows/no_response.yml
  .github/workflows/release_drafter.yml
Labels: maintenance

#6761 [python-package] stop relying on string concatenation / splitting for cv() eval results
  python-package/lightgbm/callback.py
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: maintenance

#6753 [python-package] Fix inconsistency in `predict()` output shape for 1-tree models
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: fix
