Repository microsoft/LightGBM, pull requests merged in 2024-06, with the labels that each got.

#6471 [ci] [R-package] add new linters from {lintr} 3.1.1
  .ci/lint_r_code.R
  .ci/test.sh
Labels: maintenance

#6472 [ci] upgrade linters to latest version
  .ci/get_workflow_status.py
  .nuget/create_nuget.py
  .pre-commit-config.yaml
  docs/conf.py
  helpers/check_dynamic_dependencies.py
  helpers/parameter_generator.py
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/libpath.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#6468 [python-package] remove uses of deprecated NumPy random number generation APIs, require 'numpy>=1.17.0'
  .gitignore
  docs/Python-Intro.rst
  examples/python-guide/logistic_regression.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
  tests/python_package_test/conftest.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#6402 [python-package] clarify max_depth warning and limit when it is emitted
  docs/Parameters-Tuning.rst
  include/LightGBM/config.h
  python-package/lightgbm/sklearn.py
  src/io/config.cpp
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#6470 [python-package] add a few type hints in LGBMModel.fit()
  python-package/lightgbm/sklearn.py
Labels: awaiting review, maintenance

#6442 [R-package] skip integer categorical feature check when building dataset subset (fixes #6412)
  .ci/test_r_package.sh
  R-package/R/lgb.Dataset.R
  R-package/tests/testthat/test_dataset.R
Labels: fix

#6467 [python-package] Add support for NumPy 2.0, test against nightly versions of dependencies (fixes #6454)
  .ci/test-python-latest.sh
  .github/workflows/python_package.yml
  python-package/lightgbm/basic.py
  python-package/lightgbm/engine.py
  tests/c_api_test/test_.py
  tests/python_package_test/test_arrow.py
  tests/python_package_test/test_basic.py
Labels: feature

#6391 [ci] [python-package] add arm64 macOS wheels
  .ci/lint-python.sh
  .ci/test.sh
  .github/workflows/python_package.yml
  CMakeLists.txt
Labels: feature

#6439 release v4.4.0
  .appveyor.yml
  R-package/R/lgb.Booster.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.model.dt.tree.R
  R-package/configure
  R-package/cran-comments.md
  R-package/man/lgb.dump.Rd
  R-package/man/lgb.model.dt.tree.Rd
  R-package/man/lgb.save.Rd
  R-package/man/lgb.slice.Dataset.Rd
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/pyproject.toml
Labels: maintenance

#6485 bump development version to 4.4.0.99
  .appveyor.yml
  R-package/configure
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6483 chore: update dataset_loader.cpp
  src/io/dataset_loader.cpp
Labels: maintenance

#6487 [ci] [python-package] run macOS x86_64 tests on macOS 12 (Monterey), stop manually setting macOS wheel tags
  .ci/setup.sh
  .ci/test.sh
  .vsts-ci.yml
Labels: breaking

#6488 [ci] remove unnecessary package installations in CI
  .ci/setup.sh
Labels: maintenance

#6490 [docs] remove pmml redirect, simplify some other docs
  .ci/test_windows.ps1
  README.md
  pmml/README.md
  python-package/README.rst
Labels: doc

#6493 [python-package] Change build settings to set strict-config to false
  .github/workflows/cuda.yml
  .github/workflows/python_package.yml
  .vsts-ci.yml
  python-package/pyproject.toml
Labels: maintenance

#6495 [ci] [docs] fix link-checks job
  .github/workflows/linkchecker.yml
  docs/FAQ.rst
  docs/GPU-Windows.rst
Labels: maintenance

#6499 [docs] [R-package] update cran-comments.md
  R-package/cran-comments.md
Labels: doc

#6497 [ci] reduce repetition of BUILD_DIRECTORY in CI scripts
  .ci/test.sh
  .ci/test_r_package.sh
  .ci/test_windows.ps1
Labels: maintenance

#6502 [R-package] Use `Rf_`-prefixed versions of protect/unprotect
  R-package/src/lightgbm_R.cpp
Labels: maintenance
