Repository microsoft/LightGBM, pull requests merged in 2024-11, with the labels that each got.

#6709 [ci] check PowerShell scripts with PSScriptAnalyzer (part 2)
  .ci/install-opencl.ps1
  .ci/test-r-package-windows.ps1
  .ci/test-windows.ps1
  .ci/test.sh
Labels: maintenance

#6711 [ci] check JavaScript code with `biome` tool
  .ci/lint-js.sh
  .ci/lint-python-bash.sh
  .ci/test.sh
  .editorconfig
  biome.json
  docs/_static/js/script.js
  examples/binary_classification/forced_splits.json
  examples/regression/forced_bins.json
  examples/regression/forced_bins2.json
  python-package/README.rst
Labels: maintenance

#6710 [ci] check PowerShell scripts with PSScriptAnalyzer (part 3)
  .ci/install-opencl.ps1
  .ci/lint-powershell.ps1
  .ci/test-r-package-windows.ps1
  .ci/test-windows.ps1
  .ci/test.sh
Labels: maintenance

#6713 [ci] [R-package] re-enable 'rchk' checks
  .github/workflows/r_package.yml
Labels: maintenance

#6718 [python-package] adapt to scikit-learn 1.6 testing changes, pin more packages in R 3.6 CI jobs
  .ci/install-old-r-packages.R
  .ci/test-r-package.sh
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: blocking, maintenance

#6715 [docs] add note about pyodide support
  README.md
Labels: doc

#6733 [ci] [python-package] [R-package] adapt to scikit-learn check_sample_weight_equivalence changes, stop testing against R 3.6 on Linux
  .ci/install-old-r-packages.R
  .ci/test-r-package.sh
  .github/workflows/r_package.yml
  python-package/lightgbm/sklearn.py
Labels: blocking, maintenance
