Repository microsoft/LightGBM, pull requests merged in 2024-05, with the labels that each got.

#6432 [R-package] always name the shared library 'lightgbm', not 'lib_lightgbm'
  CMakeLists.txt
  R-package/NAMESPACE
  R-package/R/lightgbm.R
  R-package/src/install.libs.R
  build-cran-package.sh
  build_r.R
Labels: maintenance

#6274 [python-package] Allow to pass early stopping min delta in params
  R-package/tests/testthat/test_lgb.Booster.R
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/engine.py
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/io/config_auto.cpp
  tests/python_package_test/test_engine.py
Labels: feature

#6409 [c++] remove uses of '..' in headers
  CMakeLists.txt
  build-cran-package.sh
  include/LightGBM/utils/common.h
Labels: awaiting review, maintenance

#6445 [docs] ensure pkgdown site index accurately reflects R-package public API (fixes #6444)
  R-package/pkgdown/_pkgdown.yml
Labels: doc

#6443 deprecate HDFS support
  CMakeLists.txt
  docs/Installation-Guide.rst
  python-package/README.rst
Labels: maintenance

#6263 [python-package] upgrade to scikit-build-core 0.9.3
  python-package/pyproject.toml
Labels: awaiting review, maintenance

#6449 [ci] Add dependabot configuration
  .github/dependabot.yml
Labels: maintenance

#6446 [R-package] [python-package] deprecate Dataset arguments to cv() and train()
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/lightgbm.R
  R-package/R/utils.R
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/man/lightgbm.Rd
  R-package/tests/testthat/test_basic.R
  examples/python-guide/advanced_example.py
  examples/python-guide/notebooks/interactive_plot_example.ipynb
  examples/python-guide/plot_example.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_utilities.py
Labels: maintenance

#6398 [R-package] expose start_iteration to dump/save/lgb.model.dt.tree
  R-package/R/lgb.Booster.R
  R-package/R/lgb.model.dt.tree.R
  R-package/man/lgb.dump.Rd
  R-package/man/lgb.model.dt.tree.Rd
  R-package/man/lgb.save.Rd
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_lgb.model.dt.tree.R
Labels: feature

#6457 [cmake] switch to FindCUDAToolkit
  CMakeLists.txt
Labels: maintenance

#6458 [ci] simplify CI configurations, parallelize compilation, test CUDA on Ubuntu 22.04
  .appveyor.yml
  .ci/test.sh
  .ci/test_windows.ps1
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/python_package.yml
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
Labels: maintenance

#6465 [ci] fix CUDA 11.8 builds (fixes #6466)
  .ci/test.sh
  .ci/test_windows.ps1
Labels: awaiting review, blocking, maintenance

#6459 [python-package] drop Python 3.6 support, add Python 3.12
  .ci/conda-envs/ci-core-py38.txt
  .ci/test-python-oldest.sh
  .ci/test.sh
  .ci/test_windows.ps1
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/python_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  python-package/pyproject.toml
Labels: breaking

#6463 [ci] further simplify CI configurations
  .appveyor.yml
  .ci/check_python_dists.sh
  .ci/get_workflow_status.py
  .ci/setup.sh
  .ci/test.sh
  .ci/test_r_package_valgrind.sh
  .ci/test_windows.ps1
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/optional_checks.yml
  .github/workflows/python_package.yml
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
Labels: maintenance

#6447 [python-package] make LGBMDeprecationWarning inherit from FutureWarning
  python-package/lightgbm/basic.py
Labels: maintenance

#6213 [R-package] Use ALTREP system to return C++-allocated arrays
  R-package/src/lightgbm_R.cpp
Labels: efficiency

#6451 [cmake] always target Windows SDK v10.x when using Visual Studio generators (fixes #6448)
  CMakeLists.txt
Labels: awaiting review, fix
