Repository microsoft/LightGBM, pull requests merged in 2024-10, with the labels that each got.

#6623 [c++] Add Bagging by Query for Lambdarank
  docs/Parameters.rst
  include/LightGBM/config.h
  include/LightGBM/cuda/cuda_objective_function.hpp
  include/LightGBM/objective_function.h
  include/LightGBM/sample_strategy.h
  src/boosting/bagging.hpp
  src/boosting/gbdt.cpp
  src/io/config.cpp
  src/io/config_auto.cpp
  src/objective/rank_objective.hpp
  tests/python_package_test/test_engine.py
Labels: awaiting review, effectiveness, feature

#6663 [ci] replace uses of 'mamba' with 'conda', use Python 12 for test-python-latest-job
  .ci/test.sh
  .github/workflows/python_package.yml
Labels: blocking, maintenance

#6539 [ci] Update CUDA versions for CI
  .github/workflows/cuda.yml
Labels: maintenance

#6655 [docs] use consistent naming for R-package and Python-package across the repo
  .ci/check-python-dists.sh
  .ci/test-python-oldest.sh
  .ci/test-r-package-windows.ps1
  .ci/test-r-package.sh
  CMakeLists.txt
  R-package/README.md
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/vignettes/basic_walkthrough.Rmd
  build-cran-package.sh
  build-python.sh
  build_r.R
  cmake/modules/FindLibR.cmake
  docker/README.md
  docs/FAQ.rst
  docs/Parallel-Learning-Guide.rst
  python-package/README.rst
  python-package/pyproject.toml
  tests/c_api_test/test_.py
Labels: doc

#6664 [ci] Restore MPI jobs on macOS
  .github/workflows/python_package.yml
Labels: maintenance

#6651 [python-package] require `scikit-learn>=0.24.2`, make scikit-learn estimators compatible with `scikit-learn>=1.6.0dev`
  .ci/test-python-latest.sh
  .ci/test-python-oldest.sh
  .ci/test.sh
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
  tests/python_package_test/test_sklearn.py
Labels: fix

#6646 [ci] fix shellcheck warnings in CI scripts
  .ci/setup.sh
  .ci/test-r-package.sh
  .ci/test.sh
Labels: maintenance

#6569 [c++] Fix `dump_model()` information for root node
  include/LightGBM/cuda/cuda_tree.hpp
  include/LightGBM/tree.h
  python-package/lightgbm/basic.py
  src/boosting/gbdt.cpp
  src/boosting/rf.hpp
  src/io/cuda/cuda_tree.cpp
  src/io/cuda/cuda_tree.cu
  src/io/tree.cpp
  src/treelearner/cuda/cuda_leaf_splits.cpp
  src/treelearner/cuda/cuda_leaf_splits.hpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cpp
  src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp
  src/treelearner/serial_tree_learner.cpp
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/utils.py
Labels: awaiting review, fix

#6679 [python-package] ignore scikit-learn 'check_sample_weight_equivalence' estimator check (fixes #6678)
  .ci/conda-envs/ci-core-py38.txt
  python-package/lightgbm/sklearn.py
Labels: maintenance

#6676 [ci] enable OpenMP support in cpp tests
  .ci/test-windows.ps1
  .ci/test.sh
Labels: awaiting review, maintenance

#6670 [python-package] deprecate support for H2O 'datatable'
  docs/Python-Intro.rst
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
Labels: maintenance

#6641 [ci] fix some shellcheck warnings in package-building scripts
  build-cran-package.sh
  build-python.sh
Labels: maintenance

#6685 [ci] add shellcheck, use latest pre-commit hook versions
  .pre-commit-config.yaml
  python-package/lightgbm/basic.py
Labels: maintenance

#6567 [GPU] Add support for linear tree with device=gpu
  src/io/config.cpp
  src/treelearner/linear_tree_learner.cpp
  src/treelearner/linear_tree_learner.h
  src/treelearner/tree_learner.cpp
Labels: awaiting review, feature

#6688 [cmake] group sanitizer options together
  CMakeLists.txt
Labels: maintenance

#6690 [ci] fix build of LightGBM with MSVS GUI
  windows/LightGBM.vcxproj
Labels: maintenance

#6691 [docs] group logically external projects in README and add some new libraries
  README.md
Labels: doc

#6689 [ci] set `MinimumVisualStudioVersion` to MSVS 2015
  windows/LightGBM.sln
Labels: maintenance

#6695 [docs] fix inaccurate comment for `force_col_wise` param with CUDA version
  src/io/config.cpp
Labels: doc

#6686 [docs] Remove only cpu note due to gpu support for linear trees
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#6698 [python-package] remove MSVS solution files from sdist
  build-python.sh
Labels: maintenance

#6673 [ci] Fix version matching between RTD pages and R-package pages
  docs/_static/js/script.js
  docs/conf.py
Labels: maintenance

#6545 [ci] [R-package] remove code for 'rchk' checks
  .ci/setup.sh
  .ci/test-r-package.sh
  .ci/test.sh
Labels: maintenance

#6704 [ci] check PowerShell scripts with PSScriptAnalyzer (part 1)
  .ci/lint-powershell.ps1
  .ci/lint-r-code.R
  .ci/test-r-package-windows.ps1
  .ci/test-windows.ps1
  .ci/test.sh
  .editorconfig
Labels: maintenance

#6706 [python-package] remove support for passing 'feature_name' and 'categorical_feature' through train() and cv()
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
Labels: breaking
