Repository microsoft/LightGBM, pull requests merged in 2024-09, with the labels that each got.

#6636 [ci] fix linux runners running out of disk space (fixed #6635)
  .vsts-ci.yml
Labels: maintenance

#6625 [docs] add supertree in README
  README.md
Labels: doc

#6621 fix some shellcheck warnings
  .ci/check-python-dists.sh
  .ci/lint-cpp.sh
  .ci/rerun-workflow.sh
  .ci/set-commit-status.sh
  .ci/trigger-dispatch-run.sh
  R-package/recreate-configure.sh
  docs/build-docs.sh
Labels: maintenance

#6626 [ci] prevent Python tests from leaving behind files
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_plotting.py
Labels: maintenance

#6579 [python-package] limit when num_boost_round warnings are emitted (fixes #6324)
  docs/Parameters.rst
  python-package/lightgbm/engine.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/utils.py
Labels: maintenance

#6637 [ci] prevent C API tests from leaving files behind (fixes #6361)
  tests/c_api_test/test_.py
Labels: maintenance

#6654 [ci] [python-package] temporarily stop testing against scikit-learn nightlies, load lib_lightgbm earlier
  .ci/conda-envs/ci-core.txt
  .ci/test-python-latest.sh
  docs/FAQ.rst
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/libpath.py
Labels: blocking, maintenance

#6647 [cmake] remove unused variable
  CMakeLists.txt
Labels: maintenance

#6642 [ci] [R-package] re-enable R-devel clang16 job (fixes #6607)
  .github/workflows/r_package.yml
Labels: maintenance

#6648 [cmake] simplify SWIG config
  CMakeLists.txt
Labels: maintenance
