Repository microsoft/LightGBM, pull requests merged in 2024-03, with the labels that each got.

#6339 [ci] [python-package] check for untyped definitions with mypy
  .ci/test.sh
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
Labels: maintenance

#6357 [ci] Fix R 3.6 tests, dask tests, compatibility with dask>=2024.3.1
  .ci/test.sh
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  python-package/lightgbm/compat.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#6370 [ci] put ceiling on graphviz in Python 3.7 jobs
  .ci/test.sh
Labels: maintenance

#6371 [docs] remove language about CUDA version being experimental (fixes #6340)
  docs/Installation-Guide.rst
  docs/_static/js/script.js
  python-package/README.rst
Labels: doc

#6024 Fix single row prediction performance in a multi-threaded environment
  include/LightGBM/config.h
  src/c_api.cpp
  tests/cpp_tests/test_single_row.cpp
Labels: efficiency

#6353 [python-package] Allow to pass Arrow table with boolean columns to dataset
  include/LightGBM/arrow.h
  include/LightGBM/arrow.tpp
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  tests/cpp_tests/test_arrow.cpp
  tests/python_package_test/test_arrow.py
Labels: feature

#6346 [ci] [docs] update some docs and CI dependencies
  .ci/test.sh
  docs/env.yml
Labels: maintenance

#6373 [ci] prevent trailing whitespace, ensure files end with newline
  .ci/install-clang-devel.sh
  .pre-commit-config.yaml
  R-package/LICENSE
  R-package/cran-comments.md
  SECURITY.md
  build-cran-package.sh
  docs/Advanced-Topics.rst
  docs/Features.rst
  docs/GPU-Targets.rst
  docs/GPU-Tutorial.rst
  docs/Key-Events.md
  docs/Makefile
  docs/_static/images/artifacts-download.svg
  docs/_static/images/artifacts-fetching.svg
  docs/_static/images/artifacts-not-available.svg
  docs/_static/images/dask-concat.svg
  docs/_static/images/dask-initial-setup.svg
  examples/README.md
  examples/binary_classification/train.conf
  examples/binary_classification/train_linear.conf
  examples/lambdarank/README.md
  examples/lambdarank/train.conf
  examples/multiclass_classification/train.conf
  examples/parallel_learning/train.conf
  examples/python-guide/README.md
  examples/regression/train.conf
  examples/xendcg/README.md
  examples/xendcg/train.conf
  include/LightGBM/bin.h
  include/LightGBM/network.h
  include/LightGBM/utils/common.h
  pmml/README.md
  src/c_api.cpp
  src/treelearner/kernels/histogram_16_64_256.hu
  src/treelearner/leaf_splits.hpp
  src/treelearner/ocl/histogram16.cl
  src/treelearner/ocl/histogram256.cl
  src/treelearner/ocl/histogram64.cl
  swig/StringArray.i
  swig/pointer_manipulation.i
  tests/cpp_tests/testutils.cpp
  windows/LightGBM.vcxproj.filters
Labels: maintenance

#6368 [docs] [ci] encourage use of `cmake --build`
  .ci/test.sh
  .ci/test_windows.ps1
  docker/dockerfile-cli
  docker/gpu/dockerfile-cli-only-distroless.gpu
  docker/gpu/dockerfile-cli-only.gpu
  docker/gpu/dockerfile.gpu
  docs/GPU-Tutorial.rst
  docs/Installation-Guide.rst
  tests/cpp_tests/test_single_row.cpp
  tests/cpp_tests/testutils.cpp
Labels: doc
