Repository microsoft/LightGBM, pull requests merged in 2024-02, with the labels that each got.

#6287 bump development version to 4.3.0.99
  .appveyor.yml
  R-package/configure
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6299 [ci] [R-package] pin to older setup-pandoc for R 3.6 jobs (fixes #6298)
  .github/workflows/r_package.yml
Labels: blocking, maintenance

#6293 [R-package] Rename `slice()` to `lgb.slice.Dataset()`
  R-package/DESCRIPTION
  R-package/NAMESPACE
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.cv.R
  R-package/man/lgb.slice.Dataset.Rd
  R-package/tests/testthat/test_dataset.R
Labels: breaking

#6307 [ci] fix installation of clang-18 (fixes #6306)
  .ci/install-clang-devel.sh
Labels: maintenance

#6305 [ci] ensure shell script exit codes are in range 0-255
  .ci/append_comment.sh
  .ci/check_python_dists.sh
  .ci/install_opencl.ps1
  .ci/lint-cpp.sh
  .ci/lint-python.sh
  .ci/rerun_workflow.sh
  .ci/set_commit_status.sh
  .ci/setup.sh
  .ci/test-python-oldest.sh
  .ci/test.sh
  .ci/test_r_package.sh
  .ci/test_r_package_valgrind.sh
  .ci/test_windows.ps1
  .ci/trigger_dispatch_run.sh
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/optional_checks.yml
  .github/workflows/python_package.yml
  .github/workflows/r_configure.yml
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  R-package/recreate-configure.sh
  build-cran-package.sh
  build-python.sh
  docs/build-docs.sh
  docs/conf.py
Labels: maintenance

#6308 [ci] enable ruff-format on some files, add pre-commit config
  .ci/get_workflow_status.py
  .ci/lint-python.sh
  .ci/test.sh
  .nuget/create_nuget.py
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/conf.py
  helpers/check_dynamic_dependencies.py
  helpers/parameter_generator.py
  python-package/pyproject.toml
Labels: maintenance

#6323 [ci] fix no-response permissions
  .github/workflows/no-response.yml
Labels: maintenance

#6330 [ci] remove workflow_dispatch from no-response configuration
  .github/workflows/no-response.yml
Labels: maintenance

#6019 Fix calculation of number of bins in FindGroup
  src/io/dataset.cpp
  src/treelearner/gpu_tree_learner.cpp
Labels: fix

#6333 [python-package] fix mypy error about pyarrow data
  .ci/test.sh
  python-package/lightgbm/basic.py
Labels: maintenance

#6317 [ci] [python-package] enable ruff-format on tests and examples
  .pre-commit-config.yaml
  examples/python-guide/advanced_example.py
  examples/python-guide/dask/ranking.py
  examples/python-guide/dataset_from_multi_hdf5.py
  examples/python-guide/logistic_regression.py
  examples/python-guide/notebooks/interactive_plot_example.ipynb
  examples/python-guide/plot_example.py
  examples/python-guide/simple_example.py
  examples/python-guide/sklearn_example.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
  tests/c_api_test/test_.py
  tests/cpp_tests/test.py
  tests/distributed/_test_distributed.py
  tests/distributed/conftest.py
  tests/python_package_test/test_arrow.py
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_callback.py
  tests/python_package_test/test_consistency.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_dual.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_plotting.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/test_utilities.py
  tests/python_package_test/utils.py
Labels: maintenance

#6327 ENH more stable gradient of CrossEntropy
  src/objective/xentropy_objective.hpp
Labels: awaiting review, breaking

#6314 [c++] Fix memory leak in Arrow table implementation
  include/LightGBM/arrow.h
Labels: fix

#6301 [c++][fix] Support Quantized Training with Categorical Features on CPU
  R-package/src/Makevars.in
  R-package/src/Makevars.win.in
  src/io/train_share_states.cpp
  src/treelearner/feature_histogram.cpp
  src/treelearner/feature_histogram.hpp
  src/treelearner/monotone_constraints.hpp
  src/treelearner/serial_tree_learner.cpp
  tests/python_package_test/test_engine.py
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: awaiting review, feature

#6334 [ci] [python-package] enforce 'pylint' checks (fixes #4308)
  python-package/lightgbm/basic.py
  python-package/lightgbm/plotting.py
  python-package/pyproject.toml
  tests/distributed/_test_distributed.py
Labels: maintenance

#6341 [python-package] remove unused type alias
  python-package/lightgbm/basic.py
Labels: maintenance

#6336 [ci] [python-package] enable ruff-format on all Python code
  python-package/lightgbm/__init__.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/libpath.py
  python-package/lightgbm/plotting.py
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
Labels: maintenance

#6342 [c++] remove unnecessary include in CLI
  src/main.cpp
Labels: maintenance

#6345 [ci] ignore ruff-format changes in git blame (fixes #6304)
  .git-blame-ignore-revs
Labels: maintenance
