Repository microsoft/LightGBM, pull requests merged in 2024-01, with the labels that each got.

#6254 [docs] Add LightGBMLSS to README
  README.md
Labels: doc

#6209 [R-package] Remove non-beneficial parallelization
  R-package/src/lightgbm_R.cpp
Labels: efficiency

#6256 [ci] update issue-locking workflow
  .github/workflows/lock.yml
Labels: maintenance

#6253 [python-package] fix mypy error about pandas categorical features
  python-package/lightgbm/basic.py
Labels: maintenance

#6259 [cmake] [swig] use CMake's built-in file-copying mechanisms instead of 'cp'
  CMakeLists.txt
Labels: awaiting review, fix

#6258 [R-package] [ci] switch vignettes from 'rmarkdown' to 'markdown'
  .ci/test_r_package.sh
  .ci/test_r_package_windows.ps1
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
  R-package/DESCRIPTION
  R-package/README.md
  R-package/vignettes/basic_walkthrough.Rmd
  docs/env.yml
Labels: maintenance

#6260 [cmake] [c++] require CMake 3.18+
  CMakeLists.txt
  docs/GPU-Windows.rst
  docs/Installation-Guide.rst
  python-package/pyproject.toml
Labels: breaking

#6251 [c++] include OpenMP-control files in MSBuild solution file (fixes #6238)
  windows/LightGBM.vcxproj
  windows/LightGBM.vcxproj.filters
Labels: fix

#6268 [cmake] [CUDA] ignore CUDA-specific source files in non-CUDA builds (fixes #6267)
  CMakeLists.txt
Labels: fix

#6272 [CUDA] Add arch=8.9 to CUDA_ARCHS for RTX 40XX
  CMakeLists.txt
Labels: fix

#6283 [ci] fix conda env creation in 'regular' CI job (fixes #6282)
  .ci/test.sh
Labels: maintenance

#6277 release v4.3.0
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance
