Repository microsoft/LightGBM, pull requests merged in 2024-07, with the labels that each got.

#6500 [R-package]: add num_trees_per_iter, num_trees, and num_iter methods
  R-package/R/lgb.Booster.R
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  R-package/tests/testthat/test_lgb.Booster.R
Labels: feature

#6310 [python-package] Add `feature_names_in_` attribute for scikit-learn estimators (fixes #6279)
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: feature

#6515 cmake: add missing lib_lightgbm_swig.so to lightgbmlib.jar on linux
  CMakeLists.txt
Labels: fix

#6503 [ci] resolve shellcheck errors in .ci/check_python_dists.sh
  .ci/check_python_dists.sh
Labels: maintenance

#6484 [CMake] Use CMAKE_MSVC_RUNTIME_LIBRARY to apply /MT
  CMakeLists.txt
Labels: maintenance

#6508 [ci] [R-package] run 'R CMD check' as a foreground task
  .ci/test_r_package.sh
Labels: maintenance

#6521 [docs] fix FAQ markdown
  docs/FAQ.rst
Labels: doc

#6518 [ci] prevent `lgb.model` and `lgb.pkl` files being left behind after testing
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#6514 Remove template parameters from copy constructor
  src/io/dense_bin.hpp
  src/io/multi_val_dense_bin.hpp
  src/io/multi_val_sparse_bin.hpp
  src/io/sparse_bin.hpp
Labels: maintenance

#6528 [doc] fix documentation for quantized training
  docs/Parameters.rst
  include/LightGBM/config.h
Labels: doc

#6530 [tests][python] fix nan in pandas bool column
  tests/python_package_test/test_engine.py
Labels: maintenance

#6526 [python-package] avoid overwriting dependencies via 'build-python.sh install'
  build-python.sh
Labels: maintenance

#6532 [test][python] fix pandas DeprecationWarning about `is_sparse` function
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
Labels: maintenance

#6478 Avoid copy on Refit
  include/LightGBM/boosting.h
  src/application/application.cpp
  src/boosting/gbdt.cpp
  src/boosting/gbdt.h
  src/c_api.cpp
Labels: efficiency

#6527 [ci] restore aarch64 linux builds (fixes #6509)
  .ci/test.sh
  .vsts-ci.yml
  python-package/lightgbm/compat.py
Labels: maintenance

#6494 [ci] [R-package] add arm64 macOS R-package CI job (fixes #6481)
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
Labels: maintenance

#6534 [c++] remove HDFS support (fixes #6436)
  CMakeLists.txt
  build-python.sh
  docs/Installation-Guide.rst
  docs/_static/js/script.js
  python-package/README.rst
  src/io/file_io.cpp
Labels: awaiting review, breaking

#6428 [python-package] respect 'verbose' setting when using custom objective function (fixes #6014)
  src/io/config.cpp
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/test_utilities.py
Labels: fix

#6523 [ci] [R-package] add CI jobs covering more CRAN "additional checks", fix R_NO_REMAP warnings (fixes #6369)
  .ci/install-clang-devel.sh
  .ci/run-r-cmd-check.sh
  .ci/test_r_package.sh
  .github/workflows/r_package.yml
  R-package/src/lightgbm_R.cpp
  R-package/src/lightgbm_R.h
  include/LightGBM/utils/log.h
Labels: awaiting review, maintenance

#6536 [docs] update and simplify installation docs
  R-package/README.md
  docs/FAQ.rst
  docs/Installation-Guide.rst
  python-package/README.rst
Labels: doc

#6540 [ci] [R-package] use --no-xattrs when re-tarring CRAN-style package
  build-cran-package.sh
Labels: maintenance

#6489 [cmake] Some improvements to handling of OpenMP on macOS
  CMakeLists.txt
Labels: fix

#6546 [docs] Add conda downloads badge
  python-package/README.rst
Labels: doc

#6542 [ci] update codeowners
  .github/CODEOWNERS
Labels: maintenance

#6524 [python-package] Correctly recognize LGBMClassifier(num_class=2, objective="multiclass") as multiclass classification
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: fix

#6554 [ci] [R-package] help linker find libstdc++.so.1 in clang18 job (fixes #6553)
  .github/workflows/r_package.yml
Labels: maintenance

#6552 [docs] remove outdated docs from the repo
  README.md
  docs/Advanced-Topics.rst
  docs/GPU-Tutorial.rst
  docs/GPU-Windows.rst
  docs/Installation-Guide.rst
  docs/Key-Events.md
  docs/_static/images/gcc-comparison-2.png
  docs/_static/images/screenshot-added-manual-entry-in-cmake.png
  docs/_static/images/screenshot-advanced-system-settings.png
  docs/_static/images/screenshot-boost-compiled.png
  docs/_static/images/screenshot-configured-and-generated-cmake.png
  docs/_static/images/screenshot-configured-lightgbm.png
  docs/_static/images/screenshot-create-directory.png
  docs/_static/images/screenshot-debug-run.png
  docs/_static/images/screenshot-downloading-cmake.png
  docs/_static/images/screenshot-environment-variables.png
  docs/_static/images/screenshot-files-to-remove.png
  docs/_static/images/screenshot-git-for-windows.png
  docs/_static/images/screenshot-lightgbm-in-cli-with-gpu.png
  docs/_static/images/screenshot-lightgbm-with-gpu-support-compiled.png
  docs/_static/images/screenshot-mingw-installation.png
  docs/_static/images/screenshot-mingw-makefiles-to-use.png
  docs/_static/images/screenshot-r-mingw-used.png
  docs/_static/images/screenshot-segmentation-fault.png
  docs/_static/images/screenshot-system.png
  docs/_static/images/screenshot-use-gpu.png
  docs/gcc-Tips.rst
Labels: doc

#6557 [docs] remove link to Roadmap (fixes #6556)
  CONTRIBUTING.md
Labels: doc

#6549 [docs] Add NuGet version badge
  README.md
Labels: doc

#6559 [ci] revert clang-18 LD_LIBRARY_PATH workaround
  .github/workflows/r_package.yml
Labels: maintenance

#6562 [docs] fix link to multiple OpenMP issue description
  docs/FAQ.rst
Labels: doc

#6563 [ci] modify CodeQL settings
  .vsts-ci.yml
Labels: maintenance

#6558 [python-package] [docs] Expand class docs for Dataset
  R-package/DESCRIPTION
  R-package/R/lgb.Dataset.R
  R-package/man/lgb.Dataset.Rd
  docs/env.yml
  python-package/lightgbm/basic.py
Labels: doc

#6568 [docs] Update badge for Link checks workflow
  README.md
Labels: doc

#6570 [docs] update GitHub Actions badges in README
  README.md
Labels: awaiting review, doc

#6538 release v4.5.0
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
Labels: awaiting review, maintenance

#6574 [ci] ask pip to always install local artifact but not download package from PyPI
  build-python.sh
Labels: blocking, maintenance

#6575 bump development version to 4.5.0.99
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6573 [ci] fix MSVC warning about builds in temp directory
  .ci/test_r_package_windows.ps1
  .ci/test_windows.ps1
Labels: maintenance

#6576 [docs] add conda version badge
  README.md
  python-package/README.rst
Labels: doc

#6581 [ci] place all CI helpers under the .ci folder and use - instead of _ in their names
  .appveyor.yml
  .ci/append-comment.sh
  .ci/check-dynamic-dependencies.py
  .ci/check-python-dists.sh
  .ci/create-nuget.py
  .ci/get-workflow-status.py
  .ci/install-opencl.ps1
  .ci/lint-r-code.R
  .ci/parameter-generator.py
  .ci/rerun-workflow.sh
  .ci/set-commit-status.sh
  .ci/test-r-package-valgrind.sh
  .ci/test-r-package-windows.ps1
  .ci/test-r-package.sh
  .ci/test-windows.ps1
  .ci/test.sh
  .ci/trigger-dispatch-run.sh
  .github/workflows/optional_checks.yml
  .github/workflows/r_package.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/triggering_comments.yml
  .vsts-ci.yml
  docs/Parameters.rst
  docs/README.rst
  src/io/config_auto.cpp
Labels: awaiting review, maintenance
