Repository microsoft/LightGBM, pull requests merged in 2025-04, with the labels that each got.

#6872 [ci] [python-package] re-enable scikit-build-core binary stripping
  .ci/check-python-dists.sh
  .ci/setup.sh
  .ci/test-windows.ps1
  .ci/test.sh
  python-package/pyproject.toml
Labels: blocking, maintenance

#6858 [python-package] enforce keyword args in internal functions
  python-package/lightgbm/basic.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/engine.py
  python-package/lightgbm/plotting.py
  tests/python_package_test/test_plotting.py
Labels: maintenance

#6850 [R-package] Ensure print.lgb.Booster() works when objective is not explicitly set
  R-package/R/lgb.Booster.R
  R-package/tests/testthat/test_lgb.Booster.R
Labels: fix

#6852 [python-package] Load parameters from model string
  python-package/lightgbm/basic.py
  tests/python_package_test/test_engine.py
Labels: awaiting review, breaking

#6887 [python-package] Add specific error messages to some `test_basic` tests
  tests/python_package_test/test_basic.py
Labels: maintenance

#6894 [python-package] drop support for h2o datatable
  docs/Python-Intro.rst
  docs/conf.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#6904 [python-package] Add superfluous-else-raise (RET506) rule to Ruff
  docs/conf.py
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
  python-package/pyproject.toml
Labels: maintenance
