Repository microsoft/LightGBM, pull requests merged in 2025-05, with the labels that each got.

#6897 [docs][python] update types in docstring
  python-package/lightgbm/basic.py
  python-package/lightgbm/sklearn.py
Labels: awaiting review, doc

#6919 [ci] skip self-hosted Linux CI jobs
  .vsts-ci.yml
Labels: maintenance

#6905 [docs] document use of EffVer
  README.md
  docs/Installation-Guide.rst
Labels: awaiting review, doc

#6893 [python-package] Add specific error messages to `test_basic` and `test_dask` tests
  tests/python_package_test/test_basic.py
  tests/python_package_test/test_dask.py
Labels: maintenance

#6925 [python-package] Add specific error messages to `test_engine`
  tests/python_package_test/test_engine.py
Labels: maintenance

#6921 [ci] skip NuGet creation
  .vsts-ci.yml
Labels: awaiting review, maintenance

#6926 [python-package] Add more specific error messages to `test_engine`
  tests/python_package_test/test_engine.py
Labels: maintenance

#6927 [python-package] Add specific error messages to `test_plotting`
  tests/python_package_test/test_plotting.py
Labels: maintenance
