Repository microsoft/LightGBM, pull requests merged in 2025-07, with the labels that each got.

#6086 [ROCm] add support for ROCm/HIP device
  .gitignore
  CMakeLists.txt
  include/LightGBM/cuda/cuda_algorithms.hpp
  include/LightGBM/cuda/cuda_rocm_interop.h
  include/LightGBM/cuda/cuda_split_info.hpp
  include/LightGBM/cuda/vector_cudahost.h
  src/cuda/cuda_algorithms.cu
  src/metric/cuda/cuda_pointwise_metric.cu
  src/objective/cuda/cuda_binary_objective.cu
  src/objective/cuda/cuda_rank_objective.cu
  src/treelearner/cuda/cuda_best_split_finder.cu
  src/treelearner/cuda/cuda_data_partition.cu
  src/treelearner/cuda/cuda_gradient_discretizer.cu
  src/treelearner/cuda/cuda_histogram_constructor.cu
  src/treelearner/cuda/cuda_leaf_splits.cu
  src/treelearner/cuda/cuda_single_gpu_tree_learner.cu
Labels: feature

#6979 [docs] [ci] skip scikit-learn 1.7.1 in docs build, make tests compatible with pandas 3.0, use new Azure DevOps pool
  .vsts-ci.yml
  docs/env.yml
  tests/python_package_test/test_basic.py
Labels: maintenance

#6958 [ci] [CUDA] Switch to GitHub runner for GPU CI
  .github/workflows/cuda.yml
Labels: maintenance

#6977 [python-package] Follow symlinks to lib_lightgbm in library-loading
  python-package/lightgbm/__init__.py
  python-package/lightgbm/libpath.py
Labels: feature

#6898 [python-package] Fix mypy checks in `compat.py`
  python-package/lightgbm/compat.py
Labels: fix

#6896 [ci] Drop support for Python 3.7 and Python 3.8
  .appveyor.yml
  .ci/conda-envs/ci-core-py38.txt
  .ci/conda-envs/ci-core-py39.txt
  .ci/pip-envs/requirements-oldest.txt
  .ci/test-windows.ps1
  .ci/test.sh
  .github/workflows/python_package.yml
  python-package/README.rst
  python-package/pyproject.toml
Labels: breaking
