Repository microsoft/LightGBM, pull requests merged in 2025-01, with the labels that each got.

#6766 [CUDA] remove src/treelearner/kernels
  CMakeLists.txt
  src/treelearner/kernels/histogram_16_64_256.cu
  src/treelearner/kernels/histogram_16_64_256.hu
Labels: maintenance

#6771 [ci] pin more dependencies in Python 3.8 environment
  .ci/conda-envs/ci-core-py38.txt
Labels: blocking, maintenance

#6765 [ci][python-package] add testing for the shape of raw score predictions
  tests/python_package_test/test_engine.py
Labels: maintenance

#6764 [ci] lock inactive issues and PRs at different time
  .github/workflows/lock.yml
Labels: maintenance

#6763 [ci] add yaml files linter to pre-commit hook but skip some rules for now (Part 1)
  .pre-commit-config.yaml
  .yamllint.yml
Labels: maintenance

#6781 [python-package] Infer feature names from `pyarrow.Table`
  python-package/lightgbm/basic.py
  tests/python_package_test/test_arrow.py
Labels: fix

#6669 [ci] [python-package] build macOS x86_64 wheels on macOS 13 (Ventura)
  .ci/setup.sh
  .github/workflows/r_package.yml
  .vsts-ci.yml
Labels: maintenance

#6789 [ci] fix errors about indentation in yaml files (Part 2)
  .github/workflows/cuda.yml
  .github/workflows/python_package.yml
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .github/workflows/triggering_comments.yml
  .vsts-ci.yml
  .yamllint.yml
  R-package/pkgdown/_pkgdown.yml
Labels: maintenance

#6778 [c++] Fixed Predictor lifecycle and trees initialization in Contrib mode
  src/boosting/gbdt.h
  src/c_api.cpp
  tests/cpp_tests/test_single_row.cpp
Labels: fix

#6794 [ci] fix errors about comments indentation in yaml files (Part 3)
  .vsts-ci.yml
  .yamllint.yml
Labels: maintenance

#6773 [python-package] do not copy column-major numpy arrays when creating Dataset from list of arrays
  include/LightGBM/c_api.h
  python-package/lightgbm/basic.py
  src/c_api.cpp
  tests/python_package_test/test_basic.py
Labels: breaking

#6801 [ci] remove pandas before testing that LightGBM can be imported without extra deps
  .ci/test.sh
Labels: maintenance

#6668 [python-package] support Python 3.13
  .ci/test-windows.ps1
  .ci/test.sh
  .github/workflows/cuda.yml
  .github/workflows/linkchecker.yml
  .github/workflows/python_package.yml
  .github/workflows/static_analysis.yml
  .readthedocs.yaml
  .vsts-ci.yml
  docs/README.rst
  docs/env.yml
  python-package/pyproject.toml
Labels: feature

#6804 [ci] fix errors about comments indentation in yaml files (Part 4)
  .github/workflows/cuda.yml
  .github/workflows/lock.yml
  .github/workflows/no_response.yml
  .github/workflows/optional_checks.yml
  .github/workflows/r_package.yml
  .github/workflows/r_valgrind.yml
  .github/workflows/static_analysis.yml
  .github/workflows/triggering_comments.yml
  .vsts-ci.yml
  .yamllint.yml
Labels: maintenance
