Repository microsoft/LightGBM, pull requests merged in 2025-02, with the labels that each got.

#6812 [CUDA] fix setting of CUDA architectures and enable support for NVIDIA Blackwell
  .ci/check-python-dists.sh
  .github/workflows/cuda.yml
  CMakeLists.txt
Labels: feature

#6785 [python-package] Separately check whether `pyarrow` and `cffi` are installed
  python-package/lightgbm/basic.py
  python-package/lightgbm/compat.py
  tests/python_package_test/conftest.py
  tests/python_package_test/test_arrow.py
Labels: fix

#6817 [ci] [python-package] update pre-commit hooks to latest versions
  .pre-commit-config.yaml
  examples/parallel_learning/train.conf
  examples/regression/train.conf
  examples/xendcg/train.conf
  python-package/lightgbm/basic.py
  python-package/lightgbm/callback.py
  python-package/lightgbm/dask.py
  python-package/lightgbm/plotting.py
  src/treelearner/parallel_tree_learner.h
  tests/python_package_test/test_arrow.py
  tests/python_package_test/test_engine.py
  tests/python_package_test/test_sklearn.py
  tests/python_package_test/utils.py
Labels: maintenance

#6813 [ci] validate pyproject file by json schema
  .pre-commit-config.yaml
Labels: maintenance

#6816 [ci] fix valgrind workflow
  .github/workflows/optional_checks.yml
  .github/workflows/r_valgrind.yml
Labels: maintenance

#6783 [python-package] support sub-classing scikit-learn estimators
  docs/FAQ.rst
  python-package/lightgbm/dask.py
  python-package/lightgbm/sklearn.py
  tests/python_package_test/test_dask.py
  tests/python_package_test/test_sklearn.py
Labels: breaking

#6714 [R-package] require lgb.Dataset, remove support for passing 'colnames' and 'categorical_feature' for lgb.train() and lgb.cv()
  R-package/R/callback.R
  R-package/R/lgb.Dataset.R
  R-package/R/lgb.convert_with_rules.R
  R-package/R/lgb.cv.R
  R-package/R/lgb.train.R
  R-package/R/utils.R
  R-package/man/lgb.cv.Rd
  R-package/man/lgb.train.Rd
  R-package/src/install.libs.R
  R-package/tests/testthat/test_basic.R
  R-package/tests/testthat/test_lgb.Booster.R
  R-package/tests/testthat/test_parameters.R
  build_r.R
Labels: breaking

#6796 release v4.6.0
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  docs/Parameters.rst
  include/LightGBM/config.h
  python-package/pyproject.toml
Labels: maintenance

#6826 bump development version to v4.6.0.99
  .appveyor.yml
  R-package/configure
  R-package/cran-comments.md
  R-package/pkgdown/_pkgdown.yml
  VERSION.txt
  python-package/pyproject.toml
Labels: maintenance

#6837 [ci] [R-package] add CI job using clang-20
  .github/workflows/r_package.yml
Labels: maintenance

#6808 [ci] consolidate R package installs into a CI script
  .ci/install-r-deps.R
  .ci/test-r-package-valgrind.sh
  .ci/test-r-package-windows.ps1
  .ci/test-r-package.sh
  .github/workflows/r_package.yml
  .github/workflows/static_analysis.yml
  .vsts-ci.yml
Labels: maintenance
