Repository microsoft/LightGBM, pull requests merged in 2025-06, with the labels that each got.

#6866 [ci] update to 1ES image pool
  .vsts-ci.yml
Labels: maintenance

#6933 [docs] fix link to "Parallel Algorithm for Decision Tree" paper
  README.md
  docs/Features.rst
Labels: doc

#6923 [swig] fix memory leak in swig interface
  swig/lightgbmlib.i
Labels: fix

#6950 [ci] [R-package] Add period after specified linter names in `nolint` comments
  .ci/install-r-deps.R
  R-package/R/utils.R
  R-package/inst/make-r-def.R
  R-package/src/install.libs.R
  R-package/tests/testthat.R
  R-package/tests/testthat/test_utils.R
  build_r.R
Labels: maintenance

#6955 [python-package] Add specific error messages to `test_dask` tests
  tests/python_package_test/test_dask.py
Labels: maintenance
